<?php
// $Id$

/**
 * @file
 * Implements language definitions for Lingwo Dictionary
 */

/**
 * Per-language settings array
 */

// TODO: We're loading these from PHP files for now
$GLOBALS['LANG_SETTINGS'] = array();
require_once 'lingwo_language.pl.inc';
//require_once (drupal_get_path('module', 'lingwo_dictionary') .'/lingwo_language/lingwo_language.pl.inc');

function lingwo_language_load($lang) {
  // TODO: loads the node which represents this language.
  // TODO: We will have one 'canonical' node for each language.  Its id
  // will be stored in a variable.  This will look up the node id and load
  // it.
}

function lingwo_language_settings($lang) {
  // TODO: we should load the language node, decode its body and return it.
  global $LANG_SETTINGS;
  return $LANG_SETTINGS[$lang];
}

function lingwo_language_fields($lang, $pos) {
  $settings = lingwo_language_settings($lang);
  return $settings['fields'][$pos];
}

