<?php
// $Id$

/**
 * @file
 * Integrate Anki into Drupal
 */

/**
 * Implementation of hook_menu().
 */
function anki_menu() {
  $items = array();
  $items['admin/settings/anki'] = array(
    'title' => 'Anki',
    'description' => 'Settings for the Anki module.',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('anki_admin_settings'),
    'file' => 'anki.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

/*
 * API functions
 */

function anki_server_connect() {
  require_once(drupal_get_path('module', 'anki') .'/anki_server.php');
  return new AnkiServer(anki_server_url());
}

/*
 * Settings
 */

function anki_server_url($value = NULL) {
  if (is_null($value)) {
    return variable_get('anki_server_url', 'localhost:5000');
  }
  variable_set('anki_server_url', $value);
}

function anki_server_deck_path($value = NULL) {
  if (is_null($value)) {
    return variable_get('anki_server_deck_path', drupal_get_path('module', 'anki'). '/AnkiServer/decks');
  }

  variable_set('anki_server_deck_path', $value);
}


