<?php
// $Id$

/**
 * @file
 * For storing a users "Words I Am Learning" list
 */

/*
 * Implementation of hook_nodeapi().
 */
function lingwo_wial_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type != lingwo_dictionary_settings('entry_content_type'))
    return;

  // the wial list only deals with translations
  if (!lingwo_dictionary_entry_is_translation($node))
    return;

  switch ($op) {
    case 'view':
      // TODO: we should be able to optionally exclude this from the node view,
      // leaving it up to the theme to include this form somewhere.

      // Add information about whether this node is on this users WIAL or not.
      if (lingwo_wial_get($node->nid)) {
        $op = 'remove';
      }
      else {
        $op = 'add';
      }

      $node->content['wial_status'] = array(
        '#weight' => -10,
        '#value'  => drupal_get_form('lingwo_wial_form', $op, $node, $a3, $a4)
      );
      break;

    case 'delete':
      // TODO: Should we loop through all the users who have this on their WIAL list
      // and call the remove hook?  Sounds dangerous.  This could lock up the request
      // in trying to edit a million Anki decks...
      db_query('DELETE FROM {lingwo_wial_node} WHERE nid = %d', $node->nid);
      break;
  }
}

/**
 * Implementation of hook_views_api().
 */
function lingwo_wial_views_api() {
  return array(
    'api'  => 2,
    'path' => drupal_get_path('module', 'lingwo_wial'),
  );
}

/**
 * Implementation of hook_node_operations().
 */
function lingwo_wial_node_operations() {
  return array(
    array(
      'label' => t('Remove from my "Words I Am Learning" List'),
      'callback' => 'lingwo_wial_bulk_remove',
    )
  );
}

/**
 * Implementation of hook_theme().
 */
function lingwo_wial_theme() {
  return array(
    'lingwo_wial_form' => array(
      'arguments' => array('form' => NULL),
    )
  );
}

/*
 * Forms
 */

// WIAL add form
function lingwo_wial_form(&$form_state, $op, $node, $teaser=FALSE, $page=FALSE) {
  $form = array(
    // pack some data in here for the theme
    '#node'     => $node,
    '#teaser'   => $teaser,
    '#page'     => $page,
    '#headword' => $node->title
  );

  $form['wial_op'] = array(
    '#type' => 'hidden',
    '#value' => $op
  );
  $form['nid'] = array(
    '#type' => 'hidden',
    '#value' => $node->nid,
  );

  if ($op == 'add') {
    $msg = t('Add to my "Words I Am Learning" List');
  }
  else {
    $msg = t('Remove from my "Words I Am Learning" List');
  }
  $form['button'] = array(
    '#type' => 'submit',
    '#value' => $msg,
  );

  return $form;
}

function lingwo_wial_form_submit($form, &$form_state) {
  switch ($form_state['values']['wial_op']) {
    case 'add':
      if (lingwo_wial_add($form_state['values']['nid'])) {
        drupal_set_message(t('Added <em>@headword</em> to your "Words I Am Learning" list',
          array('@headword' => $form_state['values']['headword'])));
      }
      else {
        drupal_set_message(t('Unable to add entry to your "Words I Am Learning" list'), 'error');
      }
      break;

    case 'remove':
      if (lingwo_wial_remove($form_state['values']['nid'])) {
        drupal_set_message(t('Removed <em>@headword</em> from your "Words I Am Learning" list',
          array('@headword' => $form_state['values']['headword'])));
      }
      else {
        drupal_set_message(t('Unable to remove entry from your "Words I Am Learning" list'), 'error');
      }
      break;
  }
}

/*
 * API functions
 */

// API function for determining if a user has a particular item
function lingwo_wial_get($nid, $uid=NULL) {
  global $user;

  if (is_null($uid)) {
    $uid = $user->uid;
  }

  $res = db_query("SELECT * FROM {lingwo_wial_node} WHERE nid = '%s' AND uid = '%s'", $nid, $uid);
  return db_fetch_object($res);
}

// Add a node to a users WIAL list
function lingwo_wial_add($nid, $uid=NULL) {
  global $user;

  if (is_null($uid)) {
    $uid = $user->uid;
  }

  $obj = (object)array(
    'uid'   => $uid,
    'nid'   => $nid,
    'added' => time(),
  );

  if (drupal_write_record('lingwo_wial_node', $obj)) {
    module_invoke_all('lingwo_wial', 'add', $nid, $uid);
    return TRUE;
  }

  return FALSE;
}

// Remove a node from a users WIAL list
function lingwo_wial_remove($nid, $uid=NULL) {
  global $user;

  if (is_null($uid)) {
    $uid = $user->uid;
  }

  if (db_query("DELETE FROM {lingwo_wial_node} WHERE uid = %d AND nid = %d", $uid, $nid)) {
    module_invoke_all('lingwo_wial', 'remove', $nid, $uid);
    return TRUE;
  }

  return FALSE;
}

// Bulk remove nodes
function lingwo_wial_bulk_remove($nids, $uid=NULL) {
  global $user;

  if (is_null($uid)) {
    $uid = $user->uid;
  }

  foreach ($nids as $nid) {
    lingwo_wial_remove($nid, $uid);
  }
}


/*
 * Theme functions
 */

function templace_preprocess_theme_lingwo_wial_form(&$vars, $form) {
  $vars['teaser']  = $form['#teaser'];
  $vars['page']    = $form['#page'];
  $vars['node']    = $form['#node'];
  $vars['wial_op'] = $form['#wial_op'];
}

function theme_lingwo_wial_form($form) {
  return drupal_render($form);
}

