(function(){var m;(function(){function c(e){var a=k[e];if(a)return a;if(!i[e])throw new Error("Module "+e+" not found");for(var g=i[e],h=g.deps||(g.length?["require","exports","module"]:[]),j=k[e]={},b=0;b<h.length;b++){var d=h[b];switch(d){case "require":d=function(f){if(f.charAt(0)==="."){for(f=e.substring(0,e.lastIndexOf("/")+1)+f;l!==f;){var l=f;f=f.replace(/\/[^\/]*\/\.\.\//,"/")}f=f.replace(/\/\.\//g,"/")}return c(f)};break;case "exports":d=j;break;case "module":a=d={exports:j};break;default:d=
c(d)}h[b]=d}j=g.apply(this,h);if(a&&a.exports!=k[e])j=a.exports;if(j)return k[e]=j;return k[e]}var i={},k={};m=function(e,a){for(var g=[],h=0;h<e.length;h++)g.push(c(e[h]));a.apply(c,g)};m.def=function(e,a,g){if(typeof a=="function")i[e]=a;else(i[e]=g).deps=a}})();m.def("lingwo_dictionary/annotation/Reader2",["jquery"],function(c){function i(b,d,f){old_fn=b[d];b[d]=function(){old_fn.apply(this,arguments);f()}}function k(b){var d={},f;for(f in b)d[f]=b[f];return d}function e(b,d){return function(){return b.apply(d,
arguments)}}var a,g,h=/MSIE 6/i.test(navigator.userAgent),j={layout:"docked"};g={popup:{setup:function(){a.bubbleNode.addClass("popup")},shutdown:function(){a.bubbleNode.removeClass("popup")},show:function(){var b=a.selectedNode,d=a.bubbleNode,f=b.offset(),l=f.left+b.width()/2-150;b=f.top+b.height()+40;f=c(document).width();if(l+300>f)l=f-300;if(l<0)l=0;d.show().css({left:l,top:b,height:""});if(h||d.height()>200)d.css({height:200})},hide:function(){a.bubbleNode.hide()}},docked:{_dock:null,_footer:null,
_footerId:null,_footerMargin:null,_positionBubble:function(){a.bubbleNode.show();var b=a.bubbleNode,d=this._dock.offset(),f=this._footer.offset().top;b.outerWidth();b.innerWidth();var l=b.outerHeight()-b.innerHeight(),n=Math.max(d.top-c(window).scrollTop()+1,0);f=Math.min(f-c(window).scrollTop()-n-this._footerMargin+1,c(window).height()-n)-l;b.css({left:d.left-c(window).scrollLeft(),top:n,height:f})},_drupalHack:false,setup:function(){a.bubbleNode.addClass("docked");this._dock=c("#lingwo-korpus-dock");
this._footerId=this._dock.attr("data-footer-id");this._footerMargin=this._dock.attr("data-footer-margin");this._footer=c("#"+this._footerId);var b=e(this._positionBubble,this);c(window).bind("scroll.lingwoReaderDocked",b);c(window).bind("resize.lingwoReaderDocked",b);if(!this._drupalHack){typeof window.Drupal!="undefined"&&Drupal.adminToolbar&&i(Drupal.adminToolbar,"setState",function(){if(a.layout===g.docked){a.bubbleNode.hide();setTimeout(b,500)}});this._drupalHack=true}a.setBubbleContent("<em>Click a work in the text to look it up in the dictionary.</em>");
setTimeout(b,0)},shutdown:function(){a.bubbleNode.removeClass("docked");this._dock=this._footerId=this._footerMargin=this._footer=null;c(window).unbind(".lingwoReaderDocked")},show:function(){},hide:function(){}}};return a={defaultLayouts:g,onLoad:function(){},config:null,bubbleNode:null,contentNode:null,selectedNode:null,shown:false,isSetup:false,layout:null,setup:function(b){if(typeof b=="undefined")b=k(j);this.config=b;if(this.config.layout=="docked"&&h)this.config.layout="popup";if(this.isSetup){this.layout.shutdown();
this.layout=null;this.isSetup=false}if(!this.bubbleNode)this.bubbleNode=c("<div></div>").attr("id","lingwo-korpus-entry-view-wrapper").appendTo(c("body")).hide();if(!this.contentNode)this.contentNode=c("<div></div>").attr("id","lingwo-korpus-entry-view").appendTo(this.bubbleNode);b=typeof this.config.layout=="string"?g[this.config.layout]:this.config.layout;b.setup();this.config.skipHoverEvents||this.setupHoverEvents();this.layout=b;this.isSetup=false},setupHoverEvents:function(){var b=this;c(".anno, .anno-anchor").unbind("mouseenter mouseleave").bind("mouseenter",
function(d){d=c(d.target);d.addClass("hover");if(d=b._getAnnoText(d))d.addClass("hover")}).bind("mouseleave",function(d){d=c(d.target);d.removeClass("hover");if(d=b._getAnnoText(d))d.removeClass("hover")})},_getAnnoText:function(b){if(b.hasClass("anno-anchor"))if(b=b.attr("data-anno"))return c("#"+b);return null},setSelection:function(b){var d;if(this.selectedNode){this.selectedNode.removeClass("selected");if(d=this._getAnnoText(this.selectedNode))d.removeClass("selected");this.selectedNode=null}if(b){b=
c(b);b.addClass("selected");this.selectedNode=b;if(d=this._getAnnoText(this.selectedNode))d.addClass("selected")}},clearSelection:function(){this.setSelection(null)},showBubble:function(){if(!this.shown){this.layout.show();this.shown=true}},hideBubble:function(){if(this.shown){this.layout.hide();this.shown=false}},setBubbleContent:function(b){this.contentNode.html(b)},setBubbleLoading:function(){this.setBubbleContent("Loading...")},isWordNode:function(b){return c(b).hasClass("anno")||c(b).hasClass("anno-anchor")},
handleClick:function(b){if(this.isWordNode(b)){this.setSelection(b);this.onLoad(this.selectedNode);this.showBubble();return false}this.clearSelection();this.hideBubble()}}});m.def("lingwo_dictionary/annotation/Embed",["jquery","lingwo_dictionary/annotation/Reader2"],function(c,i){function k(a,g,h){var j;for(j in g)if(!h||typeof a[j]=="undefined")a[j]=g[j]}var e={};if(typeof window.BiblioBird!="undefined")e=window.BiblioBird;k(e,{url:"http://www.bibliobird.com",lang:"en"},true);k(e,{initialized:false,
contentAreas:[],embedWindow:null,embedIframe:null,embedWindowShown:false,username:null,start:function(){var a=this;c(".bibliobird-content").each(function(){a.contentAreas.push(new ContentArea(this))})},initialize:function(a){function g(){var b=(c(window).width()-400)/2,d=(c(window).height()-200)/2;h.css({top:d,left:b})}if(!this.initialized){var h=c('<div class="clear-block"><div class="bibliobird-embed-titlebar"><span class="bibliobird-embed-title">BiblioBird</span> <a href="#" class="bibliobird-embed-close">close</a></div></div>'),
j=c('<iframe height="100%" width="100%" border="0" id="bibliobirdEmbedIframe" name="bibliobirdEmbedIframe"></iframe>').appendTo(h);h.css({width:400,height:200,position:"fixed",border:"1px solid black",background:"white",display:"none"}).appendTo(c("body"));c(".bibliobird-embed-close",h).click(function(){e.hideEmbedWindow();return false});c(window).resize(g);setTimeout(g,0);i.setup({layout:"popup",skipHoverEvents:true});c("body").click(function(b){e.hideEmbedWindow();return i.handleClick(b.target)});
k(this,{embedWindow:h,embedIframe:j,username:a,initialized:true})}},receiveMessage:function(a){if(a.indexOf("#login-successful")==0){a=a.split(":");if(a[1])this.username=a[1];this.hideEmbedWindow()}},openEmbedWindow:function(a){if(this.embedWindow!==null&&!this.embedWindowShown){this.embedIframe.attr("src",a);this.embedWindow.show();this.embedWindowShown=true}},hideEmbedWindow:function(){if(this.embedWindow!==null&&this.embedWindowShown){this.embedWindow.hide();this.embedWindowShown=false;this.refreshAll()}},
logout:function(){var a=this;c.ajax({url:e.url+"/lingwo_korpus/rlogout",dataType:"jsonp",success:function(){a.username=null;a.refreshAll()}})},refreshAll:function(){c.each(this.contentAreas,function(){this.refresh()})}});i.onLoad=function(a){a=(a.attr("data-entry")||"").split("#");var g=a[0],h=a[1];i.setBubbleLoading();c.ajax({url:e.url+"/lingwo_korpus/lookup_entry",dataType:"jsonp",data:{hash:g,lang:e.lang},success:function(j){i.setBubbleContent(j.content);c(".node",i.contentNode).removeClass("clear-block").removeAttr("id");
c("ul.links.inline",i.contentNode).remove();h&&c(".lingwo-sense-id-"+h,i.contentNode).addClass("selected");c("a",i.contentNode).each(function(b,d){b=d.href;var f;if(b){f=window.location.protocol+"//"+window.location.host;d.href=b.replace(f,e.url);d.target="_blank"}})}})};ContentArea=function(a){this.node=a;this.url=c(a).attr("data-url")||window.location.href;this.teaser=c(a).attr("data-teaser")=="true";this.links=c('<div class="bibliobird-links"></div>').insertBefore(a);this.data={};this.lookupContent()};
k(ContentArea.prototype,{lookupContent:function(){var a=this;c.ajax({url:e.url+"/lingwo_korpus/lookup_content",dataType:"jsonp",data:{url:this.url},success:function(g){e.initialize(g.username);a.data=g;a.rebuildLinks();if(g.content){a.node.innerHTML=g.content;i.setupHoverEvents()}}})},rebuildLinks:function(){var a=this.links,g=this.data;a.html("");if(e.username){a.append("Logged into BiblioBird as "+e.username+" ");a.append(c("<a></a>").html("Logout").attr("href",e.url+"/logout").click(function(){e.logout();
return false}))}else{a.append("Not logged into BiblioBird ");a.append(c("<a></a>").html("Login").attr("href",e.url+"/lingwo_korpus/rlogin"+(e.localRelayUrl?"?relay="+e.localRelayUrl:"")).click(function(h){e.openEmbedWindow(h.target.href);return false}));a.append(" ");a.append(c("<a></a>").html("Join BiblioBird").attr({href:e.url+"/user/register",target:"_blank"}))}a.append(" ");g.not_found&&a.append(c("<a></a>").html("Add to Bibliobird").attr({href:e.url+"/node/add/content?remote_url="+escape(this.url),
target:"_blank"}))},refresh:function(){this.rebuildLinks()}});return window.BiblioBird=e});m.def("jquery",[],function(){return window.jQuery});m.def("jQuery",[],function(){return window.jQuery});m(["lingwo_dictionary/annotation/Embed"],function(c){c.start()})})();
