/*
 RequireJS Copyright (c) 2004-2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/requirejs for details

 jQuery JavaScript Library v1.4.2
 http://jquery.com/

 Copyright 2010, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2010, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Sat Feb 13 22:33:48 2010 -0500
*/
var require;
(function(){function v(o){return ga.call(o)==="[object Function]"}function C(o){return function(r){o.exports=r}}var M={},y,G,A=[],L,O,U,S,K,Q={},R,da=/^(complete|loaded)$/,W,X=!!(typeof window!=="undefined"&&navigator&&document),c=!X&&typeof importScripts!=="undefined",ga=Object.prototype.toString,oa,k,fa;if(typeof require!=="undefined")if(v(require))return;else Q=require;k=require=function(o,r,w,x){var E;if(typeof o==="string"&&!v(r))return require.get(o,r);if(!require.isArray(o)){E=o;if(require.isArray(r)){o=
r;r=w;w=x}else o=[]}return W(null,o,r,E,w)};k.onError=function(o){throw o;};k.def=function(o,r,w,x){if(!k.isArray(r)){x=w;w=r;r=[]}return W(o,r,w,null,x)};W=function(o,r,w,x,E){var z=y.contexts[E],T,Y;E=E?E:x&&x.context?x.context:y.ctxName;z=y.contexts[E];if(o)if(z&&(z.defined[o]||z.waiting[o]))return k;if(!z){z={contextName:E,config:{waitSeconds:7,baseUrl:y.baseUrl||"./",paths:{}},waiting:[],specified:{require:true,exports:true,module:true},loaded:{require:true},urlFetched:{},defined:{},modifiers:{}};
z.defined.require=k;z=y.contexts[E]=z}if(x){if(x.baseUrl)if(x.baseUrl.charAt(x.baseUrl.length-1)!=="/")x.baseUrl+="/";Y=z.config.paths;k.mixin(z.config,x,true);if(x.paths){for(T in x.paths)T in M||(Y[T]=x.paths[T]);z.config.paths=Y}if(x.priority){k(x.priority);z.config.priorityWait=x.priority}if(x.deps||x.callback)k(x.deps||[],x.callback);x.ready&&k.ready(x.ready);if(!r)return k}if(r){x=r;r=[];for(T=0;T<x.length;T++)r[T]=k.splitPrefix(x[T],o)}x=z.waiting.push({name:o,deps:r,callback:w});if(o){z.waiting[o]=
x-1;z.specified[o]=true}if(o&&w&&!k.isFunction(w))z.defined[o]=w;if(y.paused||z.config.priorityWait)(y.paused||(y.paused=[])).push([void 0,o,r,z]);else{k.checkDeps(void 0,o,r,z);k.checkLoaded(E)}if(o)z.loaded[o]=true;return k};k.mixin=function(o,r,w){for(var x in r)if(!(x in M)&&(!(x in o)||w))o[x]=r[x];return k};k.version="0.13.0";y=k.s={ctxName:"_",contexts:{},skipAsync:{},isBrowser:X,isPageLoaded:!X,readyCalls:[],doc:X?document:null};k.isBrowser=y.isBrowser;if(X){y.head=document.getElementsByTagName("head")[0];
if(fa=document.getElementsByTagName("base")[0])y.head=fa.parentNode}k.pause=function(){if(!y.paused)y.paused=[]};k.resume=function(){var o,r,w;if(!y.contexts[y.ctxName].config.priorityWait){if(y.paused){w=y.paused;delete y.paused;for(o=0;r=w[o];o++)k.checkDeps.apply(k,r)}k.checkLoaded(y.ctxName)}};k.checkDeps=function(o,r,w,x){if(!o)for(o=0;r=w[o];o++)if(!x.specified[r.fullName]){x.specified[r.fullName]=true;x.startTime=(new Date).getTime();r.prefix||k.load(r.name,x.contextName)}};k.isArray=function(o){return ga.call(o)===
"[object Array]"};k.isFunction=v;k.get=function(o,r){if(o==="exports"||o==="module")return k.onError(new Error("require of "+o+" is not allowed."));r=r||y.ctxName;var w=y.contexts[r].defined[o];if(w===undefined)return k.onError(new Error("require: module name '"+o+"' has not been loaded yet for context: "+r));return w};k.load=function(o,r){var w=y.contexts[r],x=w.urlFetched;w=w.loaded;y.isDone=false;w[o]||(w[o]=false);w=k.nameToUrl(o,null,r);if(!x[w]){k.attach(w,r,o);x[w]=true}};k.jsExtRegExp=/\.js$/;
k.normalizeName=function(o,r){if(o.charAt(0)==="."){r=r.split("/");r=r.slice(0,r.length-1);o=r.concat(o.split("/"));for(G=0;r=o[G];G++)if(r==="."){o.splice(G,1);G-=1}else if(r===".."){o.splice(G-1,2);G-=2}o=o.join("/")}return o};k.splitPrefix=function(o,r){var w=o.indexOf("!"),x=null;if(w!==-1){x=o.substring(0,w);o=o.substring(w+1,o.length)}if(r)o=k.normalizeName(o,r);return{prefix:x,name:o,fullName:x?x+"!"+o:o}};k.nameToUrl=function(o,r,w){var x,E,z;w=y.contexts[w].config;if(o.indexOf(":")!==-1||
o.charAt(0)==="/"||k.jsExtRegExp.test(o))return o+(r?r:"");else if(o.charAt(0)===".")return k.onError(new Error("require.nameToUrl does not handle relative module names (ones that start with '.' or '..')"));else{x=w.paths;o=o.split("/");for(E=o.length;E>0;E--){z=o.slice(0,E).join("/");if(x[z]){o.splice(0,E,x[z]);break}}r=o.join("/")+(r||".js");return(r.charAt(0)==="/"||r.match(/^\w+:/)?"":w.baseUrl)+r}};k.checkLoaded=function(o){var r=y.contexts[o||y.ctxName],w=r.config.waitSeconds*1E3,x=w&&r.startTime+
w<(new Date).getTime(),E,z;w="";var T=false,Y=false,V,$,ha={};if(!r.isCheckLoaded){if(r.config.priorityWait){z=true;for(E=0;$=r.config.priorityWait[E];E++)if(!r.loaded[$]){z=false;break}if(z){delete r.config.priorityWait;k.resume()}else return}r.isCheckLoaded=true;z=r.waiting;E=r.loaded;for(V in E)if(!(V in M)){T=true;if(!E[V])if(x)w+=V+" ";else{Y=true;break}}if(!T&&!z.length)r.isCheckLoaded=false;else{if(x&&w){r=new Error("require.js load timeout for modules: "+w);r.requireType="timeout";r.requireModules=
w;return k.onError(r)}if(Y){r.isCheckLoaded=false;if(X||c)setTimeout(function(){k.checkLoaded(o)},50)}else{r.waiting=[];r.loaded={};for(E=0;w=z[E];E++)k.exec(w,ha,z,r);r.isCheckLoaded=false;if(r.waiting.length)k.checkLoaded(o);else if(!A.length){y.ctxName="_";y.isDone=true;k.callReady&&k.callReady()}}}}};k.exec=function(o,r,w,x){if(o){var E=o.name,z=o.callback;z=o.deps;var T,Y,V=x.defined,$,ha=[],Z,ea,ia=false;if(E){if(r[E]||E in V)return V[E];r[E]=true}if(z)for(T=0;Y=z[T];T++){Z=Y.name;if(Z==="exports"){Z=
V[E]={};ia=true}else if(Z==="module"){ea=Z={id:E,uri:E?k.nameToUrl(E,null,x.contextName):undefined};ea.setExports=C(ea)}else Z=Z in V?V[Z]:r[Z]?undefined:k.exec(w[w[Z]],r,w,x);ha.push(Z)}if((z=o.callback)&&k.isFunction(z)){$=k.execCb(E,z,ha);if(E)if(ia&&(!ea||!("exports"in ea)))$=V[E];else if(ea&&"exports"in ea)$=V[E]=Z.exports;else{if(E in V)return k.onError(new Error(E+" has already been defined"));V[E]=$}}return $}};k.execCb=function(o,r,w){return r.apply(null,w)};k.onScriptLoad=function(o){var r=
o.currentTarget||o.srcElement,w;if(o.type==="load"||da.test(r.readyState)){o=r.getAttribute("data-requirecontext");w=r.getAttribute("data-requiremodule");y.contexts[o].loaded[w]=true;k.checkLoaded(o);r.removeEventListener?r.removeEventListener("load",k.onScriptLoad,false):r.detachEvent("onreadystatechange",k.onScriptLoad)}};k.attach=function(o,r,w,x,E){var z;if(X){x=x||k.onScriptLoad;z=document.createElement("script");z.type=E||"text/javascript";z.charset="utf-8";if(!y.skipAsync[o])z.async=true;z.setAttribute("data-requirecontext",
r);z.setAttribute("data-requiremodule",w);z.addEventListener?z.addEventListener("load",x,false):z.attachEvent("onreadystatechange",x);z.src=o;return fa?y.head.insertBefore(z,fa):y.head.appendChild(z)}else if(c){r=y.contexts[r].loaded;r[w]=false;importScripts(o);r[w]=true}return null};y.baseUrl=Q.baseUrl;if(X&&(!y.baseUrl||!y.head)){L=document.getElementsByTagName("script");U=Q.baseUrlMatch?Q.baseUrlMatch:/(requireplugins-|require-)?jquery[\-\d\.]*(min)?\.js(\W|$)/i;for(G=L.length-1;G>-1&&(O=L[G]);G--){if(!y.head)y.head=
O.parentNode;if(!Q.deps)if(S=O.getAttribute("data-main"))Q.deps=[S];if((S=O.src)&&!y.baseUrl)if(K=S.match(U)){y.baseUrl=S.substring(0,K.index);break}}}k.pageLoaded=function(){if(!y.isPageLoaded){y.isPageLoaded=true;oa&&clearInterval(oa);if(R)document.readyState="complete";k.callReady()}};k.callReady=function(){var o=y.readyCalls,r,w;if(y.isPageLoaded&&y.isDone&&o.length){y.readyCalls=[];for(r=0;w=o[r];r++)w()}};k.ready=function(o){y.isPageLoaded&&y.isDone?o():y.readyCalls.push(o);return k};if(X){if(document.addEventListener){document.addEventListener("DOMContentLoaded",
k.pageLoaded,false);window.addEventListener("load",k.pageLoaded,false);if(!document.readyState){R=true;document.readyState="loading"}}else if(window.attachEvent){window.attachEvent("onload",k.pageLoaded);if(self===self.top)oa=setInterval(function(){try{if(document.body){document.documentElement.doScroll("left");k.pageLoaded()}}catch(o){}},30)}document.readyState==="complete"&&k.pageLoaded()}k(Q)})();
require.def("lingwo_dictionary/annotation/Reader",["jquery"],function(v){function C(K,Q,R){old_fn=K[Q];K[Q]=function(){old_fn.apply(this,arguments);R()}}var M,y,G,A,L=false,O,U,S;return{callback:function(){},popup:true,activated:true,shown:false,setup:function(K,Q,R){function da(){if(!R){M.show();var W=G.offset(),X=A.offset().top;M.outerWidth();M.innerWidth();var c=M.outerHeight()-M.innerHeight(),ga=Math.max(W.top-v(window).scrollTop()+1,0);X=Math.min(X-v(window).scrollTop()-ga-U+1,v(window).height()-
ga)-c;M.css({left:W.left-v(window).scrollLeft(),top:ga,height:X})}}this.callback=Q;if(typeof R!=="undefined")this.popup=R;else R=this.popup;M||(M=v("<div></div>").attr("id","lingwo-korpus-entry-view-wrapper").addClass(R?"popup":"docked").appendTo(v("body")).hide());y||(y=v("<div></div>").attr("id","lingwo-korpus-entry-view").appendTo(M));if(!G){G=v("#lingwo-korpus-dock",K);O=G.attr("data-footer-id");U=G.attr("data-footer-margin")}A||(A=v("#"+O,K));if(!R){y.html("<em>Click a word in the text to look it up in the dictionary.</em>");
setTimeout(da,0)}if(!L){v(window).scroll(da);v(window).resize(da);typeof window.Drupal!=="undefined"&&Drupal.adminToolbar&&C(Drupal.adminToolbar,"setState",function(){if(!R){M.hide();setTimeout(da,500)}});L=true}},activate:function(K){K||this.clearSelection();this.activated=K},clearSelection:function(){if(S){S.removeClass("selected");S=null}},hideDialog:function(){this.popup&&M.hide();this.shown=false;this.clearSelection()},showDialog:function(K){K=v(K);var Q;this.clearSelection();Q=K.offset();if(this.popup){var R=
Q.left+K.width()/2-150;Q=Q.top+K.height()+40;var da=v(document).width();if(R+300>da)R=da-300;if(R<0)R=0;M.show().css({left:R,top:Q,height:""})}S=K;K.addClass("selected");this.shown=true;this.callback(K,y,function(W){W!==null&&typeof W!=="undefined"&&y.html(W);this.popup&&M.height()>200&&M.css({height:200})})},onClick:function(K){if(!this.activated)return true;K=v(K.target);this.clearSelection();if(K.hasClass("anno")){this.showDialog(K);return false}this.hideDialog();return true}}});
require.def("lingwo_dictionary/annotation/Embed",["jquery","lingwo_dictionary/annotation/Reader"],function(v,C){function M(A,L,O){var U;for(U in L)if(!O||typeof A[U]=="undefined")A[U]=L[U]}function y(A,L,O){var U=A.attr("data-sense");O("Loading ...");v.ajax({url:G.url+"/lingwo_korpus/lookup_entry",dataType:"jsonp",data:{url:A.attr("href")},success:function(S){O(S.content);v(".node",L).removeClass("clear-block").removeAttr("id");v("ul.links.inline",L).remove();U&&v(".lingwo-sense-id-"+U,L).addClass("selected")}})}
var G={};if(typeof window.BiblioBird!="undefined")G=window.BiblioBird;M(G,{url:"http://www.bibliobird.com",lang:"en"},true);M(G,{initialized:false,contentAreas:[],embedWindow:null,embedIframe:null,embedWindowShown:false,username:null,start:function(){var A=this;v(".bibliobird-content").each(function(){A.contentAreas.push(new ContentArea(this))})},initialize:function(A){function L(){var S=(v(window).width()-400)/2,K=(v(window).height()-200)/2;O.css({top:K,left:S})}if(!this.initialized){var O=v('<div class="clear-block"><div class="bibliobird-embed-titlebar"><span class="bibliobird-embed-title">BiblioBird</span> <a href="#" class="bibliobird-embed-close">close</a></div></div>'),
U=v('<iframe height="100%" width="100%" border="0" id="bibliobirdEmbedIframe" name="bibliobirdEmbedIframe"></iframe>').appendTo(O);O.css({width:400,height:200,position:"fixed",border:"1px solid black",background:"white"}).hide().appendTo(v("body"));v(".bibliobird-embed-close",O).click(function(){G.hideEmbedWindow();return false});v(window).resize(L);setTimeout(L,0);C.setup(v("body"),y,true);v("body").click(function(S){G.hideEmbedWindow();return C.onClick(S)});M(this,{embedWindow:O,embedIframe:U,username:A,
initialized:true})}},receiveMessage:function(A){if(A.indexOf("#login-successful")==0){A=A.split(":");if(A[1])this.username=A[1];this.hideEmbedWindow()}},openEmbedWindow:function(A){if(this.embedWindow!==null&&!this.embedWindowShown){this.embedIframe.attr("src",A);this.embedWindow.show();this.embedWindowShown=true}},hideEmbedWindow:function(){if(this.embedWindow!==null&&this.embedWindowShown){this.embedWindow.hide();this.embedWindowShown=false;this.refreshAll()}},logout:function(){var A=this;v.ajax({url:G.url+
"/lingwo_korpus/rlogout",dataType:"jsonp",success:function(){A.username=null;A.refreshAll()}})},refreshAll:function(){v.each(this.contentAreas,function(){this.refresh()})}});ContentArea=function(A){this.node=A;this.from_lang=v(A).attr("data-from-lang");this.to_lang=v(A).attr("data-to-lang");this.url=v(A).attr("data-url")||window.location.href;this.teaser=v(A).attr("data-teaser")=="true";this.links=v('<div class="bibliobird-links"></div>').insertBefore(A);this.data={};this.lookupContent()};M(ContentArea.prototype,
{lookupContent:function(){var A=this;v.ajax({url:G.url+"/lingwo_korpus/lookup_content",dataType:"jsonp",data:{url:this.url,to_lang:this.to_lang},success:function(L){G.initialize(L.username);A.data=L;A.rebuildLinks();if(L.content)A.node.innerHTML=L.content}})},rebuildLinks:function(){var A=this.links,L=this.data;A.html("");if(G.username){A.append("Logged into BiblioBird as "+G.username+" ");A.append(v("<a></a>").html("Logout").attr("href",G.url+"/logout").click(function(){G.logout();return false}))}else{A.append("Not logged into BiblioBird ");
A.append(v("<a></a>").html("Login").attr("href",G.url+"/lingwo_korpus/rlogin"+(G.localRelayUrl?"?relay="+G.localRelayUrl:"")).click(function(O){G.openEmbedWindow(O.target.href);return false}));A.append(" ");A.append(v("<a></a>").html("Join BiblioBird").attr({href:G.url+"/user/register",target:"_blank"}))}A.append(" ");L.not_found&&A.append(v("<a></a>").html("Add to Bibliobird").attr({href:G.url+"/node/add/content?remote_url="+escape(url),target:"_blank"}))},refresh:function(){this.rebuildLinks()}});
G.start();window.BiblioBird=G});
(function(v,C){function M(){if(!c.isReady){try{k.documentElement.doScroll("left")}catch(a){setTimeout(M,1);return}c.ready()}}function y(a,b){b.src?c.ajax({url:b.src,async:false,dataType:"script"}):c.globalEval(b.text||b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}function G(a,b,d,f,e,i){var j=a.length;if(typeof b==="object"){for(var q in b)G(a,q,b[q],f,e,d);return a}if(d!==C){f=!i&&f&&c.isFunction(d);for(q=0;q<j;q++)e(a[q],b,f?d.call(a[q],q,e(a[q],b)):d,i);return a}return j?
e(a[0],b):C}function A(){return(new Date).getTime()}function L(){return false}function O(){return true}function U(a,b,d){d[0].type=a;return c.event.handle.apply(b,d)}function S(a){var b,d=[],f=[],e=arguments,i,j,q,l,p,u;j=c.data(this,"events");if(!(a.liveFired===this||!j||!j.live||a.button&&a.type==="click")){a.liveFired=this;var D=j.live.slice(0);for(l=0;l<D.length;l++){j=D[l];j.origType.replace(pa,"")===a.type?f.push(j.selector):D.splice(l--,1)}i=c(a.target).closest(f,a.currentTarget);p=0;for(u=
i.length;p<u;p++)for(l=0;l<D.length;l++){j=D[l];if(i[p].selector===j.selector){q=i[p].elem;f=null;if(j.preType==="mouseenter"||j.preType==="mouseleave")f=c(a.relatedTarget).closest(j.selector)[0];if(!f||f!==q)d.push({elem:q,handleObj:j})}}p=0;for(u=d.length;p<u;p++){i=d[p];a.currentTarget=i.elem;a.data=i.handleObj.data;a.handleObj=i.handleObj;if(i.handleObj.origHandler.apply(i.elem,e)===false){b=false;break}}return b}}function K(a,b){return"live."+(a&&a!=="*"?a+".":"")+b.replace(/\./g,"`").replace(/ /g,
"&")}function Q(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function R(a,b){var d=0;b.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var f=c.data(a[d++]),e=c.data(this,f);if(f=f&&f.events){delete e.handle;e.events={};for(var i in f)for(var j in f[i])c.event.add(this,i,f[i][j],f[i][j].data)}}})}function da(a,b,d){var f,e,i;b=b&&b[0]?b[0].ownerDocument||b[0]:k;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===k&&!Ea.test(a[0])&&(c.support.checkClone||!Fa.test(a[0]))){e=
true;if(i=c.fragments[a[0]])if(i!==1)f=i}if(!f){f=b.createDocumentFragment();c.clean(a,b,f,d)}if(e)c.fragments[a[0]]=i?f:1;return{fragment:f,cacheable:e}}function W(a,b){var d={};c.each(Ga.concat.apply([],Ga.slice(0,b)),function(){d[this]=a});return d}function X(a){return"scrollTo"in a&&a.document?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var c=function(a,b){return new c.fn.init(a,b)},ga=v.jQuery,oa=v.$,k=v.document,fa,o=/^[^<]*(<[\w\W]+>)[^>]*$|^#([\w-]+)$/,r=/^.[^:#\[\.,]*$/,w=/\S/,x=
/^(\s|\u00A0)+|(\s|\u00A0)+$/g,E=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,z=navigator.userAgent,T=false,Y=[],V=!!(typeof require!=="undefined"&&require.def),$,ha=Object.prototype.toString,Z=Object.prototype.hasOwnProperty,ea=Array.prototype.push,ia=Array.prototype.slice,Ha=Array.prototype.indexOf;c.fn=c.prototype={init:function(a,b){var d,f;if(!a)return this;if(a.nodeType){this.context=this[0]=a;this.length=1;return this}if(a==="body"&&!b){this.context=k;this[0]=k.body;this.selector="body";this.length=1;return this}if(typeof a===
"string")if((d=o.exec(a))&&(d[1]||!b))if(d[1]){f=b?b.ownerDocument||b:k;if(a=E.exec(a))if(c.isPlainObject(b)){a=[k.createElement(a[1])];c.fn.attr.call(a,b,true)}else a=[f.createElement(a[1])];else{a=da([d[1]],[f]);a=(a.cacheable?a.fragment.cloneNode(true):a.fragment).childNodes}return c.merge(this,a)}else{if(b=k.getElementById(d[2])){if(b.id!==d[2])return fa.find(a);this.length=1;this[0]=b}this.context=k;this.selector=a;return this}else if(!b&&/^\w+$/.test(a)){this.selector=a;this.context=k;a=k.getElementsByTagName(a);
return c.merge(this,a)}else return!b||b.jquery?(b||fa).find(a):c(b).find(a);else if(c.isFunction(a))return fa.ready(a);if(a.selector!==C){this.selector=a.selector;this.context=a.context}return c.makeArray(a,this)},selector:"",jquery:"1.4.2",length:0,size:function(){return this.length},toArray:function(){return ia.call(this,0)},get:function(a){return a==null?this.toArray():a<0?this.slice(a)[0]:this[a]},pushStack:function(a,b,d){var f=c();c.isArray(a)?ea.apply(f,a):c.merge(f,a);f.prevObject=this;f.context=
this.context;if(b==="find")f.selector=this.selector+(this.selector?" ":"")+d;else if(b)f.selector=this.selector+"."+b+"("+d+")";return f},each:function(a,b){return c.each(this,a,b)},ready:function(a){c.bindReady();if(c.isReady&&(!V||require.s.isDone))a.call(k,c);else{Y||(Y=[]);Y.push(a)}return this},eq:function(a){return a===-1?this.slice(a):this.slice(a,+a+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(ia.apply(this,arguments),"slice",
ia.call(arguments).join(","))},map:function(a){return this.pushStack(c.map(this,function(b,d){return a.call(b,d,b)}))},end:function(){return this.prevObject||c(null)},push:ea,sort:[].sort,splice:[].splice};c.fn.init.prototype=c.fn;c.extend=c.fn.extend=function(){var a=arguments[0]||{},b=1,d=arguments.length,f=false,e,i,j,q;if(typeof a==="boolean"){f=a;a=arguments[1]||{};b=2}if(typeof a!=="object"&&!c.isFunction(a))a={};if(d===b){a=this;--b}for(;b<d;b++)if((e=arguments[b])!=null)for(i in e){j=a[i];
q=e[i];if(a!==q)if(f&&q&&(c.isPlainObject(q)||c.isArray(q))){j=j&&(c.isPlainObject(j)||c.isArray(j))?j:c.isArray(q)?[]:{};a[i]=c.extend(f,j,q)}else if(q!==C)a[i]=q}return a};c.extend({noConflict:function(a){v.$=oa;if(a)v.jQuery=ga;return c},isReady:false,ready:function(){if(!c.isReady){if(!k.body)return setTimeout(c.ready,13);c.isReady=true;c.callReady()}},callReady:function(){if(c.isReady&&(!V||require.s.isDone)){if(Y){for(var a,b=0;a=Y[b++];)a.call(k,c);Y=null}c.fn.triggerHandler&&c(k).triggerHandler("ready")}},
bindReady:function(){if(!T){T=true;if(k.readyState==="complete")return c.ready();if(k.addEventListener){k.addEventListener("DOMContentLoaded",$,false);v.addEventListener("load",c.ready,false)}else if(k.attachEvent){k.attachEvent("onreadystatechange",$);v.attachEvent("onload",c.ready);var a=false;try{a=v.frameElement==null}catch(b){}k.documentElement.doScroll&&a&&M()}}},isFunction:function(a){return ha.call(a)==="[object Function]"},isArray:function(a){return ha.call(a)==="[object Array]"},isPlainObject:function(a){if(!a||
ha.call(a)!=="[object Object]"||a.nodeType||a.setInterval)return false;if(a.constructor&&!Z.call(a,"constructor")&&!Z.call(a.constructor.prototype,"isPrototypeOf"))return false;var b;for(b in a);return b===C||Z.call(a,b)},isEmptyObject:function(a){for(var b in a)return false;return true},error:function(a){throw a;},parseJSON:function(a){if(typeof a!=="string"||!a)return null;a=c.trim(a);if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return v.JSON&&v.JSON.parse?v.JSON.parse(a):(new Function("return "+a))();else c.error("Invalid JSON: "+a)},noop:function(){},globalEval:function(a){if(a&&w.test(a)){var b=k.getElementsByTagName("head")[0]||k.documentElement,d=k.createElement("script");d.type="text/javascript";if(c.support.scriptEval)d.appendChild(k.createTextNode(a));else d.text=a;b.insertBefore(d,b.firstChild);b.removeChild(d)}},nodeName:function(a,b){return a.nodeName&&a.nodeName.toUpperCase()===
b.toUpperCase()},each:function(a,b,d){var f,e=0,i=a.length,j=i===C||c.isFunction(a);if(d)if(j)for(f in a){if(b.apply(a[f],d)===false)break}else for(;e<i;){if(b.apply(a[e++],d)===false)break}else if(j)for(f in a){if(b.call(a[f],f,a[f])===false)break}else for(d=a[0];e<i&&b.call(d,e,d)!==false;d=a[++e]);return a},trim:function(a){return(a||"").replace(x,"")},makeArray:function(a,b){b=b||[];if(a!=null)a.length==null||typeof a==="string"||c.isFunction(a)||typeof a!=="function"&&a.setInterval?ea.call(b,
a):c.merge(b,a);return b},inArray:function(a,b){if(b.indexOf)return b.indexOf(a);for(var d=0,f=b.length;d<f;d++)if(b[d]===a)return d;return-1},merge:function(a,b){var d=a.length,f=0;if(typeof b.length==="number")for(var e=b.length;f<e;f++)a[d++]=b[f];else for(;b[f]!==C;)a[d++]=b[f++];a.length=d;return a},grep:function(a,b,d){for(var f=[],e=0,i=a.length;e<i;e++)!d!==!b(a[e],e)&&f.push(a[e]);return f},map:function(a,b,d){for(var f=[],e,i=0,j=a.length;i<j;i++){e=b(a[i],i,d);if(e!=null)f[f.length]=e}return f.concat.apply([],
f)},guid:1,proxy:function(a,b,d){if(arguments.length===2)if(typeof b==="string"){d=a;a=d[b];b=C}else if(b&&!c.isFunction(b)){d=b;b=C}if(!b&&a)b=function(){return a.apply(d||this,arguments)};if(a)b.guid=a.guid=a.guid||b.guid||c.guid++;return b},uaMatch:function(a){a=a.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||!/compatible/.test(a)&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}},
browser:{}});z=c.uaMatch(z);if(z.browser){c.browser[z.browser]=true;c.browser.version=z.version}if(c.browser.webkit)c.browser.safari=true;if(Ha)c.inArray=function(a,b){return Ha.call(b,a)};fa=c(k);if(k.addEventListener)$=function(){k.removeEventListener("DOMContentLoaded",$,false);c.ready()};else if(k.attachEvent)$=function(){if(k.readyState==="complete"){k.detachEvent("onreadystatechange",$);c.ready()}};(function(){c.support={};var a=k.documentElement,b=k.createElement("script"),d=k.createElement("div"),
f="script"+A();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var e=d.getElementsByTagName("*"),i=d.getElementsByTagName("a")[0];if(!(!e||!e.length||!i)){c.support={leadingWhitespace:d.firstChild.nodeType===3,tbody:!d.getElementsByTagName("tbody").length,htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(i.getAttribute("style")),hrefNormalized:i.getAttribute("href")==="/a",opacity:/^0.55$/.test(i.style.opacity),
cssFloat:!!i.style.cssFloat,checkOn:d.getElementsByTagName("input")[0].value==="on",optSelected:k.createElement("select").appendChild(k.createElement("option")).selected,parentNode:d.removeChild(d.appendChild(k.createElement("div"))).parentNode===null,deleteExpando:true,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null};b.type="text/javascript";try{b.appendChild(k.createTextNode("window."+f+"=1;"))}catch(j){}a.insertBefore(b,a.firstChild);if(v[f]){c.support.scriptEval=true;delete v[f]}try{delete b.test}catch(q){c.support.deleteExpando=
false}a.removeChild(b);if(d.attachEvent&&d.fireEvent){d.attachEvent("onclick",function l(){c.support.noCloneEvent=false;d.detachEvent("onclick",l)});d.cloneNode(true).fireEvent("onclick")}d=k.createElement("div");d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";a=k.createDocumentFragment();a.appendChild(d.firstChild);c.support.checkClone=a.cloneNode(true).cloneNode(true).lastChild.checked;c(function(){var l=k.createElement("div");l.style.width=l.style.paddingLeft="1px";k.body.appendChild(l);
c.boxModel=c.support.boxModel=l.offsetWidth===2;k.body.removeChild(l).style.display="none"});a=function(l){var p=k.createElement("div");l="on"+l;var u=l in p;if(!u){p.setAttribute(l,"return;");u=typeof p[l]==="function"}return u};c.support.submitBubbles=a("submit");c.support.changeBubbles=a("change");a=b=d=e=i=null}})();c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",
frameborder:"frameBorder"};var ja="jQuery"+A(),$a=0,Ia={};c.extend({cache:{},expando:ja,noData:{embed:true,object:true,applet:true},data:function(a,b,d){if(!(a.nodeName&&c.noData[a.nodeName.toLowerCase()])){a=a==v?Ia:a;var f=a[ja],e=c.cache;if(!f&&typeof b==="string"&&d===C)return null;f||(f=++$a);if(typeof b==="object"){a[ja]=f;e[f]=c.extend(true,{},b)}else if(!e[f]){a[ja]=f;e[f]={}}a=e[f];if(d!==C)a[b]=d;return typeof b==="string"?a[b]:a}},removeData:function(a,b){if(!(a.nodeName&&c.noData[a.nodeName.toLowerCase()])){a=
a==v?Ia:a;var d=a[ja],f=c.cache,e=f[d];if(b){if(e){delete e[b];c.isEmptyObject(e)&&c.removeData(a)}}else{if(c.support.deleteExpando)delete a[c.expando];else a.removeAttribute&&a.removeAttribute(c.expando);delete f[d]}}}});c.fn.extend({data:function(a,b){if(typeof a==="undefined"&&this.length)return c.data(this[0]);else if(typeof a==="object")return this.each(function(){c.data(this,a)});var d=a.split(".");d[1]=d[1]?"."+d[1]:"";if(b===C){var f=this.triggerHandler("getData"+d[1]+"!",[d[0]]);if(f===C&&
this.length)f=c.data(this[0],a);return f===C&&d[1]?this.data(d[0]):f}else return this.trigger("setData"+d[1]+"!",[d[0],b]).each(function(){c.data(this,a,b)})},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var f=c.data(a,b);if(!d)return f||[];if(!f||c.isArray(d))f=c.data(a,b,c.makeArray(d));else f.push(d);return f}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),f=d.shift();if(f==="inprogress")f=d.shift();
if(f){b==="fx"&&d.unshift("inprogress");f.call(a,function(){c.dequeue(a,b)})}}});c.fn.extend({queue:function(a,b){if(typeof a!=="string"){b=a;a="fx"}if(b===C)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,a,b);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||
"fx",[])}});var Ja=/[\n\t]/g,ua=/\s+/,ab=/\r/g,bb=/href|src|style/,cb=/(button|input)/i,db=/(button|input|object|select|textarea)/i,eb=/^(a|area)$/i,Ka=/radio|checkbox/;c.fn.extend({attr:function(a,b){return G(this,a,b,true,c.attr)},removeAttr:function(a){return this.each(function(){c.attr(this,a,"");this.nodeType===1&&this.removeAttribute(a)})},addClass:function(a){if(c.isFunction(a))return this.each(function(p){var u=c(this);u.addClass(a.call(this,p,u.attr("class")))});if(a&&typeof a==="string")for(var b=
(a||"").split(ua),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===1)if(e.className){for(var i=" "+e.className+" ",j=e.className,q=0,l=b.length;q<l;q++)if(i.indexOf(" "+b[q]+" ")<0)j+=" "+b[q];e.className=c.trim(j)}else e.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(l){var p=c(this);p.removeClass(a.call(this,l,p.attr("class")))});if(a&&typeof a==="string"||a===C)for(var b=(a||"").split(ua),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===
1&&e.className)if(a){for(var i=(" "+e.className+" ").replace(Ja," "),j=0,q=b.length;j<q;j++)i=i.replace(" "+b[j]+" "," ");e.className=c.trim(i)}else e.className=""}return this},toggleClass:function(a,b){var d=typeof a,f=typeof b==="boolean";if(c.isFunction(a))return this.each(function(e){var i=c(this);i.toggleClass(a.call(this,e,i.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var e,i=0,j=c(this),q=b,l=a.split(ua);e=l[i++];){q=f?q:!j.hasClass(e);j[q?"addClass":"removeClass"](e)}else if(d===
"undefined"||d==="boolean"){this.className&&c.data(this,"__className__",this.className);this.className=this.className||a===false?"":c.data(this,"__className__")||""}})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if((" "+this[b].className+" ").replace(Ja," ").indexOf(a)>-1)return true;return false},val:function(a){if(a===C){var b=this[0];if(b){if(c.nodeName(b,"option"))return(b.attributes.value||{}).specified?b.value:b.text;if(c.nodeName(b,"select")){var d=b.selectedIndex,f=
[],e=b.options;b=b.type==="select-one";if(d<0)return null;var i=b?d:0;for(d=b?d+1:e.length;i<d;i++){var j=e[i];if(j.selected){a=c(j).val();if(b)return a;f.push(a)}}return f}if(Ka.test(b.type)&&!c.support.checkOn)return b.getAttribute("value")===null?"on":b.value;return(b.value||"").replace(ab,"")}return C}var q=c.isFunction(a);return this.each(function(l){var p=c(this),u=a;if(this.nodeType===1){if(q)u=a.call(this,l,p.val());if(typeof u==="number")u+="";if(c.isArray(u)&&Ka.test(this.type))this.checked=
c.inArray(p.val(),u)>=0;else if(c.nodeName(this,"select")){var D=c.makeArray(u);c("option",this).each(function(){this.selected=c.inArray(c(this).val(),D)>=0});if(!D.length)this.selectedIndex=-1}else this.value=u}})}});c.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,b,d,f){if(!a||a.nodeType===3||a.nodeType===8)return C;if(f&&b in c.attrFn)return c(a)[b](d);f=a.nodeType!==1||!c.isXMLDoc(a);var e=d!==C;b=f&&c.props[b]||b;if(a.nodeType===
1){var i=bb.test(b);if(b in a&&f&&!i){if(e){b==="type"&&cb.test(a.nodeName)&&a.parentNode&&c.error("type property can't be changed");a[b]=d}if(c.nodeName(a,"form")&&a.getAttributeNode(b))return a.getAttributeNode(b).nodeValue;if(b==="tabIndex")return(b=a.getAttributeNode("tabIndex"))&&b.specified?b.value:db.test(a.nodeName)||eb.test(a.nodeName)&&a.href?0:C;return a[b]}if(!c.support.style&&f&&b==="style"){if(e)a.style.cssText=""+d;return a.style.cssText}e&&a.setAttribute(b,""+d);a=!c.support.hrefNormalized&&
f&&i?a.getAttribute(b,2):a.getAttribute(b);return a===null?C:a}return c.style(a,b,d)}});var pa=/\.(.*)$/,fb=function(a){return a.replace(/[^\w\s\.\|`]/g,function(b){return"\\"+b})};c.event={add:function(a,b,d,f){if(!(a.nodeType===3||a.nodeType===8)){if(a.setInterval&&a!==v&&!a.frameElement)a=v;var e,i;if(d.handler){e=d;d=e.handler}if(!d.guid)d.guid=c.guid++;if(i=c.data(a)){var j=i.events=i.events||{},q=i.handle;if(!q)i.handle=q=function(){return typeof c!=="undefined"&&!c.event.triggered?c.event.handle.apply(q.elem,
arguments):C};q.elem=a;b=b.split(" ");for(var l,p=0,u;l=b[p++];){i=e?c.extend({},e):{handler:d,data:f};if(l.indexOf(".")>-1){u=l.split(".");l=u.shift();i.namespace=u.slice(0).sort().join(".")}else{u=[];i.namespace=""}i.type=l;i.guid=d.guid;var D=j[l],J=c.event.special[l]||{};if(!D){D=j[l]=[];if(!J.setup||J.setup.call(a,f,u,q)===false)if(a.addEventListener)a.addEventListener(l,q,false);else a.attachEvent&&a.attachEvent("on"+l,q)}if(J.add){J.add.call(a,i);if(!i.handler.guid)i.handler.guid=d.guid}D.push(i);
c.event.global[l]=true}a=null}}},global:{},remove:function(a,b,d,f){if(!(a.nodeType===3||a.nodeType===8)){var e,i=0,j,q,l,p,u,D,J=c.data(a),P=J&&J.events;if(J&&P){if(b&&b.type){d=b.handler;b=b.type}if(!b||typeof b==="string"&&b.charAt(0)==="."){b=b||"";for(e in P)c.event.remove(a,e+b)}else{for(b=b.split(" ");e=b[i++];){p=e;j=e.indexOf(".")<0;q=[];if(!j){q=e.split(".");e=q.shift();l=new RegExp("(^|\\.)"+c.map(q.slice(0).sort(),fb).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(u=P[e])if(d){p=c.event.special[e]||
{};for(N=f||0;N<u.length;N++){D=u[N];if(d.guid===D.guid){if(j||l.test(D.namespace)){f==null&&u.splice(N--,1);p.remove&&p.remove.call(a,D)}if(f!=null)break}}if(u.length===0||f!=null&&u.length===1){if(!p.teardown||p.teardown.call(a,q)===false)La(a,e,J.handle);delete P[e]}}else for(var N=0;N<u.length;N++){D=u[N];if(j||l.test(D.namespace)){c.event.remove(a,p,D.handler,N);u.splice(N--,1)}}}if(c.isEmptyObject(P)){if(b=J.handle)b.elem=null;delete J.events;delete J.handle;c.isEmptyObject(J)&&c.removeData(a)}}}}},
trigger:function(a,b,d,f){var e=a.type||a;if(!f){a=typeof a==="object"?a[ja]?a:c.extend(c.Event(e),a):c.Event(e);if(e.indexOf("!")>=0){a.type=e=e.slice(0,-1);a.exclusive=true}if(!d){a.stopPropagation();c.event.global[e]&&c.each(c.cache,function(){this.events&&this.events[e]&&c.event.trigger(a,b,this.handle.elem)})}if(!d||d.nodeType===3||d.nodeType===8)return C;a.result=C;a.target=d;b=c.makeArray(b);b.unshift(a)}a.currentTarget=d;(f=c.data(d,"handle"))&&f.apply(d,b);f=d.parentNode||d.ownerDocument;
try{if(!(d&&d.nodeName&&c.noData[d.nodeName.toLowerCase()]))if(d["on"+e]&&d["on"+e].apply(d,b)===false)a.result=false}catch(i){}if(!a.isPropagationStopped()&&f)c.event.trigger(a,b,f,true);else if(!a.isDefaultPrevented()){f=a.target;var j,q=c.nodeName(f,"a")&&e==="click",l=c.event.special[e]||{};if((!l._default||l._default.call(d,a)===false)&&!q&&!(f&&f.nodeName&&c.noData[f.nodeName.toLowerCase()])){try{if(f[e]){if(j=f["on"+e])f["on"+e]=null;c.event.triggered=true;f[e]()}}catch(p){}if(j)f["on"+e]=
j;c.event.triggered=false}}},handle:function(a){var b,d,f,e;a=arguments[0]=c.event.fix(a||v.event);a.currentTarget=this;b=a.type.indexOf(".")<0&&!a.exclusive;if(!b){d=a.type.split(".");a.type=d.shift();f=new RegExp("(^|\\.)"+d.slice(0).sort().join("\\.(?:.*\\.)?")+"(\\.|$)")}e=c.data(this,"events");d=e[a.type];if(e&&d){d=d.slice(0);e=0;for(var i=d.length;e<i;e++){var j=d[e];if(b||f.test(j.namespace)){a.handler=j.handler;a.data=j.data;a.handleObj=j;j=j.handler.apply(this,arguments);if(j!==C){a.result=
j;if(j===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY originalTarget pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),fix:function(a){if(a[ja])return a;
var b=a;a=c.Event(b);for(var d=this.props.length,f;d;){f=this.props[--d];a[f]=b[f]}if(!a.target)a.target=a.srcElement||k;if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null){b=k.documentElement;d=k.body;a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(b&&b.scrollTop||d&&d.scrollTop||0)-(b&&b.clientTop||
d&&d.clientTop||0)}if(!a.which&&(a.charCode||a.charCode===0?a.charCode:a.keyCode))a.which=a.charCode||a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==C)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,a.origType,c.extend({},a,{handler:S}))},remove:function(a){var b=true,d=a.origType.replace(pa,"");c.each(c.data(this,"events").live||[],function(){if(d===
this.origType.replace(pa,""))return b=false});b&&c.event.remove(this,a.origType,S)}},beforeunload:{setup:function(a,b,d){if(this.setInterval)this.onbeforeunload=d;return false},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};var La=k.removeEventListener?function(a,b,d){a.removeEventListener(b,d,false)}:function(a,b,d){a.detachEvent("on"+b,d)};c.Event=function(a){if(!this.preventDefault)return new c.Event(a);if(a&&a.type){this.originalEvent=a;this.type=a.type}else this.type=
a;this.timeStamp=A();this[ja]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=O;var a=this.originalEvent;if(a){a.preventDefault&&a.preventDefault();a.returnValue=false}},stopPropagation:function(){this.isPropagationStopped=O;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=O;this.stopPropagation()},isDefaultPrevented:L,isPropagationStopped:L,isImmediatePropagationStopped:L};
var Ma=function(a){var b=a.relatedTarget;try{for(;b&&b!==this;)b=b.parentNode;if(b!==this){a.type=a.data;c.event.handle.apply(this,arguments)}}catch(d){}},Na=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?Na:Ma,a)},teardown:function(d){c.event.remove(this,b,d&&d.selector?Na:Ma)}}});if(!c.support.submitBubbles)c.event.special.submit={setup:function(){if(this.nodeName.toLowerCase()!==
"form"){c.event.add(this,"click.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="submit"||d==="image")&&c(b).closest("form").length)return U("submit",this,arguments)});c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="text"||d==="password")&&c(b).closest("form").length&&a.keyCode===13)return U("submit",this,arguments)})}else return false},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var va=/textarea|input|select/i,
wa,Oa=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedIndex>-1?c.map(a.options,function(f){return f.selected}).join("-"):"";else if(a.nodeName.toLowerCase()==="select")d=a.selectedIndex;return d},xa=function(a,b){var d=a.target,f,e;if(!(!va.test(d.nodeName)||d.readOnly)){f=c.data(d,"_change_data");e=Oa(d);if(a.type!=="focusout"||d.type!=="radio")c.data(d,"_change_data",e);if(!(f===C||e===f))if(f!=null||e){a.type="change";return c.event.trigger(a,
b,d)}}};c.event.special.change={filters:{focusout:xa,click:function(a){var b=a.target,d=b.type;if(d==="radio"||d==="checkbox"||b.nodeName.toLowerCase()==="select")return xa.call(this,a)},keydown:function(a){var b=a.target,d=b.type;if(a.keyCode===13&&b.nodeName.toLowerCase()!=="textarea"||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return xa.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,"_change_data",Oa(a))}},setup:function(){if(this.type==="file")return false;
for(var a in wa)c.event.add(this,a+".specialChange",wa[a]);return va.test(this.nodeName)},teardown:function(){c.event.remove(this,".specialChange");return va.test(this.nodeName)}};wa=c.event.special.change.filters}k.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(f){f=c.event.fix(f);f.type=b;return c.event.handle.call(this,f)}c.event.special[b]={setup:function(){this.addEventListener(a,d,true)},teardown:function(){this.removeEventListener(a,d,true)}}});c.each(["bind",
"one"],function(a,b){c.fn[b]=function(d,f,e){if(typeof d==="object"){for(var i in d)this[b](i,f,d[i],e);return this}if(c.isFunction(f)){e=f;f=C}var j=b==="one"?c.proxy(e,function(l){c(this).unbind(l,j);return e.apply(this,arguments)}):e;if(d==="unload"&&b!=="one")this.one(d,f,e);else{i=0;for(var q=this.length;i<q;i++)c.event.add(this[i],d,j,f)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,a[d]);else{d=0;for(var f=this.length;d<
f;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,d,f){return this.live(b,d,f,a)},undelegate:function(a,b,d){return arguments.length===0?this.unbind("live"):this.die(b,null,d,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0]){a=c.Event(a);a.preventDefault();a.stopPropagation();c.event.trigger(a,b,this[0]);return a.result}},toggle:function(a){for(var b=arguments,d=1;d<b.length;)c.proxy(a,b[d++]);return this.click(c.proxy(a,
function(f){var e=(c.data(this,"lastToggle"+a.guid)||0)%d;c.data(this,"lastToggle"+a.guid,e+1);f.preventDefault();return b[e].apply(this,arguments)||false}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var Pa={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(d,f,e,i){var j,q=0,l,p,u=i||this.selector,D=i?this:c(this.context);if(c.isFunction(f)){e=f;f=C}for(d=(d||"").split(" ");(j=d[q++])!=null;){i=
pa.exec(j);l="";if(i){l=i[0];j=j.replace(pa,"")}if(j==="hover")d.push("mouseenter"+l,"mouseleave"+l);else{p=j;if(j==="focus"||j==="blur"){d.push(Pa[j]+l);j+=l}else j=(Pa[j]||j)+l;b==="live"?D.each(function(){c.event.add(this,K(j,u),{data:f,selector:u,handler:e,origType:j,origHandler:e,preType:p})}):D.unbind(K(j,u),e)}}return this}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),
function(a,b){c.fn[b]=function(d){return d?this.bind(b,d):this.trigger(b)};if(c.attrFn)c.attrFn[b]=true});v.attachEvent&&!v.addEventListener&&v.attachEvent("onunload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});(function(){function a(g){for(var h="",m,n=0;g[n];n++){m=g[n];if(m.nodeType===3||m.nodeType===4)h+=m.nodeValue;else if(m.nodeType!==8)h+=a(m.childNodes)}return h}function b(g,h,m,n,t,s){t=0;for(var F=n.length;t<F;t++){var B=n[t];
if(B){B=B[g];for(var I=false;B;){if(B.sizcache===m){I=n[B.sizset];break}if(B.nodeType===1&&!s){B.sizcache=m;B.sizset=t}if(B.nodeName.toLowerCase()===h){I=B;break}B=B[g]}n[t]=I}}}function d(g,h,m,n,t,s){t=0;for(var F=n.length;t<F;t++){var B=n[t];if(B){B=B[g];for(var I=false;B;){if(B.sizcache===m){I=n[B.sizset];break}if(B.nodeType===1){if(!s){B.sizcache=m;B.sizset=t}if(typeof h!=="string"){if(B===h){I=true;break}}else if(l.filter(h,[B]).length>0){I=B;break}}B=B[g]}n[t]=I}}}var f=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^[\]]*\]|['"][^'"]*['"]|[^[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,
e=0,i=Object.prototype.toString,j=false,q=true;[0,0].sort(function(){q=false;return 0});var l=function(g,h,m,n){m=m||[];var t=h=h||k;if(h.nodeType!==1&&h.nodeType!==9)return[];if(!g||typeof g!=="string")return m;for(var s=[],F,B,I,qa,ka=true,ma=H(h),la=g;(f.exec(""),F=f.exec(la))!==null;){la=F[3];s.push(F[1]);if(F[2]){qa=F[3];break}}if(s.length>1&&u.exec(g))if(s.length===2&&p.relative[s[0]])B=ya(s[0]+s[1],h);else for(B=p.relative[s[0]]?[h]:l(s.shift(),h);s.length;){g=s.shift();if(p.relative[g])g+=
s.shift();B=ya(g,B)}else{if(!n&&s.length>1&&h.nodeType===9&&!ma&&p.match.ID.test(s[0])&&!p.match.ID.test(s[s.length-1])){F=l.find(s.shift(),h,ma);h=F.expr?l.filter(F.expr,F.set)[0]:F.set[0]}if(h){F=n?{expr:s.pop(),set:J(n)}:l.find(s.pop(),s.length===1&&(s[0]==="~"||s[0]==="+")&&h.parentNode?h.parentNode:h,ma);B=F.expr?l.filter(F.expr,F.set):F.set;if(s.length>0)I=J(B);else ka=false;for(;s.length;){var aa=s.pop();F=aa;if(p.relative[aa])F=s.pop();else aa="";if(F==null)F=h;p.relative[aa](I,F,ma)}}else I=
[]}I||(I=B);I||l.error(aa||g);if(i.call(I)==="[object Array]")if(ka)if(h&&h.nodeType===1)for(g=0;I[g]!=null;g++){if(I[g]&&(I[g]===true||I[g].nodeType===1&&ba(h,I[g])))m.push(B[g])}else for(g=0;I[g]!=null;g++)I[g]&&I[g].nodeType===1&&m.push(B[g]);else m.push.apply(m,I);else J(I,m);if(qa){l(qa,t,m,n);l.uniqueSort(m)}return m};l.uniqueSort=function(g){if(N){j=q;g.sort(N);if(j)for(var h=1;h<g.length;h++)g[h]===g[h-1]&&g.splice(h--,1)}return g};l.matches=function(g,h){return l(g,null,null,h)};l.find=function(g,
h,m){var n,t;if(!g)return[];for(var s=0,F=p.order.length;s<F;s++){var B=p.order[s];if(t=p.leftMatch[B].exec(g)){var I=t[1];t.splice(1,1);if(I.substr(I.length-1)!=="\\"){t[1]=(t[1]||"").replace(/\\/g,"");n=p.find[B](t,h,m);if(n!=null){g=g.replace(p.match[B],"");break}}}}n||(n=h.getElementsByTagName("*"));return{set:n,expr:g}};l.filter=function(g,h,m,n){for(var t=g,s=[],F=h,B,I,qa=h&&h[0]&&H(h[0]);g&&h.length;){for(var ka in p.filter)if((B=p.leftMatch[ka].exec(g))!=null&&B[2]){var ma=p.filter[ka],la,
aa;aa=B[1];I=false;B.splice(1,1);if(aa.substr(aa.length-1)!=="\\"){if(F===s)s=[];if(p.preFilter[ka])if(B=p.preFilter[ka](B,F,m,s,n,qa)){if(B===true)continue}else I=la=true;if(B)for(var ra=0;(aa=F[ra])!=null;ra++)if(aa){la=ma(aa,B,ra,F);var Qa=n^!!la;if(m&&la!=null)if(Qa)I=true;else F[ra]=false;else if(Qa){s.push(aa);I=true}}if(la!==C){m||(F=s);g=g.replace(p.match[ka],"");if(!I)return[];break}}}if(g===t)if(I==null)l.error(g);else break;t=g}return F};l.error=function(g){throw"Syntax error, unrecognized expression: "+
g;};var p=l.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},
leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(g){return g.getAttribute("href")}},relative:{"+":function(g,h){var m=typeof h==="string",n=m&&!/\W/.test(h);m=m&&!n;if(n)h=h.toLowerCase();n=0;for(var t=g.length,s;n<t;n++)if(s=g[n]){for(;(s=s.previousSibling)&&s.nodeType!==1;);g[n]=m||s&&s.nodeName.toLowerCase()===h?s||false:s===h}m&&l.filter(h,g,true)},">":function(g,h){var m=typeof h==="string";if(m&&!/\W/.test(h)){h=h.toLowerCase();for(var n=0,t=g.length;n<t;n++){var s=
g[n];if(s){m=s.parentNode;g[n]=m.nodeName.toLowerCase()===h?m:false}}}else{n=0;for(t=g.length;n<t;n++)if(s=g[n])g[n]=m?s.parentNode:s.parentNode===h;m&&l.filter(h,g,true)}},"":function(g,h,m){var n=e++,t=d;if(typeof h==="string"&&!/\W/.test(h)){var s=h=h.toLowerCase();t=b}t("parentNode",h,n,g,s,m)},"~":function(g,h,m){var n=e++,t=d;if(typeof h==="string"&&!/\W/.test(h)){var s=h=h.toLowerCase();t=b}t("previousSibling",h,n,g,s,m)}},find:{ID:function(g,h,m){if(typeof h.getElementById!=="undefined"&&
!m)return(g=h.getElementById(g[1]))?[g]:[]},NAME:function(g,h){if(typeof h.getElementsByName!=="undefined"){var m=[];h=h.getElementsByName(g[1]);for(var n=0,t=h.length;n<t;n++)h[n].getAttribute("name")===g[1]&&m.push(h[n]);return m.length===0?null:m}},TAG:function(g,h){return h.getElementsByTagName(g[1])}},preFilter:{CLASS:function(g,h,m,n,t,s){g=" "+g[1].replace(/\\/g,"")+" ";if(s)return g;s=0;for(var F;(F=h[s])!=null;s++)if(F)if(t^(F.className&&(" "+F.className+" ").replace(/[\t\n]/g," ").indexOf(g)>=
0))m||n.push(F);else if(m)h[s]=false;return false},ID:function(g){return g[1].replace(/\\/g,"")},TAG:function(g){return g[1].toLowerCase()},CHILD:function(g){if(g[1]==="nth"){var h=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(g[2]==="even"&&"2n"||g[2]==="odd"&&"2n+1"||!/\D/.test(g[2])&&"0n+"+g[2]||g[2]);g[2]=h[1]+(h[2]||1)-0;g[3]=h[3]-0}g[0]=e++;return g},ATTR:function(g,h,m,n,t,s){h=g[1].replace(/\\/g,"");if(!s&&p.attrMap[h])g[1]=p.attrMap[h];if(g[2]==="~=")g[4]=" "+g[4]+" ";return g},PSEUDO:function(g,h,m,n,
t){if(g[1]==="not")if((f.exec(g[3])||"").length>1||/^\w/.test(g[3]))g[3]=l(g[3],null,null,h);else{g=l.filter(g[3],h,m,true^t);m||n.push.apply(n,g);return false}else if(p.match.POS.test(g[0])||p.match.CHILD.test(g[0]))return true;return g},POS:function(g){g.unshift(true);return g}},filters:{enabled:function(g){return g.disabled===false&&g.type!=="hidden"},disabled:function(g){return g.disabled===true},checked:function(g){return g.checked===true},selected:function(g){return g.selected===true},parent:function(g){return!!g.firstChild},
empty:function(g){return!g.firstChild},has:function(g,h,m){return!!l(m[3],g).length},header:function(g){return/h\d/i.test(g.nodeName)},text:function(g){return"text"===g.type},radio:function(g){return"radio"===g.type},checkbox:function(g){return"checkbox"===g.type},file:function(g){return"file"===g.type},password:function(g){return"password"===g.type},submit:function(g){return"submit"===g.type},image:function(g){return"image"===g.type},reset:function(g){return"reset"===g.type},button:function(g){return"button"===
g.type||g.nodeName.toLowerCase()==="button"},input:function(g){return/input|select|textarea|button/i.test(g.nodeName)}},setFilters:{first:function(g,h){return h===0},last:function(g,h,m,n){return h===n.length-1},even:function(g,h){return h%2===0},odd:function(g,h){return h%2===1},lt:function(g,h,m){return h<m[3]-0},gt:function(g,h,m){return h>m[3]-0},nth:function(g,h,m){return m[3]-0===h},eq:function(g,h,m){return m[3]-0===h}},filter:{PSEUDO:function(g,h,m,n){var t=h[1],s=p.filters[t];if(s)return s(g,
m,h,n);else if(t==="contains")return(g.textContent||g.innerText||a([g])||"").indexOf(h[3])>=0;else if(t==="not"){h=h[3];m=0;for(n=h.length;m<n;m++)if(h[m]===g)return false;return true}else l.error("Syntax error, unrecognized expression: "+t)},CHILD:function(g,h){var m=h[1],n=g;switch(m){case "only":case "first":for(;n=n.previousSibling;)if(n.nodeType===1)return false;if(m==="first")return true;n=g;case "last":for(;n=n.nextSibling;)if(n.nodeType===1)return false;return true;case "nth":m=h[2];var t=
h[3];if(m===1&&t===0)return true;h=h[0];var s=g.parentNode;if(s&&(s.sizcache!==h||!g.nodeIndex)){var F=0;for(n=s.firstChild;n;n=n.nextSibling)if(n.nodeType===1)n.nodeIndex=++F;s.sizcache=h}g=g.nodeIndex-t;return m===0?g===0:g%m===0&&g/m>=0}},ID:function(g,h){return g.nodeType===1&&g.getAttribute("id")===h},TAG:function(g,h){return h==="*"&&g.nodeType===1||g.nodeName.toLowerCase()===h},CLASS:function(g,h){return(" "+(g.className||g.getAttribute("class"))+" ").indexOf(h)>-1},ATTR:function(g,h){var m=
h[1];g=p.attrHandle[m]?p.attrHandle[m](g):g[m]!=null?g[m]:g.getAttribute(m);m=g+"";var n=h[2];h=h[4];return g==null?n==="!=":n==="="?m===h:n==="*="?m.indexOf(h)>=0:n==="~="?(" "+m+" ").indexOf(h)>=0:!h?m&&g!==false:n==="!="?m!==h:n==="^="?m.indexOf(h)===0:n==="$="?m.substr(m.length-h.length)===h:n==="|="?m===h||m.substr(0,h.length+1)===h+"-":false},POS:function(g,h,m,n){var t=p.setFilters[h[2]];if(t)return t(g,m,h,n)}}},u=p.match.POS;for(var D in p.match){p.match[D]=new RegExp(p.match[D].source+/(?![^\[]*\])(?![^\(]*\))/.source);
p.leftMatch[D]=new RegExp(/(^(?:.|\r|\n)*?)/.source+p.match[D].source.replace(/\\(\d+)/g,function(g,h){return"\\"+(h-0+1)}))}var J=function(g,h){g=Array.prototype.slice.call(g,0);if(h){h.push.apply(h,g);return h}return g};try{Array.prototype.slice.call(k.documentElement.childNodes,0)}catch(P){J=function(g,h){h=h||[];if(i.call(g)==="[object Array]")Array.prototype.push.apply(h,g);else if(typeof g.length==="number")for(var m=0,n=g.length;m<n;m++)h.push(g[m]);else for(m=0;g[m];m++)h.push(g[m]);return h}}var N;
if(k.documentElement.compareDocumentPosition)N=function(g,h){if(!g.compareDocumentPosition||!h.compareDocumentPosition){if(g==h)j=true;return g.compareDocumentPosition?-1:1}g=g.compareDocumentPosition(h)&4?-1:g===h?0:1;if(g===0)j=true;return g};else if("sourceIndex"in k.documentElement)N=function(g,h){if(!g.sourceIndex||!h.sourceIndex){if(g==h)j=true;return g.sourceIndex?-1:1}g=g.sourceIndex-h.sourceIndex;if(g===0)j=true;return g};else if(k.createRange)N=function(g,h){if(!g.ownerDocument||!h.ownerDocument){if(g==
h)j=true;return g.ownerDocument?-1:1}var m=g.ownerDocument.createRange(),n=h.ownerDocument.createRange();m.setStart(g,0);m.setEnd(g,0);n.setStart(h,0);n.setEnd(h,0);g=m.compareBoundaryPoints(Range.START_TO_END,n);if(g===0)j=true;return g};(function(){var g=k.createElement("div"),h="script"+(new Date).getTime();g.innerHTML="<a name='"+h+"'/>";var m=k.documentElement;m.insertBefore(g,m.firstChild);if(k.getElementById(h)){p.find.ID=function(n,t,s){if(typeof t.getElementById!=="undefined"&&!s)return(t=
t.getElementById(n[1]))?t.id===n[1]||typeof t.getAttributeNode!=="undefined"&&t.getAttributeNode("id").nodeValue===n[1]?[t]:C:[]};p.filter.ID=function(n,t){var s=typeof n.getAttributeNode!=="undefined"&&n.getAttributeNode("id");return n.nodeType===1&&s&&s.nodeValue===t}}m.removeChild(g);m=g=null})();(function(){var g=k.createElement("div");g.appendChild(k.createComment(""));if(g.getElementsByTagName("*").length>0)p.find.TAG=function(h,m){m=m.getElementsByTagName(h[1]);if(h[1]==="*"){h=[];for(var n=
0;m[n];n++)m[n].nodeType===1&&h.push(m[n]);m=h}return m};g.innerHTML="<a href='#'></a>";if(g.firstChild&&typeof g.firstChild.getAttribute!=="undefined"&&g.firstChild.getAttribute("href")!=="#")p.attrHandle.href=function(h){return h.getAttribute("href",2)};g=null})();k.querySelectorAll&&function(){var g=l,h=k.createElement("div");h.innerHTML="<p class='TEST'></p>";if(!(h.querySelectorAll&&h.querySelectorAll(".TEST").length===0)){l=function(n,t,s,F){t=t||k;if(!F&&t.nodeType===9&&!H(t))try{return J(t.querySelectorAll(n),
s)}catch(B){}return g(n,t,s,F)};for(var m in g)l[m]=g[m];h=null}}();(function(){var g=k.createElement("div");g.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!g.getElementsByClassName||g.getElementsByClassName("e").length===0)){g.lastChild.className="e";if(g.getElementsByClassName("e").length!==1){p.order.splice(1,0,"CLASS");p.find.CLASS=function(h,m,n){if(typeof m.getElementsByClassName!=="undefined"&&!n)return m.getElementsByClassName(h[1])};g=null}}})();var ba=k.compareDocumentPosition?
function(g,h){return!!(g.compareDocumentPosition(h)&16)}:function(g,h){return g!==h&&(g.contains?g.contains(h):true)},H=function(g){return(g=(g?g.ownerDocument||g:0).documentElement)?g.nodeName!=="HTML":false},ya=function(g,h){var m=[],n="",t;for(h=h.nodeType?[h]:h;t=p.match.PSEUDO.exec(g);){n+=t[0];g=g.replace(p.match.PSEUDO,"")}g=p.relative[g]?g+"*":g;t=0;for(var s=h.length;t<s;t++)l(g,h[t],m);return l.filter(n,m)};c.find=l;c.expr=l.selectors;c.expr[":"]=c.expr.filters;c.unique=l.uniqueSort;c.text=
a;c.isXMLDoc=H;c.contains=ba})();var gb=/Until$/,hb=/^(?:parents|prevUntil|prevAll)/,ib=/,/;ia=Array.prototype.slice;var Ra=function(a,b,d){if(c.isFunction(b))return c.grep(a,function(e,i){return!!b.call(e,i,e)===d});else if(b.nodeType)return c.grep(a,function(e){return e===b===d});else if(typeof b==="string"){var f=c.grep(a,function(e){return e.nodeType===1});if(r.test(b))return c.filter(b,f,!d);else b=c.filter(b,f)}return c.grep(a,function(e){return c.inArray(e,b)>=0===d})};c.fn.extend({find:function(a){for(var b=
this.pushStack("","find",a),d=0,f=0,e=this.length;f<e;f++){d=b.length;c.find(a,this[f],b);if(f>0)for(var i=d;i<b.length;i++)for(var j=0;j<d;j++)if(b[j]===b[i]){b.splice(i--,1);break}}return b},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,f=b.length;d<f;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushStack(Ra(this,a,false),"not",a)},filter:function(a){return this.pushStack(Ra(this,a,true),"filter",a)},is:function(a){return!!a&&c.filter(a,this).length>
0},closest:function(a,b){if(c.isArray(a)){var d=[],f=this[0],e,i={},j;if(f&&a.length){e=0;for(var q=a.length;e<q;e++){j=a[e];i[j]||(i[j]=c.expr.match.POS.test(j)?c(j,b||this.context):j)}for(;f&&f.ownerDocument&&f!==b;){for(j in i){e=i[j];if(e.jquery?e.index(f)>-1:c(f).is(e)){d.push({selector:j,elem:f});delete i[j]}}f=f.parentNode}}return d}var l=c.expr.match.POS.test(a)?c(a,b||this.context):null;return this.map(function(p,u){for(;u&&u.ownerDocument&&u!==b;){if(l?l.index(u)>-1:c(u).is(a))return u;
u=u.parentNode}return null})},index:function(a){if(!a||typeof a==="string")return c.inArray(this[0],a?c(a):this.parent().children());return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b||this.context):c.makeArray(a);b=c.merge(this.get(),a);return this.pushStack(Q(a[0])||Q(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},
parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},
contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,f){var e=c.map(this,b,d);gb.test(a)||(f=d);if(f&&typeof f==="string")e=c.filter(f,e);e=this.length>1?c.unique(e):e;if((this.length>1||ib.test(f))&&hb.test(a))e=e.reverse();return this.pushStack(e,a,ia.call(arguments).join(","))}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return c.find.matches(a,b)},dir:function(a,b,d){var f=[];for(a=
a[b];a&&a.nodeType!==9&&(d===C||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&f.push(a);a=a[b]}return f},nth:function(a,b,d){b=b||1;for(var f=0;a;a=a[d])if(a.nodeType===1&&++f===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var Sa=/ jQuery\d+="(?:\d+|null)"/g,sa=/^\s+/,Ta=/(<([\w:]+)[^>]*?)\/>/g,jb=/^(?:area|br|col|embed|hr|img|input|link|meta|param)$/i,Ua=/<([\w:]+)/,kb=/<tbody/i,lb=/<|&#?\w+;/,Ea=/<script|<object|<embed|<option|<style/i,
Fa=/checked\s*(?:[^=]|=\s*.checked.)/i,Va=function(a,b,d){return jb.test(d)?a:b+"></"+d+">"},ca={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};ca.optgroup=ca.option;ca.tbody=ca.tfoot=ca.colgroup=ca.caption=ca.thead;ca.th=
ca.td;if(!c.support.htmlSerialize)ca._default=[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))});if(typeof a!=="object"&&a!==C)return this.empty().append((this[0]&&this[0].ownerDocument||k).createTextNode(a));return c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&
b.insertBefore(this[0]);b.map(function(){for(var d=this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},
append:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this)});else if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&
this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,f;(f=this[d])!=null;d++)if(!a||c.filter(a,[f]).length){if(!b&&f.nodeType===1){c.cleanData(f.getElementsByTagName("*"));c.cleanData([f])}f.parentNode&&f.parentNode.removeChild(f)}return this},empty:function(){for(var a=0,b;(b=
this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);return this},clone:function(a){var b=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var d=this.outerHTML,f=this.ownerDocument;if(!d){d=f.createElement("div");d.appendChild(this.cloneNode(true));d=d.innerHTML}return c.clean([d.replace(Sa,"").replace(/=([^="'>\s]+\/)>/g,'="$1">').replace(sa,"")],f)[0]}else return this.cloneNode(true)});if(a===true){R(this,b);
R(this.find("*"),b.find("*"))}return b},html:function(a){if(a===C)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(Sa,""):null;else if(typeof a==="string"&&!Ea.test(a)&&(c.support.leadingWhitespace||!sa.test(a))&&!ca[(Ua.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Ta,Va);try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1){c.cleanData(this[b].getElementsByTagName("*"));this[b].innerHTML=a}}catch(f){this.empty().append(a)}}else c.isFunction(a)?this.each(function(e){var i=
c(this),j=i.html();i.empty().append(function(){return a.call(this,e,j)})}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=c(this),f=d.html();d.replaceWith(a.call(this,b,f))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a)},
detach:function(a){return this.remove(a,true)},domManip:function(a,b,d){function f(D){return c.nodeName(D,"table")?D.getElementsByTagName("tbody")[0]||D.appendChild(D.ownerDocument.createElement("tbody")):D}var e,i,j=a[0],q=[],l;if(!c.support.checkClone&&arguments.length===3&&typeof j==="string"&&Fa.test(j))return this.each(function(){c(this).domManip(a,b,d,true)});if(c.isFunction(j))return this.each(function(D){var J=c(this);a[0]=j.call(this,D,b?J.html():C);J.domManip(a,b,d)});if(this[0]){e=j&&j.parentNode;
e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:da(a,this,q);l=e.fragment;if(i=l.childNodes.length===1?(l=l.firstChild):l.firstChild){b=b&&c.nodeName(i,"tr");for(var p=0,u=this.length;p<u;p++)d.call(b?f(this[p],i):this[p],p>0||e.cacheable||this.length>1?l.cloneNode(true):l)}q.length&&c.each(q,y)}return this}});c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=
function(d){var f=[];d=c(d);var e=this.length===1&&this[0].parentNode;if(e&&e.nodeType===11&&e.childNodes.length===1&&d.length===1){d[b](this[0]);return this}else{e=0;for(var i=d.length;e<i;e++){var j=(e>0?this.clone(true):this).get();c.fn[b].apply(c(d[e]),j);f=f.concat(j)}return this.pushStack(f,a,d.selector)}}});c.extend({clean:function(a,b,d,f){b=b||k;if(typeof b.createElement==="undefined")b=b.ownerDocument||b[0]&&b[0].ownerDocument||k;for(var e=[],i=0,j;(j=a[i])!=null;i++){if(typeof j==="number")j+=
"";if(j){if(typeof j==="string"&&!lb.test(j))j=b.createTextNode(j);else if(typeof j==="string"){j=j.replace(Ta,Va);var q=(Ua.exec(j)||["",""])[1].toLowerCase(),l=ca[q]||ca._default,p=l[0],u=b.createElement("div");for(u.innerHTML=l[1]+j+l[2];p--;)u=u.lastChild;if(!c.support.tbody){p=kb.test(j);q=q==="table"&&!p?u.firstChild&&u.firstChild.childNodes:l[1]==="<table>"&&!p?u.childNodes:[];for(l=q.length-1;l>=0;--l)c.nodeName(q[l],"tbody")&&!q[l].childNodes.length&&q[l].parentNode.removeChild(q[l])}!c.support.leadingWhitespace&&
sa.test(j)&&u.insertBefore(b.createTextNode(sa.exec(j)[0]),u.firstChild);j=u.childNodes}if(j.nodeType)e.push(j);else e=c.merge(e,j)}}if(d)for(i=0;e[i];i++)if(f&&c.nodeName(e[i],"script")&&(!e[i].type||e[i].type.toLowerCase()==="text/javascript"))f.push(e[i].parentNode?e[i].parentNode.removeChild(e[i]):e[i]);else{e[i].nodeType===1&&e.splice.apply(e,[i+1,0].concat(c.makeArray(e[i].getElementsByTagName("script"))));d.appendChild(e[i])}return e},cleanData:function(a){for(var b,d,f=c.cache,e=c.event.special,
i=c.support.deleteExpando,j=0,q;(q=a[j])!=null;j++)if(d=q[c.expando]){b=f[d];if(b.events)for(var l in b.events)e[l]?c.event.remove(q,l):La(q,l,b.handle);if(i)delete q[c.expando];else q.removeAttribute&&q.removeAttribute(c.expando);delete f[d]}}});var mb=/z-?index|font-?weight|opacity|zoom|line-?height/i,Wa=/alpha\([^)]*\)/,Xa=/opacity=([^)]*)/,za=/float/i,Aa=/-([a-z])/ig,nb=/([A-Z])/g,ob=/^-?\d+(?:px)?$/i,pb=/^-?\d/,qb={position:"absolute",visibility:"hidden",display:"block"},rb=["Left","Right"],
sb=["Top","Bottom"],tb=k.defaultView&&k.defaultView.getComputedStyle,Ya=c.support.cssFloat?"cssFloat":"styleFloat",Ba=function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){return G(this,a,b,true,function(d,f,e){if(e===C)return c.curCSS(d,f);if(typeof e==="number"&&!mb.test(f))e+="px";c.style(d,f,e)})};c.extend({style:function(a,b,d){if(!a||a.nodeType===3||a.nodeType===8)return C;if((b==="width"||b==="height")&&parseFloat(d)<0)d=C;var f=a.style||a,e=d!==C;if(!c.support.opacity&&b==="opacity"){if(e){f.zoom=
1;b=parseInt(d,10)+""==="NaN"?"":"alpha(opacity="+d*100+")";a=f.filter||c.curCSS(a,"filter")||"";f.filter=Wa.test(a)?a.replace(Wa,b):b}return f.filter&&f.filter.indexOf("opacity=")>=0?parseFloat(Xa.exec(f.filter)[1])/100+"":""}if(za.test(b))b=Ya;b=b.replace(Aa,Ba);if(e)f[b]=d;return f[b]},css:function(a,b,d,f){if(b==="width"||b==="height"){var e,i=b==="width"?rb:sb;d=function(){e=b==="width"?a.offsetWidth:a.offsetHeight;f!=="border"&&c.each(i,function(){f||(e-=parseFloat(c.curCSS(a,"padding"+this,
true))||0);if(f==="margin")e+=parseFloat(c.curCSS(a,"margin"+this,true))||0;else e-=parseFloat(c.curCSS(a,"border"+this+"Width",true))||0})};a.offsetWidth!==0?d():c.swap(a,qb,d);return Math.max(0,Math.round(e))}return c.curCSS(a,b,d)},curCSS:function(a,b,d){var f,e=a.style;if(!c.support.opacity&&b==="opacity"&&a.currentStyle){f=Xa.test(a.currentStyle.filter||"")?parseFloat(RegExp.$1)/100+"":"";return f===""?"1":f}if(za.test(b))b=Ya;if(!d&&e&&e[b])f=e[b];else if(tb){if(za.test(b))b="float";b=b.replace(nb,
"-$1").toLowerCase();e=a.ownerDocument.defaultView;if(!e)return null;if(a=e.getComputedStyle(a,null))f=a.getPropertyValue(b);if(b==="opacity"&&f==="")f="1"}else if(a.currentStyle){d=b.replace(Aa,Ba);f=a.currentStyle[b]||a.currentStyle[d];if(!ob.test(f)&&pb.test(f)){b=e.left;var i=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;e.left=d==="fontSize"?"1em":f||0;f=e.pixelLeft+"px";e.left=b;a.runtimeStyle.left=i}}return f},swap:function(a,b,d){var f={};for(var e in b){f[e]=a.style[e];a.style[e]=
b[e]}d.call(a);for(e in b)a.style[e]=f[e]}});if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=a.offsetWidth,d=a.offsetHeight,f=a.nodeName.toLowerCase()==="tr";return b===0&&d===0&&!f?true:b>0&&d>0&&!f?false:c.curCSS(a,"display")==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}var ub=A(),vb=/<script(.|\s)*?\/script>/gi,wb=/select|textarea/i,xb=/color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week/i,na=/=\?(&|$)/,
Ca=/\?/,yb=/(\?|&)_=.*?(&|$)/,zb=/^(\w+:)?\/\/([^\/?#]+)/,Ab=/%20/g,Bb=c.fn.load;c.fn.extend({load:function(a,b,d){if(typeof a!=="string")return Bb.call(this,a);else if(!this.length)return this;var f=a.indexOf(" ");if(f>=0){var e=a.slice(f,a.length);a=a.slice(0,f)}f="GET";if(b)if(c.isFunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);f="POST"}var i=this;c.ajax({url:a,type:f,dataType:"html",data:b,complete:function(j,q){if(q==="success"||q==="notmodified")i.html(e?
c("<div />").append(j.responseText.replace(vb,"")).find(e):j.responseText);d&&i.each(d,[j.responseText,q,j])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||wb.test(this.nodeName)||xb.test(this.type))}).map(function(a,b){a=c(this).val();return a==null?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,
value:d}}):{name:b.name,value:a}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b=null}return c.ajax({type:"GET",url:a,data:b,success:d,dataType:f})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b={}}return c.ajax({type:"POST",
url:a,data:b,success:d,dataType:f})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,global:true,type:"GET",contentType:"application/x-www-form-urlencoded",processData:true,async:true,xhr:v.XMLHttpRequest&&(v.location.protocol!=="file:"||!v.ActiveXObject)?function(){return new v.XMLHttpRequest}:function(){try{return new v.ActiveXObject("Microsoft.XMLHTTP")}catch(a){}},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",
json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},lastModified:{},etag:{},ajax:function(a){function b(){e.success&&e.success.call(l,q,j,H);e.global&&f("ajaxSuccess",[H,e])}function d(){e.complete&&e.complete.call(l,H,j);e.global&&f("ajaxComplete",[H,e]);e.global&&!--c.active&&c.event.trigger("ajaxStop")}function f(t,s){(e.context?c(e.context):c.event).trigger(t,s)}var e=c.extend(true,{},c.ajaxSettings,a),i,j,q,l=a&&a.context||e,p=e.type.toUpperCase();if(e.data&&e.processData&&
typeof e.data!=="string")e.data=c.param(e.data,e.traditional);if(e.dataType==="jsonp"){if(p==="GET")na.test(e.url)||(e.url+=(Ca.test(e.url)?"&":"?")+(e.jsonp||"callback")+"=?");else if(!e.data||!na.test(e.data))e.data=(e.data?e.data+"&":"")+(e.jsonp||"callback")+"=?";e.dataType="json"}if(e.dataType==="json"&&(e.data&&na.test(e.data)||na.test(e.url))){i=e.jsonpCallback||"jsonp"+ub++;if(e.data)e.data=(e.data+"").replace(na,"="+i+"$1");e.url=e.url.replace(na,"="+i+"$1");e.dataType="script";v[i]=v[i]||
function(t){q=t;b();d();v[i]=C;try{delete v[i]}catch(s){}J&&J.removeChild(P)}}if(e.dataType==="script"&&e.cache===null)e.cache=false;if(e.cache===false&&p==="GET"){var u=A(),D=e.url.replace(yb,"$1_="+u+"$2");e.url=D+(D===e.url?(Ca.test(e.url)?"&":"?")+"_="+u:"")}if(e.data&&p==="GET")e.url+=(Ca.test(e.url)?"&":"?")+e.data;e.global&&!c.active++&&c.event.trigger("ajaxStart");u=(u=zb.exec(e.url))&&(u[1]&&u[1]!==location.protocol||u[2]!==location.host);if(e.dataType==="script"&&p==="GET"&&u){var J=k.getElementsByTagName("head")[0]||
k.documentElement,P=k.createElement("script");P.src=e.url;if(e.scriptCharset)P.charset=e.scriptCharset;if(!i){var N=false;P.onload=P.onreadystatechange=function(){if(!N&&(!this.readyState||this.readyState==="loaded"||this.readyState==="complete")){N=true;b();d();P.onload=P.onreadystatechange=null;J&&P.parentNode&&J.removeChild(P)}}}J.insertBefore(P,J.firstChild);return C}var ba=false,H=e.xhr();if(H){e.username?H.open(p,e.url,e.async,e.username,e.password):H.open(p,e.url,e.async);try{if(e.data||a&&
a.contentType)H.setRequestHeader("Content-Type",e.contentType);if(e.ifModified){c.lastModified[e.url]&&H.setRequestHeader("If-Modified-Since",c.lastModified[e.url]);c.etag[e.url]&&H.setRequestHeader("If-None-Match",c.etag[e.url])}u||H.setRequestHeader("X-Requested-With","XMLHttpRequest");H.setRequestHeader("Accept",e.dataType&&e.accepts[e.dataType]?e.accepts[e.dataType]+", */*":e.accepts._default)}catch(ya){}if(e.beforeSend&&e.beforeSend.call(l,H,e)===false){e.global&&!--c.active&&c.event.trigger("ajaxStop");
H.abort();return false}e.global&&f("ajaxSend",[H,e]);var g=H.onreadystatechange=function(t){if(!H||H.readyState===0||t==="abort"){ba||d();ba=true;if(H)H.onreadystatechange=c.noop}else if(!ba&&H&&(H.readyState===4||t==="timeout")){ba=true;H.onreadystatechange=c.noop;j=t==="timeout"?"timeout":!c.httpSuccess(H)?"error":e.ifModified&&c.httpNotModified(H,e.url)?"notmodified":"success";var s;if(j==="success")try{q=c.httpData(H,e.dataType,e)}catch(F){j="parsererror";s=F}if(j==="success"||j==="notmodified")i||
b();else c.handleError(e,H,j,s);d();t==="timeout"&&H.abort();if(e.async)H=null}};try{var h=H.abort;H.abort=function(){H&&h.call(H);g("abort")}}catch(m){}e.async&&e.timeout>0&&setTimeout(function(){H&&!ba&&g("timeout")},e.timeout);try{H.send(p==="POST"||p==="PUT"||p==="DELETE"?e.data:null)}catch(n){c.handleError(e,H,null,n);d()}e.async||g();return H}},handleError:function(a,b,d,f){if(a.error)a.error.call(a.context||a,b,d,f);if(a.global)(a.context?c(a.context):c.event).trigger("ajaxError",[b,a,f])},
active:0,httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===1223||a.status===0}catch(b){}return false},httpNotModified:function(a,b){var d=a.getResponseHeader("Last-Modified"),f=a.getResponseHeader("Etag");if(d)c.lastModified[b]=d;if(f)c.etag[b]=f;return a.status===304||a.status===0},httpData:function(a,b,d){var f=a.getResponseHeader("content-type")||"",e=b==="xml"||!b&&f.indexOf("xml")>=0;a=e?a.responseXML:a.responseText;
e&&a.documentElement.nodeName==="parsererror"&&c.error("parsererror");if(d&&d.dataFilter)a=d.dataFilter(a,b);if(typeof a==="string")if(b==="json"||!b&&f.indexOf("json")>=0)a=c.parseJSON(a);else if(b==="script"||!b&&f.indexOf("javascript")>=0)c.globalEval(a);return a},param:function(a,b){function d(j,q){if(c.isArray(q))c.each(q,function(l,p){b||/\[\]$/.test(j)?f(j,p):d(j+"["+(typeof p==="object"||c.isArray(p)?l:"")+"]",p)});else!b&&q!=null&&typeof q==="object"?c.each(q,function(l,p){d(j+"["+l+"]",
p)}):f(j,q)}function f(j,q){q=c.isFunction(q)?q():q;e[e.length]=encodeURIComponent(j)+"="+encodeURIComponent(q)}var e=[];if(b===C)b=c.ajaxSettings.traditional;if(c.isArray(a)||a.jquery)c.each(a,function(){f(this.name,this.value)});else for(var i in a)d(i,a[i]);return e.join("&").replace(Ab,"+")}});var Da={},Cb=/toggle|show|hide/,Db=/^([+-]=)?([\d+-.]+)(.*)$/,ta,Ga=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],
["opacity"]];c.fn.extend({show:function(a,b){if(a||a===0)return this.animate(W("show",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");this[a].style.display=d||"";if(c.css(this[a],"display")==="none"){d=this[a].nodeName;var f;if(Da[d])f=Da[d];else{var e=c("<"+d+" />").appendTo("body");f=e.css("display");if(f==="none")f="block";e.remove();Da[d]=f}c.data(this[a],"olddisplay",f)}}a=0;for(b=this.length;a<b;a++)this[a].style.display=c.data(this[a],"olddisplay")||"";return this}},
hide:function(a,b){if(a||a===0)return this.animate(W("hide",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");!d&&d!=="none"&&c.data(this[a],"olddisplay",c.css(this[a],"display"))}a=0;for(b=this.length;a<b;a++)this[a].style.display="none";return this}},_toggle:c.fn.toggle,toggle:function(a,b){var d=typeof a==="boolean";if(c.isFunction(a)&&c.isFunction(b))this._toggle.apply(this,arguments);else a==null||d?this.each(function(){var f=d?a:c(this).is(":hidden");c(this)[f?"show":
"hide"]()}):this.animate(W("toggle",3),a,b);return this},fadeTo:function(a,b,d){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d)},animate:function(a,b,d,f){var e=c.speed(b,d,f);if(c.isEmptyObject(a))return this.each(e.complete);return this[e.queue===false?"each":"queue"](function(){var i=c.extend({},e),j,q=this.nodeType===1&&c(this).is(":hidden"),l=this;for(j in a){var p=j.replace(Aa,Ba);if(j!==p){a[p]=a[j];delete a[j];j=p}if(a[j]==="hide"&&q||a[j]==="show"&&!q)return i.complete.call(this);
if((j==="height"||j==="width")&&this.style){i.display=c.css(this,"display");i.overflow=this.style.overflow}if(c.isArray(a[j])){(i.specialEasing=i.specialEasing||{})[j]=a[j][1];a[j]=a[j][0]}}if(i.overflow!=null)this.style.overflow="hidden";i.curAnim=c.extend({},a);c.each(a,function(u,D){var J=new c.fx(l,i,u);if(Cb.test(D))J[D==="toggle"?q?"show":"hide":D](a);else{var P=Db.exec(D),N=J.cur(true)||0;if(P){D=parseFloat(P[2]);var ba=P[3]||"px";if(ba!=="px"){l.style[u]=(D||1)+ba;N=(D||1)/J.cur(true)*N;l.style[u]=
N+ba}if(P[1])D=(P[1]==="-="?-1:1)*D+N;J.custom(N,D,ba)}else J.custom(N,D,"")}});return true})},stop:function(a,b){var d=c.timers;a&&this.queue([]);this.each(function(){for(var f=d.length-1;f>=0;f--)if(d[f].elem===this){b&&d[f](true);d.splice(f,1)}});b||this.dequeue();return this}});c.each({slideDown:W("show",1),slideUp:W("hide",1),slideToggle:W("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"}},function(a,b){c.fn[a]=function(d,f){return this.animate(b,d,f)}});c.extend({speed:function(a,
b,d){var f=a&&typeof a==="object"?a:{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};f.duration=c.fx.off?0:typeof f.duration==="number"?f.duration:c.fx.speeds[f.duration]||c.fx.speeds._default;f.old=f.complete;f.complete=function(){f.queue!==false&&c(this).dequeue();c.isFunction(f.old)&&f.old.call(this)};return f},easing:{linear:function(a,b,d,f){return d+f*a},swing:function(a,b,d,f){return(-Math.cos(a*Math.PI)/2+0.5)*f+d}},timers:[],fx:function(a,b,d){this.options=
b;this.elem=a;this.prop=d;if(!b.orig)b.orig={}}});c.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||c.fx.step._default)(this);if((this.prop==="height"||this.prop==="width")&&this.elem.style)this.elem.style.display="block"},cur:function(a){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];return(a=parseFloat(c.css(this.elem,this.prop,a)))&&a>-10000?a:parseFloat(c.curCSS(this.elem,
this.prop))||0},custom:function(a,b,d){function f(i){return e.step(i)}this.startTime=A();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;this.pos=this.state=0;var e=this;f.elem=this.elem;if(f()&&c.timers.push(f)&&!ta)ta=setInterval(c.fx.tick,13)},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=
c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b=A(),d=true;if(a||b>=this.options.duration+this.startTime){this.now=this.end;this.pos=this.state=1;this.update();this.options.curAnim[this.prop]=true;for(var f in this.options.curAnim)if(this.options.curAnim[f]!==true)d=false;if(d){if(this.options.display!=null){this.elem.style.overflow=this.options.overflow;a=c.data(this.elem,"olddisplay");this.elem.style.display=a?a:this.options.display;if(c.css(this.elem,
"display")==="none")this.elem.style.display="block"}this.options.hide&&c(this.elem).hide();if(this.options.hide||this.options.show)for(var e in this.options.curAnim)c.style(this.elem,e,this.options.orig[e]);this.options.complete.call(this.elem)}return false}else{e=b-this.startTime;this.state=e/this.options.duration;a=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||a](this.state,e,0,1,this.options.duration);
this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};c.extend(c.fx,{tick:function(){for(var a=c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||c.fx.stop()},stop:function(){clearInterval(ta);ta=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=
a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};c.fn.offset="getBoundingClientRect"in k.documentElement?function(a){var b=this[0];if(a)return this.each(function(e){c.offset.setOffset(this,a,e)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);var d=b.getBoundingClientRect(),f=b.ownerDocument;b=f.body;f=f.documentElement;return{top:d.top+(self.pageYOffset||c.support.boxModel&&
f.scrollTop||b.scrollTop)-(f.clientTop||b.clientTop||0),left:d.left+(self.pageXOffset||c.support.boxModel&&f.scrollLeft||b.scrollLeft)-(f.clientLeft||b.clientLeft||0)}}:function(a){var b=this[0];if(a)return this.each(function(u){c.offset.setOffset(this,a,u)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d=b.offsetParent,f=b,e=b.ownerDocument,i,j=e.documentElement,q=e.body;f=(e=e.defaultView)?e.getComputedStyle(b,null):b.currentStyle;
for(var l=b.offsetTop,p=b.offsetLeft;(b=b.parentNode)&&b!==q&&b!==j;){if(c.offset.supportsFixedPosition&&f.position==="fixed")break;i=e?e.getComputedStyle(b,null):b.currentStyle;l-=b.scrollTop;p-=b.scrollLeft;if(b===d){l+=b.offsetTop;p+=b.offsetLeft;if(c.offset.doesNotAddBorder&&!(c.offset.doesAddBorderForTableAndCells&&/^t(able|d|h)$/i.test(b.nodeName))){l+=parseFloat(i.borderTopWidth)||0;p+=parseFloat(i.borderLeftWidth)||0}f=d;d=b.offsetParent}if(c.offset.subtractsBorderForOverflowNotVisible&&i.overflow!==
"visible"){l+=parseFloat(i.borderTopWidth)||0;p+=parseFloat(i.borderLeftWidth)||0}f=i}if(f.position==="relative"||f.position==="static"){l+=q.offsetTop;p+=q.offsetLeft}if(c.offset.supportsFixedPosition&&f.position==="fixed"){l+=Math.max(j.scrollTop,q.scrollTop);p+=Math.max(j.scrollLeft,q.scrollLeft)}return{top:l,left:p}};c.offset={initialize:function(){var a=k.body,b=k.createElement("div"),d,f,e,i=parseFloat(c.curCSS(a,"marginTop",true))||0;c.extend(b.style,{position:"absolute",top:0,left:0,margin:0,
border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";a.insertBefore(b,a.firstChild);d=b.firstChild;f=d.firstChild;e=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=f.offsetTop!==5;this.doesAddBorderForTableAndCells=
e.offsetTop===5;f.style.position="fixed";f.style.top="20px";this.supportsFixedPosition=f.offsetTop===20||f.offsetTop===15;f.style.position=f.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=f.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==i;a.removeChild(b);c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();if(c.offset.doesNotIncludeMarginInBodyOffset){b+=parseFloat(c.curCSS(a,
"marginTop",true))||0;d+=parseFloat(c.curCSS(a,"marginLeft",true))||0}return{top:b,left:d}},setOffset:function(a,b,d){if(/static/.test(c.curCSS(a,"position")))a.style.position="relative";var f=c(a),e=f.offset(),i=parseInt(c.curCSS(a,"top",true),10)||0,j=parseInt(c.curCSS(a,"left",true),10)||0;if(c.isFunction(b))b=b.call(a,d,e);d={top:b.top-e.top+i,left:b.left-e.left+j};"using"in b?b.using.call(a,d):f.css(d)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),
d=this.offset(),f=/^body|html$/i.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.curCSS(a,"marginTop",true))||0;d.left-=parseFloat(c.curCSS(a,"marginLeft",true))||0;f.top+=parseFloat(c.curCSS(b[0],"borderTopWidth",true))||0;f.left+=parseFloat(c.curCSS(b[0],"borderLeftWidth",true))||0;return{top:d.top-f.top,left:d.left-f.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||k.body;a&&!/^body|html$/i.test(a.nodeName)&&c.css(a,"position")==="static";)a=
a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(f){var e=this[0],i;if(!e)return null;if(f!==C)return this.each(function(){if(i=X(this))i.scrollTo(!a?f:c(i).scrollLeft(),a?f:c(i).scrollTop());else this[d]=f});else return(i=X(e))?"pageXOffset"in i?i[a?"pageYOffset":"pageXOffset"]:c.support.boxModel&&i.document.documentElement[d]||i.document.body[d]:e[d]}});c.each(["Height","Width"],function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){return this[0]?
c.css(this[0],d,false,"padding"):null};c.fn["outer"+b]=function(f){return this[0]?c.css(this[0],d,false,f?"margin":"border"):null};c.fn[d]=function(f){var e=this[0];if(!e)return f==null?null:this;if(c.isFunction(f))return this.each(function(i){var j=c(this);j[d](f.call(this,i,j[d]()))});return"scrollTo"in e&&e.document?e.document.compatMode==="CSS1Compat"&&e.document.documentElement["client"+b]||e.document.body["client"+b]:e.nodeType===9?Math.max(e.documentElement["client"+b],e.body["scroll"+b],e.documentElement["scroll"+
b],e.body["offset"+b],e.documentElement["offset"+b]):f===C?c.css(e,d):this.css(d,typeof f==="string"?f:f+"px")}});if(V){var Za=require.callReady;require.callReady=function(){Za&&Za();c.callReady()};require.def("jquery",function(){return c});require.def("jQuery",function(){return c})}})(window);