/*

 jQuery JavaScript Library v1.4.2
 http://jquery.com/

 Copyright 2010, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2010, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Sat Feb 13 22:33:48 2010 -0500
*/
(function(){var M;(function(){function r(A){var v=L[A];if(v)return v;if(!w[A])throw new Error("Module "+A+" not found");for(var D=w[A],H=D.deps||(D.length?["require","exports","module"]:[]),K=L[A]={},u=0;u<H.length;u++){var z=H[u];switch(z){case "require":z=function(G){if(G.charAt(0)==="."){for(G=A.substring(0,A.lastIndexOf("/")+1)+G;Q!==G;){var Q=G;G=G.replace(/\/[^\/]*\/\.\.\//,"/")}G=G.replace(/\/\.\//g,"/")}return r(G)};break;case "exports":z=K;break;case "module":v=z={exports:K};break;default:z=
r(z)}H[u]=z}K=D.apply(this,H);if(v&&v.exports!=L[A])K=v.exports;if(K)return L[A]=K;return L[A]}var w={},L={};M=function(A,v){for(var D=[],H=0;H<A.length;H++)D.push(r(A[H]));v.apply(r,D)};M.def=function(A,v,D){if(typeof v=="function")w[A]=v;else(w[A]=D).deps=v}})();M.def("lingwo_dictionary/annotation/Reader2",["jquery"],function(r){function w(u,z,G){old_fn=u[z];u[z]=function(){old_fn.apply(this,arguments);G()}}function L(u){var z={},G;for(G in u)z[G]=u[G];return z}function A(u,z){return function(){return u.apply(z,
arguments)}}var v,D,H=/MSIE 6/i.test(navigator.userAgent),K={layout:"docked"};D={popup:{setup:function(){v.bubbleNode.addClass("popup")},shutdown:function(){v.bubbleNode.removeClass("popup")},show:function(){var u=v.selectedNode,z=v.bubbleNode,G=u.offset(),Q=G.left+u.width()/2-150;u=G.top+u.height()+40;G=r(document).width();if(Q+300>G)Q=G-300;if(Q<0)Q=0;z.show().css({left:Q,top:u,height:""});if(H||z.height()>200)z.css({height:200})},hide:function(){v.bubbleNode.hide()}},docked:{_dock:null,_footer:null,
_footerId:null,_footerMargin:null,_positionBubble:function(){v.bubbleNode.show();var u=v.bubbleNode,z=this._dock.offset(),G=this._footer.offset().top;u.outerWidth();u.innerWidth();var Q=u.outerHeight()-u.innerHeight(),U=Math.max(z.top-r(window).scrollTop()+1,0);G=Math.min(G-r(window).scrollTop()-U-this._footerMargin+1,r(window).height()-U)-Q;u.css({left:z.left-r(window).scrollLeft(),top:U,height:G})},_drupalHack:false,setup:function(){v.bubbleNode.addClass("docked");this._dock=r("#lingwo-korpus-dock");
this._footerId=this._dock.attr("data-footer-id");this._footerMargin=this._dock.attr("data-footer-margin");this._footer=r("#"+this._footerId);var u=A(this._positionBubble,this);r(window).bind("scroll.lingwoReaderDocked",u);r(window).bind("resize.lingwoReaderDocked",u);if(!this._drupalHack){typeof window.Drupal!="undefined"&&Drupal.adminToolbar&&w(Drupal.adminToolbar,"setState",function(){if(v.layout===D.docked){v.bubbleNode.hide();setTimeout(u,500)}});this._drupalHack=true}v.setBubbleContent("<em>Click a work in the text to look it up in the dictionary.</em>");
setTimeout(u,0)},shutdown:function(){v.bubbleNode.removeClass("docked");this._dock=this._footerId=this._footerMargin=this._footer=null;r(window).unbind(".lingwoReaderDocked")},show:function(){},hide:function(){}}};return v={defaultLayouts:D,onLoad:function(){},config:null,bubbleNode:null,contentNode:null,selectedNode:null,shown:false,isSetup:false,layout:null,setup:function(u){if(typeof u=="undefined")u=L(K);this.config=u;if(this.config.layout=="docked"&&H)this.config.layout="popup";if(this.isSetup){this.layout.shutdown();
this.layout=null;this.isSetup=false}if(!this.bubbleNode)this.bubbleNode=r("<div></div>").attr("id","lingwo-korpus-entry-view-wrapper").appendTo(r("body")).hide();if(!this.contentNode)this.contentNode=r("<div></div>").attr("id","lingwo-korpus-entry-view").appendTo(this.bubbleNode);u=typeof this.config.layout=="string"?D[this.config.layout]:this.config.layout;u.setup();this.config.skipHoverEvents||this.setupHoverEvents();this.layout=u;this.isSetup=false},setupHoverEvents:function(){var u=this;r(".anno, .anno-anchor").unbind("mouseenter mouseleave").bind("mouseenter",
function(z){z=r(z.target);z.addClass("hover");if(z=u._getAnnoText(z))z.addClass("hover")}).bind("mouseleave",function(z){z=r(z.target);z.removeClass("hover");if(z=u._getAnnoText(z))z.removeClass("hover")})},_getAnnoText:function(u){if(u.hasClass("anno-anchor"))if(u=u.attr("data-anno"))return r("#"+u);return null},setSelection:function(u){var z;if(this.selectedNode){this.selectedNode.removeClass("selected");if(z=this._getAnnoText(this.selectedNode))z.removeClass("selected");this.selectedNode=null}if(u){u=
r(u);u.addClass("selected");this.selectedNode=u;if(z=this._getAnnoText(this.selectedNode))z.addClass("selected")}},clearSelection:function(){this.setSelection(null)},isInsideBubble:function(u){for(;u=u.parentNode;)if(u.id=="lingwo-korpus-entry-view")return true;return false},showBubble:function(){this.layout.show();this.shown=true},hideBubble:function(){this.layout.hide();this.shown=false},setBubbleContent:function(u){this.contentNode.html(u)},setBubbleLoading:function(){this.setBubbleContent("Loading...")},
isWordNode:function(u){return r(u).hasClass("anno")||r(u).hasClass("anno-anchor")},handleClick:function(u){if(this.isWordNode(u)){if(this.isInsideBubble(u))this.onLoad(r(u));else{this.setSelection(u);this.onLoad(this.selectedNode);this.showBubble()}return false}this.clearSelection();this.hideBubble()}}});M.def("lingwo_dictionary/annotation/Embed",["jquery","lingwo_dictionary/annotation/Reader2"],function(r,w){function L(v,D,H){var K;for(K in D)if(!H||typeof v[K]=="undefined")v[K]=D[K]}var A={};if(typeof window.BiblioBird!=
"undefined")A=window.BiblioBird;L(A,{url:"http://www.bibliobird.com",lang:"en",showLinks:true,ga:true},true);L(A,{initialized:false,contentAreas:[],embedWindow:null,embedIframe:null,embedWindowShown:false,username:null,start:function(){var v=this;if(A.ga)A.ga=typeof window._gaq!="undefined";r(".bibliobird-content").each(function(){v.contentAreas.push(new ContentArea(this))})},initialize:function(v){function D(){var u=(r(window).width()-400)/2,z=(r(window).height()-200)/2;H.css({top:z,left:u})}if(!this.initialized){var H=
r('<div class="clear-block"><div class="bibliobird-embed-titlebar"><span class="bibliobird-embed-title">BiblioBird</span> <a href="#" class="bibliobird-embed-close">close</a></div></div>'),K=r('<iframe height="100%" width="100%" border="0" id="bibliobirdEmbedIframe" name="bibliobirdEmbedIframe"></iframe>').appendTo(H);H.css({width:400,height:200,position:"fixed",border:"1px solid black",background:"white",display:"none"}).appendTo(r("body"));r(".bibliobird-embed-close",H).click(function(){A.hideEmbedWindow();
return false});r(window).resize(D);setTimeout(D,0);w.setup({layout:"popup",skipHoverEvents:true});r("body").click(function(u){A.hideEmbedWindow();return w.handleClick(u.target)});L(this,{embedWindow:H,embedIframe:K,username:v,initialized:true})}},receiveMessage:function(v){if(v.indexOf("#login-successful")==0){v=v.split(":");if(v[1])this.username=v[1];this.hideEmbedWindow()}},openEmbedWindow:function(v){if(this.embedWindow!==null&&!this.embedWindowShown){this.embedIframe.attr("src",v);this.embedWindow.show();
this.embedWindowShown=true}},hideEmbedWindow:function(){if(this.embedWindow!==null&&this.embedWindowShown){this.embedWindow.hide();this.embedWindowShown=false;this.refreshAll()}},logout:function(){var v=this;r.ajax({url:A.url+"/lingwo_korpus/rlogout",dataType:"jsonp",success:function(){v.username=null;v.refreshAll()}})},refreshAll:function(){r.each(this.contentAreas,function(){this.refresh()})}});w.onLoad=function(v){v=(v.attr("data-entry")||"").split("#");var D=v[0],H=v[1];w.setBubbleLoading();r.ajax({url:A.url+
"/lingwo_korpus/lookup_entry",dataType:"jsonp",data:{hash:D,lang:A.lang},success:function(K){w.setBubbleContent(K.content);A.ga&&_gaq.push(["_trackEvent","BiblioBird","Anonymous Lookup",A.lang]);r(".node",w.contentNode).removeClass("clear-block").removeAttr("id");r("ul.links.inline",w.contentNode).remove();H&&r(".lingwo-sense-id-"+H,w.contentNode).addClass("selected");r("a",w.contentNode).each(function(u,z){u=z.href;var G;if(u){G=window.location.protocol+"//"+window.location.host;z.href=u.replace(G,
A.url);z.target="_blank"}})}})};ContentArea=function(v){this.node=v;this.url=r(v).attr("data-url")||(""+window.location.href).split("#")[0];this.teaser=r(v).attr("data-teaser")=="true";this.links=r('<div class="bibliobird-links"></div>').insertBefore(v);this.data={};this.lookupContent()};L(ContentArea.prototype,{lookupContent:function(){var v=this;r.ajax({url:A.url+"/lingwo_korpus/lookup_content",dataType:"jsonp",data:{url:this.url},success:function(D){A.initialize(D.username);v.data=D;v.rebuildLinks();
if(D.content){v.node.innerHTML=D.content;w.setupHoverEvents()}}})},rebuildLinks:function(){if(A.showLinks){var v=this.links,D=this.data;v.html("");if(A.username){v.append("Logged into BiblioBird as "+A.username+" ");v.append(r("<a></a>").html("Logout").attr("href",A.url+"/logout").click(function(){A.logout();return false}))}else{v.append("Not logged into BiblioBird ");v.append(r("<a></a>").html("Login").attr("href",A.url+"/lingwo_korpus/rlogin"+(A.localRelayUrl?"?relay="+A.localRelayUrl:"")).click(function(H){A.openEmbedWindow(H.target.href);
return false}));v.append(" ");v.append(r("<a></a>").html("Join BiblioBird").attr({href:A.url+"/user/register",target:"_blank"}))}v.append(" ");D.not_found&&v.append(r("<a></a>").html("Add to Bibliobird").attr({href:A.url+"/node/add/content?remote_url="+escape(this.url),target:"_blank"}))}},refresh:function(){this.rebuildLinks()}});return window.BiblioBird=A});(function(r,w){function L(){if(!c.isReady){try{t.documentElement.doScroll("left")}catch(a){setTimeout(L,1);return}c.ready()}}function A(a,b){b.src?
c.ajax({url:b.src,async:false,dataType:"script"}):c.globalEval(b.text||b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}function v(a,b,d,f,e,i){var j=a.length;if(typeof b==="object"){for(var o in b)v(a,o,b[o],f,e,d);return a}if(d!==w){f=!i&&f&&c.isFunction(d);for(o=0;o<j;o++)e(a[o],b,f?d.call(a[o],o,e(a[o],b)):d,i);return a}return j?e(a[0],b):w}function D(){return(new Date).getTime()}function H(){return false}function K(){return true}function u(a,b,d){d[0].type=a;return c.event.handle.apply(b,
d)}function z(a){var b,d=[],f=[],e=arguments,i,j,o,k,n,s;j=c.data(this,"events");if(!(a.liveFired===this||!j||!j.live||a.button&&a.type==="click")){a.liveFired=this;var y=j.live.slice(0);for(k=0;k<y.length;k++){j=y[k];j.origType.replace($,"")===a.type?f.push(j.selector):y.splice(k--,1)}i=c(a.target).closest(f,a.currentTarget);n=0;for(s=i.length;n<s;n++)for(k=0;k<y.length;k++){j=y[k];if(i[n].selector===j.selector){o=i[n].elem;f=null;if(j.preType==="mouseenter"||j.preType==="mouseleave")f=c(a.relatedTarget).closest(j.selector)[0];
if(!f||f!==o)d.push({elem:o,handleObj:j})}}n=0;for(s=d.length;n<s;n++){i=d[n];a.currentTarget=i.elem;a.data=i.handleObj.data;a.handleObj=i.handleObj;if(i.handleObj.origHandler.apply(i.elem,e)===false){b=false;break}}return b}}function G(a,b){return"live."+(a&&a!=="*"?a+".":"")+b.replace(/\./g,"`").replace(/ /g,"&")}function Q(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function U(a,b){var d=0;b.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var f=c.data(a[d++]),e=c.data(this,
f);if(f=f&&f.events){delete e.handle;e.events={};for(var i in f)for(var j in f[i])c.event.add(this,i,f[i][j],f[i][j].data)}}})}function va(a,b,d){var f,e,i;b=b&&b[0]?b[0].ownerDocument||b[0]:t;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===t&&!wa.test(a[0])&&(c.support.checkClone||!xa.test(a[0]))){e=true;if(i=c.fragments[a[0]])if(i!==1)f=i}if(!f){f=b.createDocumentFragment();c.clean(a,b,f,d)}if(e)c.fragments[a[0]]=i?f:1;return{fragment:f,cacheable:e}}function V(a,b){var d={};c.each(ya.concat.apply([],
ya.slice(0,b)),function(){d[this]=a});return d}function za(a){return"scrollTo"in a&&a.document?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var c=function(a,b){return new c.fn.init(a,b)},Ua=r.jQuery,Va=r.$,t=r.document,da,Wa=/^[^<]*(<[\w\W]+>)[^>]*$|^#([\w-]+)$/,Xa=/^.[^:#\[\.,]*$/,Ya=/\S/,Za=/^(\s|\u00A0)+|(\s|\u00A0)+$/g,$a=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,aa=navigator.userAgent,Aa=false,W=[],ha=!!(typeof M!=="undefined"&&M.def),X,ia=Object.prototype.toString,ja=Object.prototype.hasOwnProperty,
ka=Array.prototype.push,ba=Array.prototype.slice,Ba=Array.prototype.indexOf;c.fn=c.prototype={init:function(a,b){var d,f;if(!a)return this;if(a.nodeType){this.context=this[0]=a;this.length=1;return this}if(a==="body"&&!b){this.context=t;this[0]=t.body;this.selector="body";this.length=1;return this}if(typeof a==="string")if((d=Wa.exec(a))&&(d[1]||!b))if(d[1]){f=b?b.ownerDocument||b:t;if(a=$a.exec(a))if(c.isPlainObject(b)){a=[t.createElement(a[1])];c.fn.attr.call(a,b,true)}else a=[f.createElement(a[1])];
else{a=va([d[1]],[f]);a=(a.cacheable?a.fragment.cloneNode(true):a.fragment).childNodes}return c.merge(this,a)}else{if(b=t.getElementById(d[2])){if(b.id!==d[2])return da.find(a);this.length=1;this[0]=b}this.context=t;this.selector=a;return this}else if(!b&&/^\w+$/.test(a)){this.selector=a;this.context=t;a=t.getElementsByTagName(a);return c.merge(this,a)}else return!b||b.jquery?(b||da).find(a):c(b).find(a);else if(c.isFunction(a))return da.ready(a);if(a.selector!==w){this.selector=a.selector;this.context=
a.context}return c.makeArray(a,this)},selector:"",jquery:"1.4.2",length:0,size:function(){return this.length},toArray:function(){return ba.call(this,0)},get:function(a){return a==null?this.toArray():a<0?this.slice(a)[0]:this[a]},pushStack:function(a,b,d){var f=c();c.isArray(a)?ka.apply(f,a):c.merge(f,a);f.prevObject=this;f.context=this.context;if(b==="find")f.selector=this.selector+(this.selector?" ":"")+d;else if(b)f.selector=this.selector+"."+b+"("+d+")";return f},each:function(a,b){return c.each(this,
a,b)},ready:function(a){c.bindReady();if(c.isReady&&(!ha||M.s.isDone))a.call(t,c);else{W||(W=[]);W.push(a)}return this},eq:function(a){return a===-1?this.slice(a):this.slice(a,+a+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(ba.apply(this,arguments),"slice",ba.call(arguments).join(","))},map:function(a){return this.pushStack(c.map(this,function(b,d){return a.call(b,d,b)}))},end:function(){return this.prevObject||c(null)},push:ka,
sort:[].sort,splice:[].splice};c.fn.init.prototype=c.fn;c.extend=c.fn.extend=function(){var a=arguments[0]||{},b=1,d=arguments.length,f=false,e,i,j,o;if(typeof a==="boolean"){f=a;a=arguments[1]||{};b=2}if(typeof a!=="object"&&!c.isFunction(a))a={};if(d===b){a=this;--b}for(;b<d;b++)if((e=arguments[b])!=null)for(i in e){j=a[i];o=e[i];if(a!==o)if(f&&o&&(c.isPlainObject(o)||c.isArray(o))){j=j&&(c.isPlainObject(j)||c.isArray(j))?j:c.isArray(o)?[]:{};a[i]=c.extend(f,j,o)}else if(o!==w)a[i]=o}return a};
c.extend({noConflict:function(a){r.$=Va;if(a)r.jQuery=Ua;return c},isReady:false,ready:function(){if(!c.isReady){if(!t.body)return setTimeout(c.ready,13);c.isReady=true;c.callReady()}},callReady:function(){if(c.isReady&&(!ha||M.s.isDone)){if(W){for(var a,b=0;a=W[b++];)a.call(t,c);W=null}c.fn.triggerHandler&&c(t).triggerHandler("ready")}},bindReady:function(){if(!Aa){Aa=true;if(t.readyState==="complete")return c.ready();if(t.addEventListener){t.addEventListener("DOMContentLoaded",X,false);r.addEventListener("load",
c.ready,false)}else if(t.attachEvent){t.attachEvent("onreadystatechange",X);r.attachEvent("onload",c.ready);var a=false;try{a=r.frameElement==null}catch(b){}t.documentElement.doScroll&&a&&L()}}},isFunction:function(a){return ia.call(a)==="[object Function]"},isArray:function(a){return ia.call(a)==="[object Array]"},isPlainObject:function(a){if(!a||ia.call(a)!=="[object Object]"||a.nodeType||a.setInterval)return false;if(a.constructor&&!ja.call(a,"constructor")&&!ja.call(a.constructor.prototype,"isPrototypeOf"))return false;
var b;for(b in a);return b===w||ja.call(a,b)},isEmptyObject:function(a){for(var b in a)return false;return true},error:function(a){throw a;},parseJSON:function(a){if(typeof a!=="string"||!a)return null;a=c.trim(a);if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return r.JSON&&r.JSON.parse?r.JSON.parse(a):(new Function("return "+a))();else c.error("Invalid JSON: "+
a)},noop:function(){},globalEval:function(a){if(a&&Ya.test(a)){var b=t.getElementsByTagName("head")[0]||t.documentElement,d=t.createElement("script");d.type="text/javascript";if(c.support.scriptEval)d.appendChild(t.createTextNode(a));else d.text=a;b.insertBefore(d,b.firstChild);b.removeChild(d)}},nodeName:function(a,b){return a.nodeName&&a.nodeName.toUpperCase()===b.toUpperCase()},each:function(a,b,d){var f,e=0,i=a.length,j=i===w||c.isFunction(a);if(d)if(j)for(f in a){if(b.apply(a[f],d)===false)break}else for(;e<
i;){if(b.apply(a[e++],d)===false)break}else if(j)for(f in a){if(b.call(a[f],f,a[f])===false)break}else for(d=a[0];e<i&&b.call(d,e,d)!==false;d=a[++e]);return a},trim:function(a){return(a||"").replace(Za,"")},makeArray:function(a,b){b=b||[];if(a!=null)a.length==null||typeof a==="string"||c.isFunction(a)||typeof a!=="function"&&a.setInterval?ka.call(b,a):c.merge(b,a);return b},inArray:function(a,b){if(b.indexOf)return b.indexOf(a);for(var d=0,f=b.length;d<f;d++)if(b[d]===a)return d;return-1},merge:function(a,
b){var d=a.length,f=0;if(typeof b.length==="number")for(var e=b.length;f<e;f++)a[d++]=b[f];else for(;b[f]!==w;)a[d++]=b[f++];a.length=d;return a},grep:function(a,b,d){for(var f=[],e=0,i=a.length;e<i;e++)!d!==!b(a[e],e)&&f.push(a[e]);return f},map:function(a,b,d){for(var f=[],e,i=0,j=a.length;i<j;i++){e=b(a[i],i,d);if(e!=null)f[f.length]=e}return f.concat.apply([],f)},guid:1,proxy:function(a,b,d){if(arguments.length===2)if(typeof b==="string"){d=a;a=d[b];b=w}else if(b&&!c.isFunction(b)){d=b;b=w}if(!b&&
a)b=function(){return a.apply(d||this,arguments)};if(a)b.guid=a.guid=a.guid||b.guid||c.guid++;return b},uaMatch:function(a){a=a.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||!/compatible/.test(a)&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}},browser:{}});aa=c.uaMatch(aa);if(aa.browser){c.browser[aa.browser]=true;c.browser.version=aa.version}if(c.browser.webkit)c.browser.safari=true;
if(Ba)c.inArray=function(a,b){return Ba.call(b,a)};da=c(t);if(t.addEventListener)X=function(){t.removeEventListener("DOMContentLoaded",X,false);c.ready()};else if(t.attachEvent)X=function(){if(t.readyState==="complete"){t.detachEvent("onreadystatechange",X);c.ready()}};(function(){c.support={};var a=t.documentElement,b=t.createElement("script"),d=t.createElement("div"),f="script"+D();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";
var e=d.getElementsByTagName("*"),i=d.getElementsByTagName("a")[0];if(!(!e||!e.length||!i)){c.support={leadingWhitespace:d.firstChild.nodeType===3,tbody:!d.getElementsByTagName("tbody").length,htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(i.getAttribute("style")),hrefNormalized:i.getAttribute("href")==="/a",opacity:/^0.55$/.test(i.style.opacity),cssFloat:!!i.style.cssFloat,checkOn:d.getElementsByTagName("input")[0].value==="on",optSelected:t.createElement("select").appendChild(t.createElement("option")).selected,
parentNode:d.removeChild(d.appendChild(t.createElement("div"))).parentNode===null,deleteExpando:true,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null};b.type="text/javascript";try{b.appendChild(t.createTextNode("window."+f+"=1;"))}catch(j){}a.insertBefore(b,a.firstChild);if(r[f]){c.support.scriptEval=true;delete r[f]}try{delete b.test}catch(o){c.support.deleteExpando=false}a.removeChild(b);if(d.attachEvent&&d.fireEvent){d.attachEvent("onclick",function k(){c.support.noCloneEvent=
false;d.detachEvent("onclick",k)});d.cloneNode(true).fireEvent("onclick")}d=t.createElement("div");d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";a=t.createDocumentFragment();a.appendChild(d.firstChild);c.support.checkClone=a.cloneNode(true).cloneNode(true).lastChild.checked;c(function(){var k=t.createElement("div");k.style.width=k.style.paddingLeft="1px";t.body.appendChild(k);c.boxModel=c.support.boxModel=k.offsetWidth===2;t.body.removeChild(k).style.display="none"});a=function(k){var n=
t.createElement("div");k="on"+k;var s=k in n;if(!s){n.setAttribute(k,"return;");s=typeof n[k]==="function"}return s};c.support.submitBubbles=a("submit");c.support.changeBubbles=a("change");a=b=d=e=i=null}})();c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",frameborder:"frameBorder"};var R="jQuery"+D(),ab=0,Ca={};c.extend({cache:{},expando:R,noData:{embed:true,object:true,
applet:true},data:function(a,b,d){if(!(a.nodeName&&c.noData[a.nodeName.toLowerCase()])){a=a==r?Ca:a;var f=a[R],e=c.cache;if(!f&&typeof b==="string"&&d===w)return null;f||(f=++ab);if(typeof b==="object"){a[R]=f;e[f]=c.extend(true,{},b)}else if(!e[f]){a[R]=f;e[f]={}}a=e[f];if(d!==w)a[b]=d;return typeof b==="string"?a[b]:a}},removeData:function(a,b){if(!(a.nodeName&&c.noData[a.nodeName.toLowerCase()])){a=a==r?Ca:a;var d=a[R],f=c.cache,e=f[d];if(b){if(e){delete e[b];c.isEmptyObject(e)&&c.removeData(a)}}else{if(c.support.deleteExpando)delete a[c.expando];
else a.removeAttribute&&a.removeAttribute(c.expando);delete f[d]}}}});c.fn.extend({data:function(a,b){if(typeof a==="undefined"&&this.length)return c.data(this[0]);else if(typeof a==="object")return this.each(function(){c.data(this,a)});var d=a.split(".");d[1]=d[1]?"."+d[1]:"";if(b===w){var f=this.triggerHandler("getData"+d[1]+"!",[d[0]]);if(f===w&&this.length)f=c.data(this[0],a);return f===w&&d[1]?this.data(d[0]):f}else return this.trigger("setData"+d[1]+"!",[d[0],b]).each(function(){c.data(this,
a,b)})},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var f=c.data(a,b);if(!d)return f||[];if(!f||c.isArray(d))f=c.data(a,b,c.makeArray(d));else f.push(d);return f}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),f=d.shift();if(f==="inprogress")f=d.shift();if(f){b==="fx"&&d.unshift("inprogress");f.call(a,function(){c.dequeue(a,b)})}}});c.fn.extend({queue:function(a,b){if(typeof a!=="string"){b=a;a="fx"}if(b===
w)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,a,b);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||"fx",[])}});var Da=/[\n\t]/g,la=/\s+/,bb=/\r/g,cb=/href|src|style/,db=/(button|input)/i,eb=/(button|input|object|select|textarea)/i,
fb=/^(a|area)$/i,Ea=/radio|checkbox/;c.fn.extend({attr:function(a,b){return v(this,a,b,true,c.attr)},removeAttr:function(a){return this.each(function(){c.attr(this,a,"");this.nodeType===1&&this.removeAttribute(a)})},addClass:function(a){if(c.isFunction(a))return this.each(function(n){var s=c(this);s.addClass(a.call(this,n,s.attr("class")))});if(a&&typeof a==="string")for(var b=(a||"").split(la),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===1)if(e.className){for(var i=" "+e.className+" ",
j=e.className,o=0,k=b.length;o<k;o++)if(i.indexOf(" "+b[o]+" ")<0)j+=" "+b[o];e.className=c.trim(j)}else e.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(k){var n=c(this);n.removeClass(a.call(this,k,n.attr("class")))});if(a&&typeof a==="string"||a===w)for(var b=(a||"").split(la),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===1&&e.className)if(a){for(var i=(" "+e.className+" ").replace(Da," "),j=0,o=b.length;j<o;j++)i=i.replace(" "+b[j]+" ",
" ");e.className=c.trim(i)}else e.className=""}return this},toggleClass:function(a,b){var d=typeof a,f=typeof b==="boolean";if(c.isFunction(a))return this.each(function(e){var i=c(this);i.toggleClass(a.call(this,e,i.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var e,i=0,j=c(this),o=b,k=a.split(la);e=k[i++];){o=f?o:!j.hasClass(e);j[o?"addClass":"removeClass"](e)}else if(d==="undefined"||d==="boolean"){this.className&&c.data(this,"__className__",this.className);this.className=
this.className||a===false?"":c.data(this,"__className__")||""}})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if((" "+this[b].className+" ").replace(Da," ").indexOf(a)>-1)return true;return false},val:function(a){if(a===w){var b=this[0];if(b){if(c.nodeName(b,"option"))return(b.attributes.value||{}).specified?b.value:b.text;if(c.nodeName(b,"select")){var d=b.selectedIndex,f=[],e=b.options;b=b.type==="select-one";if(d<0)return null;var i=b?d:0;for(d=b?d+1:e.length;i<d;i++){var j=
e[i];if(j.selected){a=c(j).val();if(b)return a;f.push(a)}}return f}if(Ea.test(b.type)&&!c.support.checkOn)return b.getAttribute("value")===null?"on":b.value;return(b.value||"").replace(bb,"")}return w}var o=c.isFunction(a);return this.each(function(k){var n=c(this),s=a;if(this.nodeType===1){if(o)s=a.call(this,k,n.val());if(typeof s==="number")s+="";if(c.isArray(s)&&Ea.test(this.type))this.checked=c.inArray(n.val(),s)>=0;else if(c.nodeName(this,"select")){var y=c.makeArray(s);c("option",this).each(function(){this.selected=
c.inArray(c(this).val(),y)>=0});if(!y.length)this.selectedIndex=-1}else this.value=s}})}});c.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,b,d,f){if(!a||a.nodeType===3||a.nodeType===8)return w;if(f&&b in c.attrFn)return c(a)[b](d);f=a.nodeType!==1||!c.isXMLDoc(a);var e=d!==w;b=f&&c.props[b]||b;if(a.nodeType===1){var i=cb.test(b);if(b in a&&f&&!i){if(e){b==="type"&&db.test(a.nodeName)&&a.parentNode&&c.error("type property can't be changed");
a[b]=d}if(c.nodeName(a,"form")&&a.getAttributeNode(b))return a.getAttributeNode(b).nodeValue;if(b==="tabIndex")return(b=a.getAttributeNode("tabIndex"))&&b.specified?b.value:eb.test(a.nodeName)||fb.test(a.nodeName)&&a.href?0:w;return a[b]}if(!c.support.style&&f&&b==="style"){if(e)a.style.cssText=""+d;return a.style.cssText}e&&a.setAttribute(b,""+d);a=!c.support.hrefNormalized&&f&&i?a.getAttribute(b,2):a.getAttribute(b);return a===null?w:a}return c.style(a,b,d)}});var $=/\.(.*)$/,gb=function(a){return a.replace(/[^\w\s\.\|`]/g,
function(b){return"\\"+b})};c.event={add:function(a,b,d,f){if(!(a.nodeType===3||a.nodeType===8)){if(a.setInterval&&a!==r&&!a.frameElement)a=r;var e,i;if(d.handler){e=d;d=e.handler}if(!d.guid)d.guid=c.guid++;if(i=c.data(a)){var j=i.events=i.events||{},o=i.handle;if(!o)i.handle=o=function(){return typeof c!=="undefined"&&!c.event.triggered?c.event.handle.apply(o.elem,arguments):w};o.elem=a;b=b.split(" ");for(var k,n=0,s;k=b[n++];){i=e?c.extend({},e):{handler:d,data:f};if(k.indexOf(".")>-1){s=k.split(".");
k=s.shift();i.namespace=s.slice(0).sort().join(".")}else{s=[];i.namespace=""}i.type=k;i.guid=d.guid;var y=j[k],F=c.event.special[k]||{};if(!y){y=j[k]=[];if(!F.setup||F.setup.call(a,f,s,o)===false)if(a.addEventListener)a.addEventListener(k,o,false);else a.attachEvent&&a.attachEvent("on"+k,o)}if(F.add){F.add.call(a,i);if(!i.handler.guid)i.handler.guid=d.guid}y.push(i);c.event.global[k]=true}a=null}}},global:{},remove:function(a,b,d,f){if(!(a.nodeType===3||a.nodeType===8)){var e,i=0,j,o,k,n,s,y,F=c.data(a),
J=F&&F.events;if(F&&J){if(b&&b.type){d=b.handler;b=b.type}if(!b||typeof b==="string"&&b.charAt(0)==="."){b=b||"";for(e in J)c.event.remove(a,e+b)}else{for(b=b.split(" ");e=b[i++];){n=e;j=e.indexOf(".")<0;o=[];if(!j){o=e.split(".");e=o.shift();k=new RegExp("(^|\\.)"+c.map(o.slice(0).sort(),gb).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(s=J[e])if(d){n=c.event.special[e]||{};for(I=f||0;I<s.length;I++){y=s[I];if(d.guid===y.guid){if(j||k.test(y.namespace)){f==null&&s.splice(I--,1);n.remove&&n.remove.call(a,y)}if(f!=
null)break}}if(s.length===0||f!=null&&s.length===1){if(!n.teardown||n.teardown.call(a,o)===false)Fa(a,e,F.handle);delete J[e]}}else for(var I=0;I<s.length;I++){y=s[I];if(j||k.test(y.namespace)){c.event.remove(a,n,y.handler,I);s.splice(I--,1)}}}if(c.isEmptyObject(J)){if(b=F.handle)b.elem=null;delete F.events;delete F.handle;c.isEmptyObject(F)&&c.removeData(a)}}}}},trigger:function(a,b,d,f){var e=a.type||a;if(!f){a=typeof a==="object"?a[R]?a:c.extend(c.Event(e),a):c.Event(e);if(e.indexOf("!")>=0){a.type=
e=e.slice(0,-1);a.exclusive=true}if(!d){a.stopPropagation();c.event.global[e]&&c.each(c.cache,function(){this.events&&this.events[e]&&c.event.trigger(a,b,this.handle.elem)})}if(!d||d.nodeType===3||d.nodeType===8)return w;a.result=w;a.target=d;b=c.makeArray(b);b.unshift(a)}a.currentTarget=d;(f=c.data(d,"handle"))&&f.apply(d,b);f=d.parentNode||d.ownerDocument;try{if(!(d&&d.nodeName&&c.noData[d.nodeName.toLowerCase()]))if(d["on"+e]&&d["on"+e].apply(d,b)===false)a.result=false}catch(i){}if(!a.isPropagationStopped()&&
f)c.event.trigger(a,b,f,true);else if(!a.isDefaultPrevented()){f=a.target;var j,o=c.nodeName(f,"a")&&e==="click",k=c.event.special[e]||{};if((!k._default||k._default.call(d,a)===false)&&!o&&!(f&&f.nodeName&&c.noData[f.nodeName.toLowerCase()])){try{if(f[e]){if(j=f["on"+e])f["on"+e]=null;c.event.triggered=true;f[e]()}}catch(n){}if(j)f["on"+e]=j;c.event.triggered=false}}},handle:function(a){var b,d,f,e;a=arguments[0]=c.event.fix(a||r.event);a.currentTarget=this;b=a.type.indexOf(".")<0&&!a.exclusive;
if(!b){d=a.type.split(".");a.type=d.shift();f=new RegExp("(^|\\.)"+d.slice(0).sort().join("\\.(?:.*\\.)?")+"(\\.|$)")}e=c.data(this,"events");d=e[a.type];if(e&&d){d=d.slice(0);e=0;for(var i=d.length;e<i;e++){var j=d[e];if(b||f.test(j.namespace)){a.handler=j.handler;a.data=j.data;a.handleObj=j;j=j.handler.apply(this,arguments);if(j!==w){a.result=j;if(j===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY originalTarget pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),
fix:function(a){if(a[R])return a;var b=a;a=c.Event(b);for(var d=this.props.length,f;d;){f=this.props[--d];a[f]=b[f]}if(!a.target)a.target=a.srcElement||t;if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null){b=t.documentElement;d=t.body;a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(b&&b.scrollTop||
d&&d.scrollTop||0)-(b&&b.clientTop||d&&d.clientTop||0)}if(!a.which&&(a.charCode||a.charCode===0?a.charCode:a.keyCode))a.which=a.charCode||a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==w)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,a.origType,c.extend({},a,{handler:z}))},remove:function(a){var b=true,d=a.origType.replace($,"");c.each(c.data(this,
"events").live||[],function(){if(d===this.origType.replace($,""))return b=false});b&&c.event.remove(this,a.origType,z)}},beforeunload:{setup:function(a,b,d){if(this.setInterval)this.onbeforeunload=d;return false},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};var Fa=t.removeEventListener?function(a,b,d){a.removeEventListener(b,d,false)}:function(a,b,d){a.detachEvent("on"+b,d)};c.Event=function(a){if(!this.preventDefault)return new c.Event(a);if(a&&a.type){this.originalEvent=
a;this.type=a.type}else this.type=a;this.timeStamp=D();this[R]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=K;var a=this.originalEvent;if(a){a.preventDefault&&a.preventDefault();a.returnValue=false}},stopPropagation:function(){this.isPropagationStopped=K;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=K;this.stopPropagation()},isDefaultPrevented:H,isPropagationStopped:H,
isImmediatePropagationStopped:H};var Ga=function(a){var b=a.relatedTarget;try{for(;b&&b!==this;)b=b.parentNode;if(b!==this){a.type=a.data;c.event.handle.apply(this,arguments)}}catch(d){}},Ha=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?Ha:Ga,a)},teardown:function(d){c.event.remove(this,b,d&&d.selector?Ha:Ga)}}});if(!c.support.submitBubbles)c.event.special.submit=
{setup:function(){if(this.nodeName.toLowerCase()!=="form"){c.event.add(this,"click.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="submit"||d==="image")&&c(b).closest("form").length)return u("submit",this,arguments)});c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="text"||d==="password")&&c(b).closest("form").length&&a.keyCode===13)return u("submit",this,arguments)})}else return false},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var ma=
/textarea|input|select/i,na,Ia=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedIndex>-1?c.map(a.options,function(f){return f.selected}).join("-"):"";else if(a.nodeName.toLowerCase()==="select")d=a.selectedIndex;return d},oa=function(a,b){var d=a.target,f,e;if(!(!ma.test(d.nodeName)||d.readOnly)){f=c.data(d,"_change_data");e=Ia(d);if(a.type!=="focusout"||d.type!=="radio")c.data(d,"_change_data",e);if(!(f===w||e===f))if(f!=null||
e){a.type="change";return c.event.trigger(a,b,d)}}};c.event.special.change={filters:{focusout:oa,click:function(a){var b=a.target,d=b.type;if(d==="radio"||d==="checkbox"||b.nodeName.toLowerCase()==="select")return oa.call(this,a)},keydown:function(a){var b=a.target,d=b.type;if(a.keyCode===13&&b.nodeName.toLowerCase()!=="textarea"||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return oa.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,"_change_data",Ia(a))}},setup:function(){if(this.type===
"file")return false;for(var a in na)c.event.add(this,a+".specialChange",na[a]);return ma.test(this.nodeName)},teardown:function(){c.event.remove(this,".specialChange");return ma.test(this.nodeName)}};na=c.event.special.change.filters}t.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(f){f=c.event.fix(f);f.type=b;return c.event.handle.call(this,f)}c.event.special[b]={setup:function(){this.addEventListener(a,d,true)},teardown:function(){this.removeEventListener(a,
d,true)}}});c.each(["bind","one"],function(a,b){c.fn[b]=function(d,f,e){if(typeof d==="object"){for(var i in d)this[b](i,f,d[i],e);return this}if(c.isFunction(f)){e=f;f=w}var j=b==="one"?c.proxy(e,function(k){c(this).unbind(k,j);return e.apply(this,arguments)}):e;if(d==="unload"&&b!=="one")this.one(d,f,e);else{i=0;for(var o=this.length;i<o;i++)c.event.add(this[i],d,j,f)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,a[d]);else{d=
0;for(var f=this.length;d<f;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,d,f){return this.live(b,d,f,a)},undelegate:function(a,b,d){return arguments.length===0?this.unbind("live"):this.die(b,null,d,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0]){a=c.Event(a);a.preventDefault();a.stopPropagation();c.event.trigger(a,b,this[0]);return a.result}},toggle:function(a){for(var b=arguments,d=1;d<b.length;)c.proxy(a,
b[d++]);return this.click(c.proxy(a,function(f){var e=(c.data(this,"lastToggle"+a.guid)||0)%d;c.data(this,"lastToggle"+a.guid,e+1);f.preventDefault();return b[e].apply(this,arguments)||false}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var Ja={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(d,f,e,i){var j,o=0,k,n,s=i||this.selector,y=i?this:c(this.context);if(c.isFunction(f)){e=f;f=w}for(d=
(d||"").split(" ");(j=d[o++])!=null;){i=$.exec(j);k="";if(i){k=i[0];j=j.replace($,"")}if(j==="hover")d.push("mouseenter"+k,"mouseleave"+k);else{n=j;if(j==="focus"||j==="blur"){d.push(Ja[j]+k);j+=k}else j=(Ja[j]||j)+k;b==="live"?y.each(function(){c.event.add(this,G(j,s),{data:f,selector:s,handler:e,origType:j,origHandler:e,preType:n})}):y.unbind(G(j,s),e)}}return this}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),
function(a,b){c.fn[b]=function(d){return d?this.bind(b,d):this.trigger(b)};if(c.attrFn)c.attrFn[b]=true});r.attachEvent&&!r.addEventListener&&r.attachEvent("onunload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});(function(){function a(g){for(var h="",l,m=0;g[m];m++){l=g[m];if(l.nodeType===3||l.nodeType===4)h+=l.nodeValue;else if(l.nodeType!==8)h+=a(l.childNodes)}return h}function b(g,h,l,m,q,p){q=0;for(var B=m.length;q<B;q++){var x=m[q];
if(x){x=x[g];for(var E=false;x;){if(x.sizcache===l){E=m[x.sizset];break}if(x.nodeType===1&&!p){x.sizcache=l;x.sizset=q}if(x.nodeName.toLowerCase()===h){E=x;break}x=x[g]}m[q]=E}}}function d(g,h,l,m,q,p){q=0;for(var B=m.length;q<B;q++){var x=m[q];if(x){x=x[g];for(var E=false;x;){if(x.sizcache===l){E=m[x.sizset];break}if(x.nodeType===1){if(!p){x.sizcache=l;x.sizset=q}if(typeof h!=="string"){if(x===h){E=true;break}}else if(k.filter(h,[x]).length>0){E=x;break}}x=x[g]}m[q]=E}}}var f=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^[\]]*\]|['"][^'"]*['"]|[^[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,
e=0,i=Object.prototype.toString,j=false,o=true;[0,0].sort(function(){o=false;return 0});var k=function(g,h,l,m){l=l||[];var q=h=h||t;if(h.nodeType!==1&&h.nodeType!==9)return[];if(!g||typeof g!=="string")return l;for(var p=[],B,x,E,ca,S=true,Y=C(h),T=g;(f.exec(""),B=f.exec(T))!==null;){T=B[3];p.push(B[1]);if(B[2]){ca=B[3];break}}if(p.length>1&&s.exec(g))if(p.length===2&&n.relative[p[0]])x=pa(p[0]+p[1],h);else for(x=n.relative[p[0]]?[h]:k(p.shift(),h);p.length;){g=p.shift();if(n.relative[g])g+=p.shift();
x=pa(g,x)}else{if(!m&&p.length>1&&h.nodeType===9&&!Y&&n.match.ID.test(p[0])&&!n.match.ID.test(p[p.length-1])){B=k.find(p.shift(),h,Y);h=B.expr?k.filter(B.expr,B.set)[0]:B.set[0]}if(h){B=m?{expr:p.pop(),set:F(m)}:k.find(p.pop(),p.length===1&&(p[0]==="~"||p[0]==="+")&&h.parentNode?h.parentNode:h,Y);x=B.expr?k.filter(B.expr,B.set):B.set;if(p.length>0)E=F(x);else S=false;for(;p.length;){var N=p.pop();B=N;if(n.relative[N])B=p.pop();else N="";if(B==null)B=h;n.relative[N](E,B,Y)}}else E=[]}E||(E=x);E||k.error(N||
g);if(i.call(E)==="[object Array]")if(S)if(h&&h.nodeType===1)for(g=0;E[g]!=null;g++){if(E[g]&&(E[g]===true||E[g].nodeType===1&&O(h,E[g])))l.push(x[g])}else for(g=0;E[g]!=null;g++)E[g]&&E[g].nodeType===1&&l.push(x[g]);else l.push.apply(l,E);else F(E,l);if(ca){k(ca,q,l,m);k.uniqueSort(l)}return l};k.uniqueSort=function(g){if(I){j=o;g.sort(I);if(j)for(var h=1;h<g.length;h++)g[h]===g[h-1]&&g.splice(h--,1)}return g};k.matches=function(g,h){return k(g,null,null,h)};k.find=function(g,h,l){var m,q;if(!g)return[];
for(var p=0,B=n.order.length;p<B;p++){var x=n.order[p];if(q=n.leftMatch[x].exec(g)){var E=q[1];q.splice(1,1);if(E.substr(E.length-1)!=="\\"){q[1]=(q[1]||"").replace(/\\/g,"");m=n.find[x](q,h,l);if(m!=null){g=g.replace(n.match[x],"");break}}}}m||(m=h.getElementsByTagName("*"));return{set:m,expr:g}};k.filter=function(g,h,l,m){for(var q=g,p=[],B=h,x,E,ca=h&&h[0]&&C(h[0]);g&&h.length;){for(var S in n.filter)if((x=n.leftMatch[S].exec(g))!=null&&x[2]){var Y=n.filter[S],T,N;N=x[1];E=false;x.splice(1,1);
if(N.substr(N.length-1)!=="\\"){if(B===p)p=[];if(n.preFilter[S])if(x=n.preFilter[S](x,B,l,p,m,ca)){if(x===true)continue}else E=T=true;if(x)for(var ea=0;(N=B[ea])!=null;ea++)if(N){T=Y(N,x,ea,B);var Ka=m^!!T;if(l&&T!=null)if(Ka)E=true;else B[ea]=false;else if(Ka){p.push(N);E=true}}if(T!==w){l||(B=p);g=g.replace(n.match[S],"");if(!E)return[];break}}}if(g===q)if(E==null)k.error(g);else break;q=g}return B};k.error=function(g){throw"Syntax error, unrecognized expression: "+g;};var n=k.selectors={order:["ID",
"NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className",
"for":"htmlFor"},attrHandle:{href:function(g){return g.getAttribute("href")}},relative:{"+":function(g,h){var l=typeof h==="string",m=l&&!/\W/.test(h);l=l&&!m;if(m)h=h.toLowerCase();m=0;for(var q=g.length,p;m<q;m++)if(p=g[m]){for(;(p=p.previousSibling)&&p.nodeType!==1;);g[m]=l||p&&p.nodeName.toLowerCase()===h?p||false:p===h}l&&k.filter(h,g,true)},">":function(g,h){var l=typeof h==="string";if(l&&!/\W/.test(h)){h=h.toLowerCase();for(var m=0,q=g.length;m<q;m++){var p=g[m];if(p){l=p.parentNode;g[m]=
l.nodeName.toLowerCase()===h?l:false}}}else{m=0;for(q=g.length;m<q;m++)if(p=g[m])g[m]=l?p.parentNode:p.parentNode===h;l&&k.filter(h,g,true)}},"":function(g,h,l){var m=e++,q=d;if(typeof h==="string"&&!/\W/.test(h)){var p=h=h.toLowerCase();q=b}q("parentNode",h,m,g,p,l)},"~":function(g,h,l){var m=e++,q=d;if(typeof h==="string"&&!/\W/.test(h)){var p=h=h.toLowerCase();q=b}q("previousSibling",h,m,g,p,l)}},find:{ID:function(g,h,l){if(typeof h.getElementById!=="undefined"&&!l)return(g=h.getElementById(g[1]))?
[g]:[]},NAME:function(g,h){if(typeof h.getElementsByName!=="undefined"){var l=[];h=h.getElementsByName(g[1]);for(var m=0,q=h.length;m<q;m++)h[m].getAttribute("name")===g[1]&&l.push(h[m]);return l.length===0?null:l}},TAG:function(g,h){return h.getElementsByTagName(g[1])}},preFilter:{CLASS:function(g,h,l,m,q,p){g=" "+g[1].replace(/\\/g,"")+" ";if(p)return g;p=0;for(var B;(B=h[p])!=null;p++)if(B)if(q^(B.className&&(" "+B.className+" ").replace(/[\t\n]/g," ").indexOf(g)>=0))l||m.push(B);else if(l)h[p]=
false;return false},ID:function(g){return g[1].replace(/\\/g,"")},TAG:function(g){return g[1].toLowerCase()},CHILD:function(g){if(g[1]==="nth"){var h=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(g[2]==="even"&&"2n"||g[2]==="odd"&&"2n+1"||!/\D/.test(g[2])&&"0n+"+g[2]||g[2]);g[2]=h[1]+(h[2]||1)-0;g[3]=h[3]-0}g[0]=e++;return g},ATTR:function(g,h,l,m,q,p){h=g[1].replace(/\\/g,"");if(!p&&n.attrMap[h])g[1]=n.attrMap[h];if(g[2]==="~=")g[4]=" "+g[4]+" ";return g},PSEUDO:function(g,h,l,m,q){if(g[1]==="not")if((f.exec(g[3])||
"").length>1||/^\w/.test(g[3]))g[3]=k(g[3],null,null,h);else{g=k.filter(g[3],h,l,true^q);l||m.push.apply(m,g);return false}else if(n.match.POS.test(g[0])||n.match.CHILD.test(g[0]))return true;return g},POS:function(g){g.unshift(true);return g}},filters:{enabled:function(g){return g.disabled===false&&g.type!=="hidden"},disabled:function(g){return g.disabled===true},checked:function(g){return g.checked===true},selected:function(g){return g.selected===true},parent:function(g){return!!g.firstChild},empty:function(g){return!g.firstChild},
has:function(g,h,l){return!!k(l[3],g).length},header:function(g){return/h\d/i.test(g.nodeName)},text:function(g){return"text"===g.type},radio:function(g){return"radio"===g.type},checkbox:function(g){return"checkbox"===g.type},file:function(g){return"file"===g.type},password:function(g){return"password"===g.type},submit:function(g){return"submit"===g.type},image:function(g){return"image"===g.type},reset:function(g){return"reset"===g.type},button:function(g){return"button"===g.type||g.nodeName.toLowerCase()===
"button"},input:function(g){return/input|select|textarea|button/i.test(g.nodeName)}},setFilters:{first:function(g,h){return h===0},last:function(g,h,l,m){return h===m.length-1},even:function(g,h){return h%2===0},odd:function(g,h){return h%2===1},lt:function(g,h,l){return h<l[3]-0},gt:function(g,h,l){return h>l[3]-0},nth:function(g,h,l){return l[3]-0===h},eq:function(g,h,l){return l[3]-0===h}},filter:{PSEUDO:function(g,h,l,m){var q=h[1],p=n.filters[q];if(p)return p(g,l,h,m);else if(q==="contains")return(g.textContent||
g.innerText||a([g])||"").indexOf(h[3])>=0;else if(q==="not"){h=h[3];l=0;for(m=h.length;l<m;l++)if(h[l]===g)return false;return true}else k.error("Syntax error, unrecognized expression: "+q)},CHILD:function(g,h){var l=h[1],m=g;switch(l){case "only":case "first":for(;m=m.previousSibling;)if(m.nodeType===1)return false;if(l==="first")return true;m=g;case "last":for(;m=m.nextSibling;)if(m.nodeType===1)return false;return true;case "nth":l=h[2];var q=h[3];if(l===1&&q===0)return true;h=h[0];var p=g.parentNode;
if(p&&(p.sizcache!==h||!g.nodeIndex)){var B=0;for(m=p.firstChild;m;m=m.nextSibling)if(m.nodeType===1)m.nodeIndex=++B;p.sizcache=h}g=g.nodeIndex-q;return l===0?g===0:g%l===0&&g/l>=0}},ID:function(g,h){return g.nodeType===1&&g.getAttribute("id")===h},TAG:function(g,h){return h==="*"&&g.nodeType===1||g.nodeName.toLowerCase()===h},CLASS:function(g,h){return(" "+(g.className||g.getAttribute("class"))+" ").indexOf(h)>-1},ATTR:function(g,h){var l=h[1];g=n.attrHandle[l]?n.attrHandle[l](g):g[l]!=null?g[l]:
g.getAttribute(l);l=g+"";var m=h[2];h=h[4];return g==null?m==="!=":m==="="?l===h:m==="*="?l.indexOf(h)>=0:m==="~="?(" "+l+" ").indexOf(h)>=0:!h?l&&g!==false:m==="!="?l!==h:m==="^="?l.indexOf(h)===0:m==="$="?l.substr(l.length-h.length)===h:m==="|="?l===h||l.substr(0,h.length+1)===h+"-":false},POS:function(g,h,l,m){var q=n.setFilters[h[2]];if(q)return q(g,l,h,m)}}},s=n.match.POS;for(var y in n.match){n.match[y]=new RegExp(n.match[y].source+/(?![^\[]*\])(?![^\(]*\))/.source);n.leftMatch[y]=new RegExp(/(^(?:.|\r|\n)*?)/.source+
n.match[y].source.replace(/\\(\d+)/g,function(g,h){return"\\"+(h-0+1)}))}var F=function(g,h){g=Array.prototype.slice.call(g,0);if(h){h.push.apply(h,g);return h}return g};try{Array.prototype.slice.call(t.documentElement.childNodes,0)}catch(J){F=function(g,h){h=h||[];if(i.call(g)==="[object Array]")Array.prototype.push.apply(h,g);else if(typeof g.length==="number")for(var l=0,m=g.length;l<m;l++)h.push(g[l]);else for(l=0;g[l];l++)h.push(g[l]);return h}}var I;if(t.documentElement.compareDocumentPosition)I=
function(g,h){if(!g.compareDocumentPosition||!h.compareDocumentPosition){if(g==h)j=true;return g.compareDocumentPosition?-1:1}g=g.compareDocumentPosition(h)&4?-1:g===h?0:1;if(g===0)j=true;return g};else if("sourceIndex"in t.documentElement)I=function(g,h){if(!g.sourceIndex||!h.sourceIndex){if(g==h)j=true;return g.sourceIndex?-1:1}g=g.sourceIndex-h.sourceIndex;if(g===0)j=true;return g};else if(t.createRange)I=function(g,h){if(!g.ownerDocument||!h.ownerDocument){if(g==h)j=true;return g.ownerDocument?
-1:1}var l=g.ownerDocument.createRange(),m=h.ownerDocument.createRange();l.setStart(g,0);l.setEnd(g,0);m.setStart(h,0);m.setEnd(h,0);g=l.compareBoundaryPoints(Range.START_TO_END,m);if(g===0)j=true;return g};(function(){var g=t.createElement("div"),h="script"+(new Date).getTime();g.innerHTML="<a name='"+h+"'/>";var l=t.documentElement;l.insertBefore(g,l.firstChild);if(t.getElementById(h)){n.find.ID=function(m,q,p){if(typeof q.getElementById!=="undefined"&&!p)return(q=q.getElementById(m[1]))?q.id===
m[1]||typeof q.getAttributeNode!=="undefined"&&q.getAttributeNode("id").nodeValue===m[1]?[q]:w:[]};n.filter.ID=function(m,q){var p=typeof m.getAttributeNode!=="undefined"&&m.getAttributeNode("id");return m.nodeType===1&&p&&p.nodeValue===q}}l.removeChild(g);l=g=null})();(function(){var g=t.createElement("div");g.appendChild(t.createComment(""));if(g.getElementsByTagName("*").length>0)n.find.TAG=function(h,l){l=l.getElementsByTagName(h[1]);if(h[1]==="*"){h=[];for(var m=0;l[m];m++)l[m].nodeType===1&&
h.push(l[m]);l=h}return l};g.innerHTML="<a href='#'></a>";if(g.firstChild&&typeof g.firstChild.getAttribute!=="undefined"&&g.firstChild.getAttribute("href")!=="#")n.attrHandle.href=function(h){return h.getAttribute("href",2)};g=null})();t.querySelectorAll&&function(){var g=k,h=t.createElement("div");h.innerHTML="<p class='TEST'></p>";if(!(h.querySelectorAll&&h.querySelectorAll(".TEST").length===0)){k=function(m,q,p,B){q=q||t;if(!B&&q.nodeType===9&&!C(q))try{return F(q.querySelectorAll(m),p)}catch(x){}return g(m,
q,p,B)};for(var l in g)k[l]=g[l];h=null}}();(function(){var g=t.createElement("div");g.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!g.getElementsByClassName||g.getElementsByClassName("e").length===0)){g.lastChild.className="e";if(g.getElementsByClassName("e").length!==1){n.order.splice(1,0,"CLASS");n.find.CLASS=function(h,l,m){if(typeof l.getElementsByClassName!=="undefined"&&!m)return l.getElementsByClassName(h[1])};g=null}}})();var O=t.compareDocumentPosition?function(g,
h){return!!(g.compareDocumentPosition(h)&16)}:function(g,h){return g!==h&&(g.contains?g.contains(h):true)},C=function(g){return(g=(g?g.ownerDocument||g:0).documentElement)?g.nodeName!=="HTML":false},pa=function(g,h){var l=[],m="",q;for(h=h.nodeType?[h]:h;q=n.match.PSEUDO.exec(g);){m+=q[0];g=g.replace(n.match.PSEUDO,"")}g=n.relative[g]?g+"*":g;q=0;for(var p=h.length;q<p;q++)k(g,h[q],l);return k.filter(m,l)};c.find=k;c.expr=k.selectors;c.expr[":"]=c.expr.filters;c.unique=k.uniqueSort;c.text=a;c.isXMLDoc=
C;c.contains=O})();var hb=/Until$/,ib=/^(?:parents|prevUntil|prevAll)/,jb=/,/;ba=Array.prototype.slice;var La=function(a,b,d){if(c.isFunction(b))return c.grep(a,function(e,i){return!!b.call(e,i,e)===d});else if(b.nodeType)return c.grep(a,function(e){return e===b===d});else if(typeof b==="string"){var f=c.grep(a,function(e){return e.nodeType===1});if(Xa.test(b))return c.filter(b,f,!d);else b=c.filter(b,f)}return c.grep(a,function(e){return c.inArray(e,b)>=0===d})};c.fn.extend({find:function(a){for(var b=
this.pushStack("","find",a),d=0,f=0,e=this.length;f<e;f++){d=b.length;c.find(a,this[f],b);if(f>0)for(var i=d;i<b.length;i++)for(var j=0;j<d;j++)if(b[j]===b[i]){b.splice(i--,1);break}}return b},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,f=b.length;d<f;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushStack(La(this,a,false),"not",a)},filter:function(a){return this.pushStack(La(this,a,true),"filter",a)},is:function(a){return!!a&&c.filter(a,this).length>
0},closest:function(a,b){if(c.isArray(a)){var d=[],f=this[0],e,i={},j;if(f&&a.length){e=0;for(var o=a.length;e<o;e++){j=a[e];i[j]||(i[j]=c.expr.match.POS.test(j)?c(j,b||this.context):j)}for(;f&&f.ownerDocument&&f!==b;){for(j in i){e=i[j];if(e.jquery?e.index(f)>-1:c(f).is(e)){d.push({selector:j,elem:f});delete i[j]}}f=f.parentNode}}return d}var k=c.expr.match.POS.test(a)?c(a,b||this.context):null;return this.map(function(n,s){for(;s&&s.ownerDocument&&s!==b;){if(k?k.index(s)>-1:c(s).is(a))return s;
s=s.parentNode}return null})},index:function(a){if(!a||typeof a==="string")return c.inArray(this[0],a?c(a):this.parent().children());return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b||this.context):c.makeArray(a);b=c.merge(this.get(),a);return this.pushStack(Q(a[0])||Q(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},
parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},
contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,f){var e=c.map(this,b,d);hb.test(a)||(f=d);if(f&&typeof f==="string")e=c.filter(f,e);e=this.length>1?c.unique(e):e;if((this.length>1||jb.test(f))&&ib.test(a))e=e.reverse();return this.pushStack(e,a,ba.call(arguments).join(","))}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return c.find.matches(a,b)},dir:function(a,b,d){var f=[];for(a=
a[b];a&&a.nodeType!==9&&(d===w||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&f.push(a);a=a[b]}return f},nth:function(a,b,d){b=b||1;for(var f=0;a;a=a[d])if(a.nodeType===1&&++f===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var Ma=/ jQuery\d+="(?:\d+|null)"/g,fa=/^\s+/,Na=/(<([\w:]+)[^>]*?)\/>/g,kb=/^(?:area|br|col|embed|hr|img|input|link|meta|param)$/i,Oa=/<([\w:]+)/,lb=/<tbody/i,mb=/<|&#?\w+;/,wa=/<script|<object|<embed|<option|<style/i,
xa=/checked\s*(?:[^=]|=\s*.checked.)/i,Pa=function(a,b,d){return kb.test(d)?a:b+"></"+d+">"},P={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};P.optgroup=P.option;P.tbody=P.tfoot=P.colgroup=P.caption=P.thead;P.th=P.td;if(!c.support.htmlSerialize)P._default=
[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))});if(typeof a!=="object"&&a!==w)return this.empty().append((this[0]&&this[0].ownerDocument||t).createTextNode(a));return c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=
this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,
true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this)});else if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,
false,function(b){this.parentNode.insertBefore(b,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,f;(f=this[d])!=null;d++)if(!a||c.filter(a,[f]).length){if(!b&&f.nodeType===1){c.cleanData(f.getElementsByTagName("*"));c.cleanData([f])}f.parentNode&&f.parentNode.removeChild(f)}return this},empty:function(){for(var a=0,b;(b=this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);
return this},clone:function(a){var b=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var d=this.outerHTML,f=this.ownerDocument;if(!d){d=f.createElement("div");d.appendChild(this.cloneNode(true));d=d.innerHTML}return c.clean([d.replace(Ma,"").replace(/=([^="'>\s]+\/)>/g,'="$1">').replace(fa,"")],f)[0]}else return this.cloneNode(true)});if(a===true){U(this,b);U(this.find("*"),b.find("*"))}return b},html:function(a){if(a===w)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(Ma,
""):null;else if(typeof a==="string"&&!wa.test(a)&&(c.support.leadingWhitespace||!fa.test(a))&&!P[(Oa.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Na,Pa);try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1){c.cleanData(this[b].getElementsByTagName("*"));this[b].innerHTML=a}}catch(f){this.empty().append(a)}}else c.isFunction(a)?this.each(function(e){var i=c(this),j=i.html();i.empty().append(function(){return a.call(this,e,j)})}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&
this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=c(this),f=d.html();d.replaceWith(a.call(this,b,f))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a)},detach:function(a){return this.remove(a,true)},domManip:function(a,b,d){function f(y){return c.nodeName(y,"table")?y.getElementsByTagName("tbody")[0]||
y.appendChild(y.ownerDocument.createElement("tbody")):y}var e,i,j=a[0],o=[],k;if(!c.support.checkClone&&arguments.length===3&&typeof j==="string"&&xa.test(j))return this.each(function(){c(this).domManip(a,b,d,true)});if(c.isFunction(j))return this.each(function(y){var F=c(this);a[0]=j.call(this,y,b?F.html():w);F.domManip(a,b,d)});if(this[0]){e=j&&j.parentNode;e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:va(a,this,o);k=e.fragment;if(i=k.childNodes.length===
1?(k=k.firstChild):k.firstChild){b=b&&c.nodeName(i,"tr");for(var n=0,s=this.length;n<s;n++)d.call(b?f(this[n],i):this[n],n>0||e.cacheable||this.length>1?k.cloneNode(true):k)}o.length&&c.each(o,A)}return this}});c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(d){var f=[];d=c(d);var e=this.length===1&&this[0].parentNode;if(e&&e.nodeType===11&&e.childNodes.length===1&&d.length===1){d[b](this[0]);
return this}else{e=0;for(var i=d.length;e<i;e++){var j=(e>0?this.clone(true):this).get();c.fn[b].apply(c(d[e]),j);f=f.concat(j)}return this.pushStack(f,a,d.selector)}}});c.extend({clean:function(a,b,d,f){b=b||t;if(typeof b.createElement==="undefined")b=b.ownerDocument||b[0]&&b[0].ownerDocument||t;for(var e=[],i=0,j;(j=a[i])!=null;i++){if(typeof j==="number")j+="";if(j){if(typeof j==="string"&&!mb.test(j))j=b.createTextNode(j);else if(typeof j==="string"){j=j.replace(Na,Pa);var o=(Oa.exec(j)||["",
""])[1].toLowerCase(),k=P[o]||P._default,n=k[0],s=b.createElement("div");for(s.innerHTML=k[1]+j+k[2];n--;)s=s.lastChild;if(!c.support.tbody){n=lb.test(j);o=o==="table"&&!n?s.firstChild&&s.firstChild.childNodes:k[1]==="<table>"&&!n?s.childNodes:[];for(k=o.length-1;k>=0;--k)c.nodeName(o[k],"tbody")&&!o[k].childNodes.length&&o[k].parentNode.removeChild(o[k])}!c.support.leadingWhitespace&&fa.test(j)&&s.insertBefore(b.createTextNode(fa.exec(j)[0]),s.firstChild);j=s.childNodes}if(j.nodeType)e.push(j);else e=
c.merge(e,j)}}if(d)for(i=0;e[i];i++)if(f&&c.nodeName(e[i],"script")&&(!e[i].type||e[i].type.toLowerCase()==="text/javascript"))f.push(e[i].parentNode?e[i].parentNode.removeChild(e[i]):e[i]);else{e[i].nodeType===1&&e.splice.apply(e,[i+1,0].concat(c.makeArray(e[i].getElementsByTagName("script"))));d.appendChild(e[i])}return e},cleanData:function(a){for(var b,d,f=c.cache,e=c.event.special,i=c.support.deleteExpando,j=0,o;(o=a[j])!=null;j++)if(d=o[c.expando]){b=f[d];if(b.events)for(var k in b.events)e[k]?
c.event.remove(o,k):Fa(o,k,b.handle);if(i)delete o[c.expando];else o.removeAttribute&&o.removeAttribute(c.expando);delete f[d]}}});var nb=/z-?index|font-?weight|opacity|zoom|line-?height/i,Qa=/alpha\([^)]*\)/,Ra=/opacity=([^)]*)/,qa=/float/i,ra=/-([a-z])/ig,ob=/([A-Z])/g,pb=/^-?\d+(?:px)?$/i,qb=/^-?\d/,rb={position:"absolute",visibility:"hidden",display:"block"},sb=["Left","Right"],tb=["Top","Bottom"],ub=t.defaultView&&t.defaultView.getComputedStyle,Sa=c.support.cssFloat?"cssFloat":"styleFloat",sa=
function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){return v(this,a,b,true,function(d,f,e){if(e===w)return c.curCSS(d,f);if(typeof e==="number"&&!nb.test(f))e+="px";c.style(d,f,e)})};c.extend({style:function(a,b,d){if(!a||a.nodeType===3||a.nodeType===8)return w;if((b==="width"||b==="height")&&parseFloat(d)<0)d=w;var f=a.style||a,e=d!==w;if(!c.support.opacity&&b==="opacity"){if(e){f.zoom=1;b=parseInt(d,10)+""==="NaN"?"":"alpha(opacity="+d*100+")";a=f.filter||c.curCSS(a,"filter")||"";f.filter=
Qa.test(a)?a.replace(Qa,b):b}return f.filter&&f.filter.indexOf("opacity=")>=0?parseFloat(Ra.exec(f.filter)[1])/100+"":""}if(qa.test(b))b=Sa;b=b.replace(ra,sa);if(e)f[b]=d;return f[b]},css:function(a,b,d,f){if(b==="width"||b==="height"){var e,i=b==="width"?sb:tb;d=function(){e=b==="width"?a.offsetWidth:a.offsetHeight;f!=="border"&&c.each(i,function(){f||(e-=parseFloat(c.curCSS(a,"padding"+this,true))||0);if(f==="margin")e+=parseFloat(c.curCSS(a,"margin"+this,true))||0;else e-=parseFloat(c.curCSS(a,
"border"+this+"Width",true))||0})};a.offsetWidth!==0?d():c.swap(a,rb,d);return Math.max(0,Math.round(e))}return c.curCSS(a,b,d)},curCSS:function(a,b,d){var f,e=a.style;if(!c.support.opacity&&b==="opacity"&&a.currentStyle){f=Ra.test(a.currentStyle.filter||"")?parseFloat(RegExp.$1)/100+"":"";return f===""?"1":f}if(qa.test(b))b=Sa;if(!d&&e&&e[b])f=e[b];else if(ub){if(qa.test(b))b="float";b=b.replace(ob,"-$1").toLowerCase();e=a.ownerDocument.defaultView;if(!e)return null;if(a=e.getComputedStyle(a,null))f=
a.getPropertyValue(b);if(b==="opacity"&&f==="")f="1"}else if(a.currentStyle){d=b.replace(ra,sa);f=a.currentStyle[b]||a.currentStyle[d];if(!pb.test(f)&&qb.test(f)){b=e.left;var i=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;e.left=d==="fontSize"?"1em":f||0;f=e.pixelLeft+"px";e.left=b;a.runtimeStyle.left=i}}return f},swap:function(a,b,d){var f={};for(var e in b){f[e]=a.style[e];a.style[e]=b[e]}d.call(a);for(e in b)a.style[e]=f[e]}});if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=
a.offsetWidth,d=a.offsetHeight,f=a.nodeName.toLowerCase()==="tr";return b===0&&d===0&&!f?true:b>0&&d>0&&!f?false:c.curCSS(a,"display")==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}var vb=D(),wb=/<script(.|\s)*?\/script>/gi,xb=/select|textarea/i,yb=/color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week/i,Z=/=\?(&|$)/,ta=/\?/,zb=/(\?|&)_=.*?(&|$)/,Ab=/^(\w+:)?\/\/([^\/?#]+)/,Bb=/%20/g,Cb=c.fn.load;c.fn.extend({load:function(a,b,d){if(typeof a!==
"string")return Cb.call(this,a);else if(!this.length)return this;var f=a.indexOf(" ");if(f>=0){var e=a.slice(f,a.length);a=a.slice(0,f)}f="GET";if(b)if(c.isFunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);f="POST"}var i=this;c.ajax({url:a,type:f,dataType:"html",data:b,complete:function(j,o){if(o==="success"||o==="notmodified")i.html(e?c("<div />").append(j.responseText.replace(wb,"")).find(e):j.responseText);d&&i.each(d,[j.responseText,o,j])}});return this},
serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||xb.test(this.nodeName)||yb.test(this.type))}).map(function(a,b){a=c(this).val();return a==null?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,value:d}}):{name:b.name,value:a}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),
function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b=null}return c.ajax({type:"GET",url:a,data:b,success:d,dataType:f})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b={}}return c.ajax({type:"POST",url:a,data:b,success:d,dataType:f})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,
global:true,type:"GET",contentType:"application/x-www-form-urlencoded",processData:true,async:true,xhr:r.XMLHttpRequest&&(r.location.protocol!=="file:"||!r.ActiveXObject)?function(){return new r.XMLHttpRequest}:function(){try{return new r.ActiveXObject("Microsoft.XMLHTTP")}catch(a){}},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},lastModified:{},etag:{},ajax:function(a){function b(){e.success&&
e.success.call(k,o,j,C);e.global&&f("ajaxSuccess",[C,e])}function d(){e.complete&&e.complete.call(k,C,j);e.global&&f("ajaxComplete",[C,e]);e.global&&!--c.active&&c.event.trigger("ajaxStop")}function f(q,p){(e.context?c(e.context):c.event).trigger(q,p)}var e=c.extend(true,{},c.ajaxSettings,a),i,j,o,k=a&&a.context||e,n=e.type.toUpperCase();if(e.data&&e.processData&&typeof e.data!=="string")e.data=c.param(e.data,e.traditional);if(e.dataType==="jsonp"){if(n==="GET")Z.test(e.url)||(e.url+=(ta.test(e.url)?
"&":"?")+(e.jsonp||"callback")+"=?");else if(!e.data||!Z.test(e.data))e.data=(e.data?e.data+"&":"")+(e.jsonp||"callback")+"=?";e.dataType="json"}if(e.dataType==="json"&&(e.data&&Z.test(e.data)||Z.test(e.url))){i=e.jsonpCallback||"jsonp"+vb++;if(e.data)e.data=(e.data+"").replace(Z,"="+i+"$1");e.url=e.url.replace(Z,"="+i+"$1");e.dataType="script";r[i]=r[i]||function(q){o=q;b();d();r[i]=w;try{delete r[i]}catch(p){}F&&F.removeChild(J)}}if(e.dataType==="script"&&e.cache===null)e.cache=false;if(e.cache===
false&&n==="GET"){var s=D(),y=e.url.replace(zb,"$1_="+s+"$2");e.url=y+(y===e.url?(ta.test(e.url)?"&":"?")+"_="+s:"")}if(e.data&&n==="GET")e.url+=(ta.test(e.url)?"&":"?")+e.data;e.global&&!c.active++&&c.event.trigger("ajaxStart");s=(s=Ab.exec(e.url))&&(s[1]&&s[1]!==location.protocol||s[2]!==location.host);if(e.dataType==="script"&&n==="GET"&&s){var F=t.getElementsByTagName("head")[0]||t.documentElement,J=t.createElement("script");J.src=e.url;if(e.scriptCharset)J.charset=e.scriptCharset;if(!i){var I=
false;J.onload=J.onreadystatechange=function(){if(!I&&(!this.readyState||this.readyState==="loaded"||this.readyState==="complete")){I=true;b();d();J.onload=J.onreadystatechange=null;F&&J.parentNode&&F.removeChild(J)}}}F.insertBefore(J,F.firstChild);return w}var O=false,C=e.xhr();if(C){e.username?C.open(n,e.url,e.async,e.username,e.password):C.open(n,e.url,e.async);try{if(e.data||a&&a.contentType)C.setRequestHeader("Content-Type",e.contentType);if(e.ifModified){c.lastModified[e.url]&&C.setRequestHeader("If-Modified-Since",
c.lastModified[e.url]);c.etag[e.url]&&C.setRequestHeader("If-None-Match",c.etag[e.url])}s||C.setRequestHeader("X-Requested-With","XMLHttpRequest");C.setRequestHeader("Accept",e.dataType&&e.accepts[e.dataType]?e.accepts[e.dataType]+", */*":e.accepts._default)}catch(pa){}if(e.beforeSend&&e.beforeSend.call(k,C,e)===false){e.global&&!--c.active&&c.event.trigger("ajaxStop");C.abort();return false}e.global&&f("ajaxSend",[C,e]);var g=C.onreadystatechange=function(q){if(!C||C.readyState===0||q==="abort"){O||
d();O=true;if(C)C.onreadystatechange=c.noop}else if(!O&&C&&(C.readyState===4||q==="timeout")){O=true;C.onreadystatechange=c.noop;j=q==="timeout"?"timeout":!c.httpSuccess(C)?"error":e.ifModified&&c.httpNotModified(C,e.url)?"notmodified":"success";var p;if(j==="success")try{o=c.httpData(C,e.dataType,e)}catch(B){j="parsererror";p=B}if(j==="success"||j==="notmodified")i||b();else c.handleError(e,C,j,p);d();q==="timeout"&&C.abort();if(e.async)C=null}};try{var h=C.abort;C.abort=function(){C&&h.call(C);
g("abort")}}catch(l){}e.async&&e.timeout>0&&setTimeout(function(){C&&!O&&g("timeout")},e.timeout);try{C.send(n==="POST"||n==="PUT"||n==="DELETE"?e.data:null)}catch(m){c.handleError(e,C,null,m);d()}e.async||g();return C}},handleError:function(a,b,d,f){if(a.error)a.error.call(a.context||a,b,d,f);if(a.global)(a.context?c(a.context):c.event).trigger("ajaxError",[b,a,f])},active:0,httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===
1223||a.status===0}catch(b){}return false},httpNotModified:function(a,b){var d=a.getResponseHeader("Last-Modified"),f=a.getResponseHeader("Etag");if(d)c.lastModified[b]=d;if(f)c.etag[b]=f;return a.status===304||a.status===0},httpData:function(a,b,d){var f=a.getResponseHeader("content-type")||"",e=b==="xml"||!b&&f.indexOf("xml")>=0;a=e?a.responseXML:a.responseText;e&&a.documentElement.nodeName==="parsererror"&&c.error("parsererror");if(d&&d.dataFilter)a=d.dataFilter(a,b);if(typeof a==="string")if(b===
"json"||!b&&f.indexOf("json")>=0)a=c.parseJSON(a);else if(b==="script"||!b&&f.indexOf("javascript")>=0)c.globalEval(a);return a},param:function(a,b){function d(j,o){if(c.isArray(o))c.each(o,function(k,n){b||/\[\]$/.test(j)?f(j,n):d(j+"["+(typeof n==="object"||c.isArray(n)?k:"")+"]",n)});else!b&&o!=null&&typeof o==="object"?c.each(o,function(k,n){d(j+"["+k+"]",n)}):f(j,o)}function f(j,o){o=c.isFunction(o)?o():o;e[e.length]=encodeURIComponent(j)+"="+encodeURIComponent(o)}var e=[];if(b===w)b=c.ajaxSettings.traditional;
if(c.isArray(a)||a.jquery)c.each(a,function(){f(this.name,this.value)});else for(var i in a)d(i,a[i]);return e.join("&").replace(Bb,"+")}});var ua={},Db=/toggle|show|hide/,Eb=/^([+-]=)?([\d+-.]+)(.*)$/,ga,ya=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]];c.fn.extend({show:function(a,b){if(a||a===0)return this.animate(V("show",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");
this[a].style.display=d||"";if(c.css(this[a],"display")==="none"){d=this[a].nodeName;var f;if(ua[d])f=ua[d];else{var e=c("<"+d+" />").appendTo("body");f=e.css("display");if(f==="none")f="block";e.remove();ua[d]=f}c.data(this[a],"olddisplay",f)}}a=0;for(b=this.length;a<b;a++)this[a].style.display=c.data(this[a],"olddisplay")||"";return this}},hide:function(a,b){if(a||a===0)return this.animate(V("hide",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");!d&&d!=="none"&&c.data(this[a],
"olddisplay",c.css(this[a],"display"))}a=0;for(b=this.length;a<b;a++)this[a].style.display="none";return this}},_toggle:c.fn.toggle,toggle:function(a,b){var d=typeof a==="boolean";if(c.isFunction(a)&&c.isFunction(b))this._toggle.apply(this,arguments);else a==null||d?this.each(function(){var f=d?a:c(this).is(":hidden");c(this)[f?"show":"hide"]()}):this.animate(V("toggle",3),a,b);return this},fadeTo:function(a,b,d){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d)},
animate:function(a,b,d,f){var e=c.speed(b,d,f);if(c.isEmptyObject(a))return this.each(e.complete);return this[e.queue===false?"each":"queue"](function(){var i=c.extend({},e),j,o=this.nodeType===1&&c(this).is(":hidden"),k=this;for(j in a){var n=j.replace(ra,sa);if(j!==n){a[n]=a[j];delete a[j];j=n}if(a[j]==="hide"&&o||a[j]==="show"&&!o)return i.complete.call(this);if((j==="height"||j==="width")&&this.style){i.display=c.css(this,"display");i.overflow=this.style.overflow}if(c.isArray(a[j])){(i.specialEasing=
i.specialEasing||{})[j]=a[j][1];a[j]=a[j][0]}}if(i.overflow!=null)this.style.overflow="hidden";i.curAnim=c.extend({},a);c.each(a,function(s,y){var F=new c.fx(k,i,s);if(Db.test(y))F[y==="toggle"?o?"show":"hide":y](a);else{var J=Eb.exec(y),I=F.cur(true)||0;if(J){y=parseFloat(J[2]);var O=J[3]||"px";if(O!=="px"){k.style[s]=(y||1)+O;I=(y||1)/F.cur(true)*I;k.style[s]=I+O}if(J[1])y=(J[1]==="-="?-1:1)*y+I;F.custom(I,y,O)}else F.custom(I,y,"")}});return true})},stop:function(a,b){var d=c.timers;a&&this.queue([]);
this.each(function(){for(var f=d.length-1;f>=0;f--)if(d[f].elem===this){b&&d[f](true);d.splice(f,1)}});b||this.dequeue();return this}});c.each({slideDown:V("show",1),slideUp:V("hide",1),slideToggle:V("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"}},function(a,b){c.fn[a]=function(d,f){return this.animate(b,d,f)}});c.extend({speed:function(a,b,d){var f=a&&typeof a==="object"?a:{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};f.duration=c.fx.off?0:typeof f.duration===
"number"?f.duration:c.fx.speeds[f.duration]||c.fx.speeds._default;f.old=f.complete;f.complete=function(){f.queue!==false&&c(this).dequeue();c.isFunction(f.old)&&f.old.call(this)};return f},easing:{linear:function(a,b,d,f){return d+f*a},swing:function(a,b,d,f){return(-Math.cos(a*Math.PI)/2+0.5)*f+d}},timers:[],fx:function(a,b,d){this.options=b;this.elem=a;this.prop=d;if(!b.orig)b.orig={}}});c.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||
c.fx.step._default)(this);if((this.prop==="height"||this.prop==="width")&&this.elem.style)this.elem.style.display="block"},cur:function(a){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];return(a=parseFloat(c.css(this.elem,this.prop,a)))&&a>-10000?a:parseFloat(c.curCSS(this.elem,this.prop))||0},custom:function(a,b,d){function f(i){return e.step(i)}this.startTime=D();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;
this.pos=this.state=0;var e=this;f.elem=this.elem;if(f()&&c.timers.push(f)&&!ga)ga=setInterval(c.fx.tick,13)},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b=D(),d=true;if(a||b>=this.options.duration+this.startTime){this.now=
this.end;this.pos=this.state=1;this.update();this.options.curAnim[this.prop]=true;for(var f in this.options.curAnim)if(this.options.curAnim[f]!==true)d=false;if(d){if(this.options.display!=null){this.elem.style.overflow=this.options.overflow;a=c.data(this.elem,"olddisplay");this.elem.style.display=a?a:this.options.display;if(c.css(this.elem,"display")==="none")this.elem.style.display="block"}this.options.hide&&c(this.elem).hide();if(this.options.hide||this.options.show)for(var e in this.options.curAnim)c.style(this.elem,
e,this.options.orig[e]);this.options.complete.call(this.elem)}return false}else{e=b-this.startTime;this.state=e/this.options.duration;a=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||a](this.state,e,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};c.extend(c.fx,{tick:function(){for(var a=c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||
c.fx.stop()},stop:function(){clearInterval(ga);ga=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};c.fn.offset="getBoundingClientRect"in
t.documentElement?function(a){var b=this[0];if(a)return this.each(function(e){c.offset.setOffset(this,a,e)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);var d=b.getBoundingClientRect(),f=b.ownerDocument;b=f.body;f=f.documentElement;return{top:d.top+(self.pageYOffset||c.support.boxModel&&f.scrollTop||b.scrollTop)-(f.clientTop||b.clientTop||0),left:d.left+(self.pageXOffset||c.support.boxModel&&f.scrollLeft||b.scrollLeft)-(f.clientLeft||b.clientLeft||
0)}}:function(a){var b=this[0];if(a)return this.each(function(s){c.offset.setOffset(this,a,s)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d=b.offsetParent,f=b,e=b.ownerDocument,i,j=e.documentElement,o=e.body;f=(e=e.defaultView)?e.getComputedStyle(b,null):b.currentStyle;for(var k=b.offsetTop,n=b.offsetLeft;(b=b.parentNode)&&b!==o&&b!==j;){if(c.offset.supportsFixedPosition&&f.position==="fixed")break;i=e?e.getComputedStyle(b,
null):b.currentStyle;k-=b.scrollTop;n-=b.scrollLeft;if(b===d){k+=b.offsetTop;n+=b.offsetLeft;if(c.offset.doesNotAddBorder&&!(c.offset.doesAddBorderForTableAndCells&&/^t(able|d|h)$/i.test(b.nodeName))){k+=parseFloat(i.borderTopWidth)||0;n+=parseFloat(i.borderLeftWidth)||0}f=d;d=b.offsetParent}if(c.offset.subtractsBorderForOverflowNotVisible&&i.overflow!=="visible"){k+=parseFloat(i.borderTopWidth)||0;n+=parseFloat(i.borderLeftWidth)||0}f=i}if(f.position==="relative"||f.position==="static"){k+=o.offsetTop;
n+=o.offsetLeft}if(c.offset.supportsFixedPosition&&f.position==="fixed"){k+=Math.max(j.scrollTop,o.scrollTop);n+=Math.max(j.scrollLeft,o.scrollLeft)}return{top:k,left:n}};c.offset={initialize:function(){var a=t.body,b=t.createElement("div"),d,f,e,i=parseFloat(c.curCSS(a,"marginTop",true))||0;c.extend(b.style,{position:"absolute",top:0,left:0,margin:0,border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";
a.insertBefore(b,a.firstChild);d=b.firstChild;f=d.firstChild;e=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=f.offsetTop!==5;this.doesAddBorderForTableAndCells=e.offsetTop===5;f.style.position="fixed";f.style.top="20px";this.supportsFixedPosition=f.offsetTop===20||f.offsetTop===15;f.style.position=f.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=f.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==i;a.removeChild(b);
c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();if(c.offset.doesNotIncludeMarginInBodyOffset){b+=parseFloat(c.curCSS(a,"marginTop",true))||0;d+=parseFloat(c.curCSS(a,"marginLeft",true))||0}return{top:b,left:d}},setOffset:function(a,b,d){if(/static/.test(c.curCSS(a,"position")))a.style.position="relative";var f=c(a),e=f.offset(),i=parseInt(c.curCSS(a,"top",true),10)||0,j=parseInt(c.curCSS(a,"left",true),10)||0;if(c.isFunction(b))b=b.call(a,
d,e);d={top:b.top-e.top+i,left:b.left-e.left+j};"using"in b?b.using.call(a,d):f.css(d)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),d=this.offset(),f=/^body|html$/i.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.curCSS(a,"marginTop",true))||0;d.left-=parseFloat(c.curCSS(a,"marginLeft",true))||0;f.top+=parseFloat(c.curCSS(b[0],"borderTopWidth",true))||0;f.left+=parseFloat(c.curCSS(b[0],"borderLeftWidth",true))||0;return{top:d.top-
f.top,left:d.left-f.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||t.body;a&&!/^body|html$/i.test(a.nodeName)&&c.css(a,"position")==="static";)a=a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(f){var e=this[0],i;if(!e)return null;if(f!==w)return this.each(function(){if(i=za(this))i.scrollTo(!a?f:c(i).scrollLeft(),a?f:c(i).scrollTop());else this[d]=f});else return(i=za(e))?"pageXOffset"in i?i[a?"pageYOffset":
"pageXOffset"]:c.support.boxModel&&i.document.documentElement[d]||i.document.body[d]:e[d]}});c.each(["Height","Width"],function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){return this[0]?c.css(this[0],d,false,"padding"):null};c.fn["outer"+b]=function(f){return this[0]?c.css(this[0],d,false,f?"margin":"border"):null};c.fn[d]=function(f){var e=this[0];if(!e)return f==null?null:this;if(c.isFunction(f))return this.each(function(i){var j=c(this);j[d](f.call(this,i,j[d]()))});return"scrollTo"in
e&&e.document?e.document.compatMode==="CSS1Compat"&&e.document.documentElement["client"+b]||e.document.body["client"+b]:e.nodeType===9?Math.max(e.documentElement["client"+b],e.body["scroll"+b],e.documentElement["scroll"+b],e.body["offset"+b],e.documentElement["offset"+b]):f===w?c.css(e,d):this.css(d,typeof f==="string"?f:f+"px")}});if(ha){var Ta=M.callReady;M.callReady=function(){Ta&&Ta();c.callReady()};M.def("jquery",function(){return c});M.def("jQuery",function(){return c})}})(window);M(["lingwo_dictionary/annotation/Embed"],
function(r){r.start()})})();
