(function(){var n;(function(){function b(g){var c=f[g];if(c)return c;if(!m[g])throw new Error("Module "+g+" not found");for(var a=m[g],e=a.deps||(a.length?["require","exports","module"]:[]),h=f[g]={},j=0;j<e.length;j++){var i=e[j];switch(i){case "require":i=function(d){if(d.charAt(0)==="."){for(d=g.substring(0,g.lastIndexOf("/")+1)+d;l!==d;){var l=d;d=d.replace(/\/[^\/]*\/\.\.\//,"/")}d=d.replace(/\/\.\//g,"/")}return b(d)};break;case "exports":i=h;break;case "module":c=i={exports:h};break;default:i=
b(i)}e[j]=i}h=a.apply(this,e);if(c&&c.exports!=f[g])h=c.exports;if(h)return f[g]=h;return f[g]}var m={},f={};n=function(g,c){for(var a=[],e=0;e<g.length;e++)a.push(b(g[e]));c.apply(b,a)};n.def=function(g,c,a){if(typeof c=="function")m[g]=c;else(m[g]=a).deps=c}})();n.def("lingwo_dictionary/annotation/Reader",["jquery"],function(b){function m(d,l,k){old_fn=d[l];d[l]=function(){old_fn.apply(this,arguments);k()}}var f,g,c,a,e=false,h,j,i;return{callback:function(){},popup:true,activated:true,shown:false,
setup:function(d,l,k){function o(){if(!k){f.show();var p=c.offset(),q=a.offset().top;f.outerWidth();f.innerWidth();var s=f.outerHeight()-f.innerHeight(),r=Math.max(p.top-b(window).scrollTop()+1,0);q=Math.min(q-b(window).scrollTop()-r-j+1,b(window).height()-r)-s;f.css({left:p.left-b(window).scrollLeft(),top:r,height:q})}}this.callback=l;if(typeof k!=="undefined")this.popup=k;else k=this.popup;f||(f=b("<div></div>").attr("id","lingwo-korpus-entry-view-wrapper").addClass(k?"popup":"docked").appendTo(b("body")).hide());
g||(g=b("<div></div>").attr("id","lingwo-korpus-entry-view").appendTo(f));if(!c){c=b("#lingwo-korpus-dock",d);h=c.attr("data-footer-id");j=c.attr("data-footer-margin")}a||(a=b("#"+h,d));if(!k){g.html("<em>Click a word in the text to look it up in the dictionary.</em>");setTimeout(o,0)}if(!e){b(window).scroll(o);b(window).resize(o);typeof window.Drupal!=="undefined"&&Drupal.adminToolbar&&m(Drupal.adminToolbar,"setState",function(){if(!k){f.hide();setTimeout(o,500)}});e=true}},activate:function(d){d||
this.clearSelection();this.activated=d},clearSelection:function(){if(i){i.removeClass("selected");i=null}},hideDialog:function(){this.popup&&f.hide();this.shown=false;this.clearSelection()},showDialog:function(d){d=b(d);var l;this.clearSelection();l=d.offset();if(this.popup){var k=l.left+d.width()/2-150;l=l.top+d.height()+40;var o=b(document).width();if(k+300>o)k=o-300;if(k<0)k=0;f.show().css({left:k,top:l,height:""})}i=d;d.addClass("selected");this.shown=true;this.callback(d,g,function(p){p!==null&&
typeof p!=="undefined"&&g.html(p);this.popup&&f.height()>200&&f.css({height:200})})},onClick:function(d){if(!this.activated)return true;d=b(d.target);this.clearSelection();if(d.hasClass("anno")){this.showDialog(d);return false}this.hideDialog();return true}}});n.def("lingwo_dictionary/annotation/Embed",["jquery","lingwo_dictionary/annotation/Reader"],function(b,m){function f(a,e,h){var j;for(j in e)if(!h||typeof a[j]=="undefined")a[j]=e[j]}function g(a,e,h){var j=a.attr("data-sense");h("Loading ...");
b.ajax({url:c.url+"/lingwo_korpus/lookup_entry",dataType:"jsonp",data:{url:a.attr("href")},success:function(i){h(i.content);b(".node",e).removeClass("clear-block").removeAttr("id");b("ul.links.inline",e).remove();j&&b(".lingwo-sense-id-"+j,e).addClass("selected")}})}var c={};if(typeof window.BiblioBird!="undefined")c=window.BiblioBird;f(c,{url:"http://www.bibliobird.com",lang:"en"},true);f(c,{initialized:false,contentAreas:[],embedWindow:null,embedIframe:null,embedWindowShown:false,username:null,
start:function(){var a=this;b(".bibliobird-content").each(function(){a.contentAreas.push(new ContentArea(this))})},initialize:function(a){function e(){var i=(b(window).width()-400)/2,d=(b(window).height()-200)/2;h.css({top:d,left:i})}if(!this.initialized){var h=b('<div class="clear-block"><div class="bibliobird-embed-titlebar"><span class="bibliobird-embed-title">BiblioBird</span> <a href="#" class="bibliobird-embed-close">close</a></div></div>'),j=b('<iframe height="100%" width="100%" border="0" id="bibliobirdEmbedIframe" name="bibliobirdEmbedIframe"></iframe>').appendTo(h);
h.css({width:400,height:200,position:"fixed",border:"1px solid black",background:"white"}).hide().appendTo(b("body"));b(".bibliobird-embed-close",h).click(function(){c.hideEmbedWindow();return false});b(window).resize(e);setTimeout(e,0);m.setup(b("body"),g,true);b("body").click(function(i){c.hideEmbedWindow();return m.onClick(i)});f(this,{embedWindow:h,embedIframe:j,username:a,initialized:true})}},receiveMessage:function(a){if(a.indexOf("#login-successful")==0){a=a.split(":");if(a[1])this.username=
a[1];this.hideEmbedWindow()}},openEmbedWindow:function(a){if(this.embedWindow!==null&&!this.embedWindowShown){this.embedIframe.attr("src",a);this.embedWindow.show();this.embedWindowShown=true}},hideEmbedWindow:function(){if(this.embedWindow!==null&&this.embedWindowShown){this.embedWindow.hide();this.embedWindowShown=false;this.refreshAll()}},logout:function(){var a=this;b.ajax({url:c.url+"/lingwo_korpus/rlogout",dataType:"jsonp",success:function(){a.username=null;a.refreshAll()}})},refreshAll:function(){b.each(this.contentAreas,
function(){this.refresh()})}});ContentArea=function(a){this.node=a;this.from_lang=b(a).attr("data-from-lang");this.to_lang=b(a).attr("data-to-lang");this.url=b(a).attr("data-url")||window.location.href;this.teaser=b(a).attr("data-teaser")=="true";this.links=b('<div class="bibliobird-links"></div>').insertBefore(a);this.data={};this.lookupContent()};f(ContentArea.prototype,{lookupContent:function(){var a=this;b.ajax({url:c.url+"/lingwo_korpus/lookup_content",dataType:"jsonp",data:{url:this.url,to_lang:this.to_lang},
success:function(e){c.initialize(e.username);a.data=e;a.rebuildLinks();if(e.content)a.node.innerHTML=e.content}})},rebuildLinks:function(){var a=this.links,e=this.data;a.html("");if(c.username){a.append("Logged into BiblioBird as "+c.username+" ");a.append(b("<a></a>").html("Logout").attr("href",c.url+"/logout").click(function(){c.logout();return false}))}else{a.append("Not logged into BiblioBird ");a.append(b("<a></a>").html("Login").attr("href",c.url+"/lingwo_korpus/rlogin"+(c.localRelayUrl?"?relay="+
c.localRelayUrl:"")).click(function(h){c.openEmbedWindow(h.target.href);return false}));a.append(" ");a.append(b("<a></a>").html("Join BiblioBird").attr({href:c.url+"/user/register",target:"_blank"}))}a.append(" ");e.not_found&&a.append(b("<a></a>").html("Add to Bibliobird").attr({href:c.url+"/node/add/content?remote_url="+escape(this.url),target:"_blank"}))},refresh:function(){this.rebuildLinks()}});return window.BiblioBird=c});n.def("jquery",[],function(){return window.jQuery});n.def("jQuery",[],
function(){return window.jQuery});n(["lingwo_dictionary/annotation/Embed"],function(b){b.start()})})();
