<?php
// $Id$

/**
 * @file
 * Extends Lingwo Dictionary for annotating texts
 */

/**
 * Implementation of hook_menu().
 */
function lingwo_korpus_menu() {
  $items = array();
  $items['admin/settings/lingwo_dictionary/korpus'] = array(
    'title' => 'Korpus',
    'description' => 'Settings for Lingwo Korpus module.',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lingwo_korpus_admin_settings'),
    'file' => 'lingwo_korpus.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['lingwo_korpus/lookup_entry'] = array(
    'title' => 'Lookup Entry',
    'page arguments' => array(2),
    'page callback' => 'lingwo_korpus_lookup_entry',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function lingwo_korpus_lookup_entry() {
  // get the "Lingwo ID" out of the 'url' GET argument
  $url = urldecode($_GET['url']);
  $url = preg_replace(':^'.base_path().':', '', $url);
  $url = preg_replace(':^'.lingwo_dictionary_settings('lookup_path').'/:', '', $url);

  // load the node with this ID
  $node = node_load(lingwo_dictionary_entry_from_id($url));

  // return the HTML to the Ajax caller
  drupal_json(array(
    'content' => node_view($node, TRUE)
  ));
}

/*
 * Implementation of hook_nodeapi().
 */
function lingwo_korpus_nodeapi(&$node, $op, $a3=NULL, $a4=NULL) {
  global $user;

  if ($node->type != lingwo_korpus_text_content_type())
    return;

  switch ($op) {
    case 'view':
      if ($a4) {
        $lang_pair = ($node->language ? $node->language : language_default()) .'-'. $user->language;
        $node->content['body']['#value'] = lingwo_korpus_filter_text($node->content['body']['#value'], $lang_pair);

        drupal_add_js(drupal_get_path('module', 'lingwo_dictionary') .'/lingwo_korpus/annotation-reader.js');
        drupal_add_css(drupal_get_path('module', 'lingwo_dictionary') .'/lingwo_korpus/annotation-reader.css');
      }
      break;
  }
}

function lingwo_korpus_filter_text($text, $lang_pair) {
  require_once(drupal_get_path('module', 'lingwo_dictionary') .'/includes/3rdparty/simplehtmldom/simple_html_dom.php');

  $html = str_get_html($text); 
  foreach($html->find('anno') as $el) {
    // get all the attributes and clear them
    $attrs = $el->attr;
    $el->attr = array();

    // get the headword
    $headword = isset($attrs['headword']) ? $attrs['headword'] : $el->plaintext;

    // convert to a link
    $el->tag = 'a';
    $el->class = 'anno';
    $el->href = url(lingwo_dictionary_settings('lookup_path').'/'.$lang_pair.'/'.$headword.'('.$attrs['pos'].')');
    $el->setAttribute('data-form', $attrs['form']);
    $el->setAttribute('data-sense', $attrs['sense']);
  }

  return $html->outertext;

}

/*
 * Settings
 */
function lingwo_korpus_text_content_type($value=NULL) {
  if (is_null($value)) {
    return variable_get('lingwo_korpus_text_content_type', '');
  }

  variable_set('lingwo_korpus_text_content_type', $value);
}

