<?php
// $Id$

/**
 * @file
 * For importing dictionary data from external sources
 */

/*
 * Implementation of hook_services()
 */
function lingwo_import_service() {
  return array(
    // lingwo_import.update_entry
    array(
      '#method' => 'lingwo_import.update_entry',
      '#callback' => 'lingwo_import_service_update_entry',
      // TODO: access is a difficult problem..  Work it out later.
      //'#access callback' => 'lingwo_import_service_update_entry_access',
      '#file' => array('file' => 'service.inc', 'module' => 'lingwo_import'),
      '#args' => array(
        array(
          '#name' => 'data',
          '#type' => 'string',
          '#description' => t('A JSON string representing an entry.')
        ),
      ),
      '#return' => 'string',
      '#help' => t('Update an entry in the database.'),
    ),


  );
}


